// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CLIENT_H_
#define FLATBUFFERS_GENERATED_CLIENT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

struct ClientHeartbeat;
struct ClientHeartbeatBuilder;

struct ClientInScene;
struct ClientInSceneBuilder;

struct ClientOutScene;
struct ClientOutSceneBuilder;

struct ClientMove;
struct ClientMoveBuilder;

struct ClientHeartbeat FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientHeartbeatBuilder Builder;
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct ClientHeartbeatBuilder {
  typedef ClientHeartbeat Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit ClientHeartbeatBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientHeartbeat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientHeartbeat>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientHeartbeat> CreateClientHeartbeat(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  ClientHeartbeatBuilder builder_(_fbb);
  return builder_.Finish();
}

struct ClientInScene FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientInSceneBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SCENE_ID = 4
  };
  uint32_t scene_id() const {
    return GetField<uint32_t>(VT_SCENE_ID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_SCENE_ID, 4) &&
           verifier.EndTable();
  }
};

struct ClientInSceneBuilder {
  typedef ClientInScene Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_scene_id(uint32_t scene_id) {
    fbb_.AddElement<uint32_t>(ClientInScene::VT_SCENE_ID, scene_id, 0);
  }
  explicit ClientInSceneBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientInScene> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientInScene>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientInScene> CreateClientInScene(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t scene_id = 0) {
  ClientInSceneBuilder builder_(_fbb);
  builder_.add_scene_id(scene_id);
  return builder_.Finish();
}

struct ClientOutScene FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientOutSceneBuilder Builder;
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct ClientOutSceneBuilder {
  typedef ClientOutScene Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit ClientOutSceneBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientOutScene> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientOutScene>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientOutScene> CreateClientOutScene(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  ClientOutSceneBuilder builder_(_fbb);
  return builder_.Finish();
}

struct ClientMove FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientMoveBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X1 = 4,
    VT_X2 = 6,
    VT_Y1 = 8,
    VT_Y2 = 10,
    VT_TIME = 12
  };
  float x1() const {
    return GetField<float>(VT_X1, 0.0f);
  }
  float x2() const {
    return GetField<float>(VT_X2, 0.0f);
  }
  float y1() const {
    return GetField<float>(VT_Y1, 0.0f);
  }
  float y2() const {
    return GetField<float>(VT_Y2, 0.0f);
  }
  uint32_t time() const {
    return GetField<uint32_t>(VT_TIME, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X1, 4) &&
           VerifyField<float>(verifier, VT_X2, 4) &&
           VerifyField<float>(verifier, VT_Y1, 4) &&
           VerifyField<float>(verifier, VT_Y2, 4) &&
           VerifyField<uint32_t>(verifier, VT_TIME, 4) &&
           verifier.EndTable();
  }
};

struct ClientMoveBuilder {
  typedef ClientMove Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x1(float x1) {
    fbb_.AddElement<float>(ClientMove::VT_X1, x1, 0.0f);
  }
  void add_x2(float x2) {
    fbb_.AddElement<float>(ClientMove::VT_X2, x2, 0.0f);
  }
  void add_y1(float y1) {
    fbb_.AddElement<float>(ClientMove::VT_Y1, y1, 0.0f);
  }
  void add_y2(float y2) {
    fbb_.AddElement<float>(ClientMove::VT_Y2, y2, 0.0f);
  }
  void add_time(uint32_t time) {
    fbb_.AddElement<uint32_t>(ClientMove::VT_TIME, time, 0);
  }
  explicit ClientMoveBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientMove> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientMove>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientMove> CreateClientMove(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x1 = 0.0f,
    float x2 = 0.0f,
    float y1 = 0.0f,
    float y2 = 0.0f,
    uint32_t time = 0) {
  ClientMoveBuilder builder_(_fbb);
  builder_.add_time(time);
  builder_.add_y2(y2);
  builder_.add_y1(y1);
  builder_.add_x2(x2);
  builder_.add_x1(x1);
  return builder_.Finish();
}

#endif  // FLATBUFFERS_GENERATED_CLIENT_H_
