// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CLIENT_FBS_H_
#define FLATBUFFERS_GENERATED_CLIENT_FBS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "common.h"

namespace fbs {

struct ClientHeartbeat;
struct ClientHeartbeatBuilder;
struct ClientHeartbeatT;

struct ClientScene;
struct ClientSceneBuilder;
struct ClientSceneT;

struct ClientCharacterMove;
struct ClientCharacterMoveBuilder;
struct ClientCharacterMoveT;

struct ClientVisibleMob;
struct ClientVisibleMobBuilder;
struct ClientVisibleMobT;

struct ClientHeartbeatT : public ::flatbuffers::NativeTable {
  typedef ClientHeartbeat TableType;
};

struct ClientHeartbeat FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientHeartbeatT NativeTableType;
  typedef ClientHeartbeatBuilder Builder;
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
  ClientHeartbeatT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ClientHeartbeatT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ClientHeartbeat> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientHeartbeatT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ClientHeartbeatBuilder {
  typedef ClientHeartbeat Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit ClientHeartbeatBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientHeartbeat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientHeartbeat>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientHeartbeat> CreateClientHeartbeat(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  ClientHeartbeatBuilder builder_(_fbb);
  return builder_.Finish();
}

::flatbuffers::Offset<ClientHeartbeat> CreateClientHeartbeat(::flatbuffers::FlatBufferBuilder &_fbb, const ClientHeartbeatT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ClientSceneT : public ::flatbuffers::NativeTable {
  typedef ClientScene TableType;
  bool come = false;
  uint32_t map_id = 0;
  std::unique_ptr<fbs::CharacterT> character{};
  ClientSceneT() = default;
  ClientSceneT(const ClientSceneT &o);
  ClientSceneT(ClientSceneT&&) FLATBUFFERS_NOEXCEPT = default;
  ClientSceneT &operator=(ClientSceneT o) FLATBUFFERS_NOEXCEPT;
};

struct ClientScene FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientSceneT NativeTableType;
  typedef ClientSceneBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_COME = 4,
    VT_MAP_ID = 6,
    VT_CHARACTER = 8
  };
  bool come() const {
    return GetField<uint8_t>(VT_COME, 0) != 0;
  }
  bool mutate_come(bool _come = 0) {
    return SetField<uint8_t>(VT_COME, static_cast<uint8_t>(_come), 0);
  }
  uint32_t map_id() const {
    return GetField<uint32_t>(VT_MAP_ID, 0);
  }
  bool mutate_map_id(uint32_t _map_id = 0) {
    return SetField<uint32_t>(VT_MAP_ID, _map_id, 0);
  }
  const fbs::Character *character() const {
    return GetPointer<const fbs::Character *>(VT_CHARACTER);
  }
  fbs::Character *mutable_character() {
    return GetPointer<fbs::Character *>(VT_CHARACTER);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_COME, 1) &&
           VerifyField<uint32_t>(verifier, VT_MAP_ID, 4) &&
           VerifyOffset(verifier, VT_CHARACTER) &&
           verifier.VerifyTable(character()) &&
           verifier.EndTable();
  }
  ClientSceneT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ClientSceneT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ClientScene> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientSceneT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ClientSceneBuilder {
  typedef ClientScene Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_come(bool come) {
    fbb_.AddElement<uint8_t>(ClientScene::VT_COME, static_cast<uint8_t>(come), 0);
  }
  void add_map_id(uint32_t map_id) {
    fbb_.AddElement<uint32_t>(ClientScene::VT_MAP_ID, map_id, 0);
  }
  void add_character(::flatbuffers::Offset<fbs::Character> character) {
    fbb_.AddOffset(ClientScene::VT_CHARACTER, character);
  }
  explicit ClientSceneBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientScene> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientScene>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientScene> CreateClientScene(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool come = false,
    uint32_t map_id = 0,
    ::flatbuffers::Offset<fbs::Character> character = 0) {
  ClientSceneBuilder builder_(_fbb);
  builder_.add_character(character);
  builder_.add_map_id(map_id);
  builder_.add_come(come);
  return builder_.Finish();
}

::flatbuffers::Offset<ClientScene> CreateClientScene(::flatbuffers::FlatBufferBuilder &_fbb, const ClientSceneT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ClientCharacterMoveT : public ::flatbuffers::NativeTable {
  typedef ClientCharacterMove TableType;
  std::unique_ptr<fbs::MovementT> movement{};
  ClientCharacterMoveT() = default;
  ClientCharacterMoveT(const ClientCharacterMoveT &o);
  ClientCharacterMoveT(ClientCharacterMoveT&&) FLATBUFFERS_NOEXCEPT = default;
  ClientCharacterMoveT &operator=(ClientCharacterMoveT o) FLATBUFFERS_NOEXCEPT;
};

struct ClientCharacterMove FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientCharacterMoveT NativeTableType;
  typedef ClientCharacterMoveBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MOVEMENT = 4
  };
  const fbs::Movement *movement() const {
    return GetPointer<const fbs::Movement *>(VT_MOVEMENT);
  }
  fbs::Movement *mutable_movement() {
    return GetPointer<fbs::Movement *>(VT_MOVEMENT);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MOVEMENT) &&
           verifier.VerifyTable(movement()) &&
           verifier.EndTable();
  }
  ClientCharacterMoveT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ClientCharacterMoveT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ClientCharacterMove> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientCharacterMoveT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ClientCharacterMoveBuilder {
  typedef ClientCharacterMove Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_movement(::flatbuffers::Offset<fbs::Movement> movement) {
    fbb_.AddOffset(ClientCharacterMove::VT_MOVEMENT, movement);
  }
  explicit ClientCharacterMoveBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientCharacterMove> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientCharacterMove>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientCharacterMove> CreateClientCharacterMove(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<fbs::Movement> movement = 0) {
  ClientCharacterMoveBuilder builder_(_fbb);
  builder_.add_movement(movement);
  return builder_.Finish();
}

::flatbuffers::Offset<ClientCharacterMove> CreateClientCharacterMove(::flatbuffers::FlatBufferBuilder &_fbb, const ClientCharacterMoveT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ClientVisibleMobT : public ::flatbuffers::NativeTable {
  typedef ClientVisibleMob TableType;
  std::vector<uint32_t> mob_ids{};
};

struct ClientVisibleMob FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientVisibleMobT NativeTableType;
  typedef ClientVisibleMobBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MOB_IDS = 4
  };
  const ::flatbuffers::Vector<uint32_t> *mob_ids() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_MOB_IDS);
  }
  ::flatbuffers::Vector<uint32_t> *mutable_mob_ids() {
    return GetPointer<::flatbuffers::Vector<uint32_t> *>(VT_MOB_IDS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MOB_IDS) &&
           verifier.VerifyVector(mob_ids()) &&
           verifier.EndTable();
  }
  ClientVisibleMobT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ClientVisibleMobT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ClientVisibleMob> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientVisibleMobT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ClientVisibleMobBuilder {
  typedef ClientVisibleMob Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_mob_ids(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> mob_ids) {
    fbb_.AddOffset(ClientVisibleMob::VT_MOB_IDS, mob_ids);
  }
  explicit ClientVisibleMobBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientVisibleMob> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientVisibleMob>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientVisibleMob> CreateClientVisibleMob(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> mob_ids = 0) {
  ClientVisibleMobBuilder builder_(_fbb);
  builder_.add_mob_ids(mob_ids);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ClientVisibleMob> CreateClientVisibleMobDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint32_t> *mob_ids = nullptr) {
  auto mob_ids__ = mob_ids ? _fbb.CreateVector<uint32_t>(*mob_ids) : 0;
  return fbs::CreateClientVisibleMob(
      _fbb,
      mob_ids__);
}

::flatbuffers::Offset<ClientVisibleMob> CreateClientVisibleMob(::flatbuffers::FlatBufferBuilder &_fbb, const ClientVisibleMobT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline ClientHeartbeatT *ClientHeartbeat::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ClientHeartbeatT>(new ClientHeartbeatT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ClientHeartbeat::UnPackTo(ClientHeartbeatT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
}

inline ::flatbuffers::Offset<ClientHeartbeat> CreateClientHeartbeat(::flatbuffers::FlatBufferBuilder &_fbb, const ClientHeartbeatT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ClientHeartbeat::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ClientHeartbeat> ClientHeartbeat::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientHeartbeatT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ClientHeartbeatT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  return fbs::CreateClientHeartbeat(
      _fbb);
}

inline ClientSceneT::ClientSceneT(const ClientSceneT &o)
      : come(o.come),
        map_id(o.map_id),
        character((o.character) ? new fbs::CharacterT(*o.character) : nullptr) {
}

inline ClientSceneT &ClientSceneT::operator=(ClientSceneT o) FLATBUFFERS_NOEXCEPT {
  std::swap(come, o.come);
  std::swap(map_id, o.map_id);
  std::swap(character, o.character);
  return *this;
}

inline ClientSceneT *ClientScene::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ClientSceneT>(new ClientSceneT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ClientScene::UnPackTo(ClientSceneT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = come(); _o->come = _e; }
  { auto _e = map_id(); _o->map_id = _e; }
  { auto _e = character(); if (_e) { if(_o->character) { _e->UnPackTo(_o->character.get(), _resolver); } else { _o->character = std::unique_ptr<fbs::CharacterT>(_e->UnPack(_resolver)); } } else if (_o->character) { _o->character.reset(); } }
}

inline ::flatbuffers::Offset<ClientScene> CreateClientScene(::flatbuffers::FlatBufferBuilder &_fbb, const ClientSceneT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ClientScene::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ClientScene> ClientScene::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientSceneT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ClientSceneT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _come = _o->come;
  auto _map_id = _o->map_id;
  auto _character = _o->character ? CreateCharacter(_fbb, _o->character.get(), _rehasher) : 0;
  return fbs::CreateClientScene(
      _fbb,
      _come,
      _map_id,
      _character);
}

inline ClientCharacterMoveT::ClientCharacterMoveT(const ClientCharacterMoveT &o)
      : movement((o.movement) ? new fbs::MovementT(*o.movement) : nullptr) {
}

inline ClientCharacterMoveT &ClientCharacterMoveT::operator=(ClientCharacterMoveT o) FLATBUFFERS_NOEXCEPT {
  std::swap(movement, o.movement);
  return *this;
}

inline ClientCharacterMoveT *ClientCharacterMove::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ClientCharacterMoveT>(new ClientCharacterMoveT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ClientCharacterMove::UnPackTo(ClientCharacterMoveT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = movement(); if (_e) { if(_o->movement) { _e->UnPackTo(_o->movement.get(), _resolver); } else { _o->movement = std::unique_ptr<fbs::MovementT>(_e->UnPack(_resolver)); } } else if (_o->movement) { _o->movement.reset(); } }
}

inline ::flatbuffers::Offset<ClientCharacterMove> CreateClientCharacterMove(::flatbuffers::FlatBufferBuilder &_fbb, const ClientCharacterMoveT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ClientCharacterMove::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ClientCharacterMove> ClientCharacterMove::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientCharacterMoveT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ClientCharacterMoveT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _movement = _o->movement ? CreateMovement(_fbb, _o->movement.get(), _rehasher) : 0;
  return fbs::CreateClientCharacterMove(
      _fbb,
      _movement);
}

inline ClientVisibleMobT *ClientVisibleMob::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ClientVisibleMobT>(new ClientVisibleMobT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ClientVisibleMob::UnPackTo(ClientVisibleMobT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = mob_ids(); if (_e) { _o->mob_ids.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->mob_ids[_i] = _e->Get(_i); } } else { _o->mob_ids.resize(0); } }
}

inline ::flatbuffers::Offset<ClientVisibleMob> CreateClientVisibleMob(::flatbuffers::FlatBufferBuilder &_fbb, const ClientVisibleMobT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ClientVisibleMob::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ClientVisibleMob> ClientVisibleMob::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientVisibleMobT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ClientVisibleMobT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _mob_ids = _o->mob_ids.size() ? _fbb.CreateVector(_o->mob_ids) : 0;
  return fbs::CreateClientVisibleMob(
      _fbb,
      _mob_ids);
}

}  // namespace fbs

#endif  // FLATBUFFERS_GENERATED_CLIENT_FBS_H_
