// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CLIENT_FBS_H_
#define FLATBUFFERS_GENERATED_CLIENT_FBS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "common.h"

namespace fbs {

struct ClientHeartbeat;
struct ClientHeartbeatBuilder;
struct ClientHeartbeatT;

struct ClientScene;
struct ClientSceneBuilder;
struct ClientSceneT;

struct ClientCharacterLogic;
struct ClientCharacterLogicBuilder;
struct ClientCharacterLogicT;

struct ClientCharacterAttack;
struct ClientCharacterAttackBuilder;
struct ClientCharacterAttackT;

struct ClientCharacterSkill;
struct ClientCharacterSkillBuilder;
struct ClientCharacterSkillT;

struct ClientCharacterBall;
struct ClientCharacterBallBuilder;
struct ClientCharacterBallT;

struct ClientMobAttack;
struct ClientMobAttackBuilder;
struct ClientMobAttackT;

struct ClientCharacterChat;
struct ClientCharacterChatBuilder;
struct ClientCharacterChatT;

struct ClientCharacterStat;
struct ClientCharacterStatBuilder;
struct ClientCharacterStatT;

struct ClientHeartbeatT : public ::flatbuffers::NativeTable {
  typedef ClientHeartbeat TableType;
};

struct ClientHeartbeat FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientHeartbeatT NativeTableType;
  typedef ClientHeartbeatBuilder Builder;
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
  ClientHeartbeatT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ClientHeartbeatT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ClientHeartbeat> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientHeartbeatT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ClientHeartbeatBuilder {
  typedef ClientHeartbeat Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit ClientHeartbeatBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientHeartbeat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientHeartbeat>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientHeartbeat> CreateClientHeartbeat(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  ClientHeartbeatBuilder builder_(_fbb);
  return builder_.Finish();
}

::flatbuffers::Offset<ClientHeartbeat> CreateClientHeartbeat(::flatbuffers::FlatBufferBuilder &_fbb, const ClientHeartbeatT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ClientSceneT : public ::flatbuffers::NativeTable {
  typedef ClientScene TableType;
  bool come = false;
  uint32_t map_id = 0;
  std::unique_ptr<fbs::CharacterT> character{};
  ClientSceneT() = default;
  ClientSceneT(const ClientSceneT &o);
  ClientSceneT(ClientSceneT&&) FLATBUFFERS_NOEXCEPT = default;
  ClientSceneT &operator=(ClientSceneT o) FLATBUFFERS_NOEXCEPT;
};

struct ClientScene FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientSceneT NativeTableType;
  typedef ClientSceneBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_COME = 4,
    VT_MAP_ID = 6,
    VT_CHARACTER = 8
  };
  bool come() const {
    return GetField<uint8_t>(VT_COME, 0) != 0;
  }
  bool mutate_come(bool _come = 0) {
    return SetField<uint8_t>(VT_COME, static_cast<uint8_t>(_come), 0);
  }
  uint32_t map_id() const {
    return GetField<uint32_t>(VT_MAP_ID, 0);
  }
  bool mutate_map_id(uint32_t _map_id = 0) {
    return SetField<uint32_t>(VT_MAP_ID, _map_id, 0);
  }
  const fbs::Character *character() const {
    return GetPointer<const fbs::Character *>(VT_CHARACTER);
  }
  fbs::Character *mutable_character() {
    return GetPointer<fbs::Character *>(VT_CHARACTER);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_COME, 1) &&
           VerifyField<uint32_t>(verifier, VT_MAP_ID, 4) &&
           VerifyOffset(verifier, VT_CHARACTER) &&
           verifier.VerifyTable(character()) &&
           verifier.EndTable();
  }
  ClientSceneT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ClientSceneT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ClientScene> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientSceneT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ClientSceneBuilder {
  typedef ClientScene Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_come(bool come) {
    fbb_.AddElement<uint8_t>(ClientScene::VT_COME, static_cast<uint8_t>(come), 0);
  }
  void add_map_id(uint32_t map_id) {
    fbb_.AddElement<uint32_t>(ClientScene::VT_MAP_ID, map_id, 0);
  }
  void add_character(::flatbuffers::Offset<fbs::Character> character) {
    fbb_.AddOffset(ClientScene::VT_CHARACTER, character);
  }
  explicit ClientSceneBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientScene> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientScene>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientScene> CreateClientScene(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool come = false,
    uint32_t map_id = 0,
    ::flatbuffers::Offset<fbs::Character> character = 0) {
  ClientSceneBuilder builder_(_fbb);
  builder_.add_character(character);
  builder_.add_map_id(map_id);
  builder_.add_come(come);
  return builder_.Finish();
}

::flatbuffers::Offset<ClientScene> CreateClientScene(::flatbuffers::FlatBufferBuilder &_fbb, const ClientSceneT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ClientCharacterLogicT : public ::flatbuffers::NativeTable {
  typedef ClientCharacterLogic TableType;
  uint32_t map_id = 0;
  fbs::CharacterLogicTypeUnion payload{};
};

struct ClientCharacterLogic FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientCharacterLogicT NativeTableType;
  typedef ClientCharacterLogicBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MAP_ID = 4,
    VT_PAYLOAD_TYPE = 6,
    VT_PAYLOAD = 8
  };
  uint32_t map_id() const {
    return GetField<uint32_t>(VT_MAP_ID, 0);
  }
  bool mutate_map_id(uint32_t _map_id = 0) {
    return SetField<uint32_t>(VT_MAP_ID, _map_id, 0);
  }
  fbs::CharacterLogicType payload_type() const {
    return static_cast<fbs::CharacterLogicType>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const fbs::Movement *payload_as_Movement() const {
    return payload_type() == fbs::CharacterLogicType_Movement ? static_cast<const fbs::Movement *>(payload()) : nullptr;
  }
  const fbs::Flip *payload_as_Flip() const {
    return payload_type() == fbs::CharacterLogicType_Flip ? static_cast<const fbs::Flip *>(payload()) : nullptr;
  }
  const fbs::Action *payload_as_Action() const {
    return payload_type() == fbs::CharacterLogicType_Action ? static_cast<const fbs::Action *>(payload()) : nullptr;
  }
  const fbs::Die *payload_as_Die() const {
    return payload_type() == fbs::CharacterLogicType_Die ? static_cast<const fbs::Die *>(payload()) : nullptr;
  }
  const fbs::Face *payload_as_Face() const {
    return payload_type() == fbs::CharacterLogicType_Face ? static_cast<const fbs::Face *>(payload()) : nullptr;
  }
  template<typename T> T *mutable_payload_as();
  fbs::Movement *mutable_payload_as_Movement() {
    return payload_type() == fbs::CharacterLogicType_Movement ? static_cast<fbs::Movement *>(mutable_payload()) : nullptr;
  }
  fbs::Flip *mutable_payload_as_Flip() {
    return payload_type() == fbs::CharacterLogicType_Flip ? static_cast<fbs::Flip *>(mutable_payload()) : nullptr;
  }
  fbs::Action *mutable_payload_as_Action() {
    return payload_type() == fbs::CharacterLogicType_Action ? static_cast<fbs::Action *>(mutable_payload()) : nullptr;
  }
  fbs::Die *mutable_payload_as_Die() {
    return payload_type() == fbs::CharacterLogicType_Die ? static_cast<fbs::Die *>(mutable_payload()) : nullptr;
  }
  fbs::Face *mutable_payload_as_Face() {
    return payload_type() == fbs::CharacterLogicType_Face ? static_cast<fbs::Face *>(mutable_payload()) : nullptr;
  }
  void *mutable_payload() {
    return GetPointer<void *>(VT_PAYLOAD);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_MAP_ID, 4) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyCharacterLogicType(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
  ClientCharacterLogicT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ClientCharacterLogicT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ClientCharacterLogic> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientCharacterLogicT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

template<> inline const fbs::Movement *ClientCharacterLogic::payload_as<fbs::Movement>() const {
  return payload_as_Movement();
}

template<> inline fbs::Movement *ClientCharacterLogic::mutable_payload_as<fbs::Movement>() {
  return mutable_payload_as_Movement();
}

template<> inline const fbs::Flip *ClientCharacterLogic::payload_as<fbs::Flip>() const {
  return payload_as_Flip();
}

template<> inline fbs::Flip *ClientCharacterLogic::mutable_payload_as<fbs::Flip>() {
  return mutable_payload_as_Flip();
}

template<> inline const fbs::Action *ClientCharacterLogic::payload_as<fbs::Action>() const {
  return payload_as_Action();
}

template<> inline fbs::Action *ClientCharacterLogic::mutable_payload_as<fbs::Action>() {
  return mutable_payload_as_Action();
}

template<> inline const fbs::Die *ClientCharacterLogic::payload_as<fbs::Die>() const {
  return payload_as_Die();
}

template<> inline fbs::Die *ClientCharacterLogic::mutable_payload_as<fbs::Die>() {
  return mutable_payload_as_Die();
}

template<> inline const fbs::Face *ClientCharacterLogic::payload_as<fbs::Face>() const {
  return payload_as_Face();
}

template<> inline fbs::Face *ClientCharacterLogic::mutable_payload_as<fbs::Face>() {
  return mutable_payload_as_Face();
}

struct ClientCharacterLogicBuilder {
  typedef ClientCharacterLogic Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_map_id(uint32_t map_id) {
    fbb_.AddElement<uint32_t>(ClientCharacterLogic::VT_MAP_ID, map_id, 0);
  }
  void add_payload_type(fbs::CharacterLogicType payload_type) {
    fbb_.AddElement<uint8_t>(ClientCharacterLogic::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(ClientCharacterLogic::VT_PAYLOAD, payload);
  }
  explicit ClientCharacterLogicBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientCharacterLogic> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientCharacterLogic>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientCharacterLogic> CreateClientCharacterLogic(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t map_id = 0,
    fbs::CharacterLogicType payload_type = fbs::CharacterLogicType_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  ClientCharacterLogicBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_map_id(map_id);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

::flatbuffers::Offset<ClientCharacterLogic> CreateClientCharacterLogic(::flatbuffers::FlatBufferBuilder &_fbb, const ClientCharacterLogicT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ClientCharacterAttackT : public ::flatbuffers::NativeTable {
  typedef ClientCharacterAttack TableType;
  std::vector<std::unique_ptr<fbs::CharacterAttackT>> payload{};
  ClientCharacterAttackT() = default;
  ClientCharacterAttackT(const ClientCharacterAttackT &o);
  ClientCharacterAttackT(ClientCharacterAttackT&&) FLATBUFFERS_NOEXCEPT = default;
  ClientCharacterAttackT &operator=(ClientCharacterAttackT o) FLATBUFFERS_NOEXCEPT;
};

struct ClientCharacterAttack FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientCharacterAttackT NativeTableType;
  typedef ClientCharacterAttackBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterAttack>> *payload() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterAttack>> *>(VT_PAYLOAD);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterAttack>> *mutable_payload() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterAttack>> *>(VT_PAYLOAD);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           verifier.VerifyVector(payload()) &&
           verifier.VerifyVectorOfTables(payload()) &&
           verifier.EndTable();
  }
  ClientCharacterAttackT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ClientCharacterAttackT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ClientCharacterAttack> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientCharacterAttackT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ClientCharacterAttackBuilder {
  typedef ClientCharacterAttack Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_payload(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterAttack>>> payload) {
    fbb_.AddOffset(ClientCharacterAttack::VT_PAYLOAD, payload);
  }
  explicit ClientCharacterAttackBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientCharacterAttack> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientCharacterAttack>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientCharacterAttack> CreateClientCharacterAttack(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterAttack>>> payload = 0) {
  ClientCharacterAttackBuilder builder_(_fbb);
  builder_.add_payload(payload);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ClientCharacterAttack> CreateClientCharacterAttackDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<fbs::CharacterAttack>> *payload = nullptr) {
  auto payload__ = payload ? _fbb.CreateVector<::flatbuffers::Offset<fbs::CharacterAttack>>(*payload) : 0;
  return fbs::CreateClientCharacterAttack(
      _fbb,
      payload__);
}

::flatbuffers::Offset<ClientCharacterAttack> CreateClientCharacterAttack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientCharacterAttackT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ClientCharacterSkillT : public ::flatbuffers::NativeTable {
  typedef ClientCharacterSkill TableType;
  uint32_t ski_id = 0;
  std::vector<std::unique_ptr<fbs::CharacterSkillT>> payload{};
  ClientCharacterSkillT() = default;
  ClientCharacterSkillT(const ClientCharacterSkillT &o);
  ClientCharacterSkillT(ClientCharacterSkillT&&) FLATBUFFERS_NOEXCEPT = default;
  ClientCharacterSkillT &operator=(ClientCharacterSkillT o) FLATBUFFERS_NOEXCEPT;
};

struct ClientCharacterSkill FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientCharacterSkillT NativeTableType;
  typedef ClientCharacterSkillBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SKI_ID = 4,
    VT_PAYLOAD = 6
  };
  uint32_t ski_id() const {
    return GetField<uint32_t>(VT_SKI_ID, 0);
  }
  bool mutate_ski_id(uint32_t _ski_id = 0) {
    return SetField<uint32_t>(VT_SKI_ID, _ski_id, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterSkill>> *payload() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterSkill>> *>(VT_PAYLOAD);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterSkill>> *mutable_payload() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterSkill>> *>(VT_PAYLOAD);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_SKI_ID, 4) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           verifier.VerifyVector(payload()) &&
           verifier.VerifyVectorOfTables(payload()) &&
           verifier.EndTable();
  }
  ClientCharacterSkillT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ClientCharacterSkillT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ClientCharacterSkill> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientCharacterSkillT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ClientCharacterSkillBuilder {
  typedef ClientCharacterSkill Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_ski_id(uint32_t ski_id) {
    fbb_.AddElement<uint32_t>(ClientCharacterSkill::VT_SKI_ID, ski_id, 0);
  }
  void add_payload(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterSkill>>> payload) {
    fbb_.AddOffset(ClientCharacterSkill::VT_PAYLOAD, payload);
  }
  explicit ClientCharacterSkillBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientCharacterSkill> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientCharacterSkill>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientCharacterSkill> CreateClientCharacterSkill(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t ski_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterSkill>>> payload = 0) {
  ClientCharacterSkillBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_ski_id(ski_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ClientCharacterSkill> CreateClientCharacterSkillDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t ski_id = 0,
    const std::vector<::flatbuffers::Offset<fbs::CharacterSkill>> *payload = nullptr) {
  auto payload__ = payload ? _fbb.CreateVector<::flatbuffers::Offset<fbs::CharacterSkill>>(*payload) : 0;
  return fbs::CreateClientCharacterSkill(
      _fbb,
      ski_id,
      payload__);
}

::flatbuffers::Offset<ClientCharacterSkill> CreateClientCharacterSkill(::flatbuffers::FlatBufferBuilder &_fbb, const ClientCharacterSkillT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ClientCharacterBallT : public ::flatbuffers::NativeTable {
  typedef ClientCharacterBall TableType;
  std::vector<std::unique_ptr<fbs::CharacterBallT>> payload{};
  ClientCharacterBallT() = default;
  ClientCharacterBallT(const ClientCharacterBallT &o);
  ClientCharacterBallT(ClientCharacterBallT&&) FLATBUFFERS_NOEXCEPT = default;
  ClientCharacterBallT &operator=(ClientCharacterBallT o) FLATBUFFERS_NOEXCEPT;
};

struct ClientCharacterBall FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientCharacterBallT NativeTableType;
  typedef ClientCharacterBallBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterBall>> *payload() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterBall>> *>(VT_PAYLOAD);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterBall>> *mutable_payload() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterBall>> *>(VT_PAYLOAD);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           verifier.VerifyVector(payload()) &&
           verifier.VerifyVectorOfTables(payload()) &&
           verifier.EndTable();
  }
  ClientCharacterBallT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ClientCharacterBallT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ClientCharacterBall> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientCharacterBallT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ClientCharacterBallBuilder {
  typedef ClientCharacterBall Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_payload(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterBall>>> payload) {
    fbb_.AddOffset(ClientCharacterBall::VT_PAYLOAD, payload);
  }
  explicit ClientCharacterBallBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientCharacterBall> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientCharacterBall>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientCharacterBall> CreateClientCharacterBall(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterBall>>> payload = 0) {
  ClientCharacterBallBuilder builder_(_fbb);
  builder_.add_payload(payload);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ClientCharacterBall> CreateClientCharacterBallDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<fbs::CharacterBall>> *payload = nullptr) {
  auto payload__ = payload ? _fbb.CreateVector<::flatbuffers::Offset<fbs::CharacterBall>>(*payload) : 0;
  return fbs::CreateClientCharacterBall(
      _fbb,
      payload__);
}

::flatbuffers::Offset<ClientCharacterBall> CreateClientCharacterBall(::flatbuffers::FlatBufferBuilder &_fbb, const ClientCharacterBallT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ClientMobAttackT : public ::flatbuffers::NativeTable {
  typedef ClientMobAttack TableType;
  uint32_t map_id = 0;
  std::unique_ptr<fbs::MobAttackT> payload{};
  ClientMobAttackT() = default;
  ClientMobAttackT(const ClientMobAttackT &o);
  ClientMobAttackT(ClientMobAttackT&&) FLATBUFFERS_NOEXCEPT = default;
  ClientMobAttackT &operator=(ClientMobAttackT o) FLATBUFFERS_NOEXCEPT;
};

struct ClientMobAttack FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientMobAttackT NativeTableType;
  typedef ClientMobAttackBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MAP_ID = 4,
    VT_PAYLOAD = 6
  };
  uint32_t map_id() const {
    return GetField<uint32_t>(VT_MAP_ID, 0);
  }
  bool mutate_map_id(uint32_t _map_id = 0) {
    return SetField<uint32_t>(VT_MAP_ID, _map_id, 0);
  }
  const fbs::MobAttack *payload() const {
    return GetPointer<const fbs::MobAttack *>(VT_PAYLOAD);
  }
  fbs::MobAttack *mutable_payload() {
    return GetPointer<fbs::MobAttack *>(VT_PAYLOAD);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_MAP_ID, 4) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           verifier.VerifyTable(payload()) &&
           verifier.EndTable();
  }
  ClientMobAttackT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ClientMobAttackT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ClientMobAttack> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientMobAttackT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ClientMobAttackBuilder {
  typedef ClientMobAttack Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_map_id(uint32_t map_id) {
    fbb_.AddElement<uint32_t>(ClientMobAttack::VT_MAP_ID, map_id, 0);
  }
  void add_payload(::flatbuffers::Offset<fbs::MobAttack> payload) {
    fbb_.AddOffset(ClientMobAttack::VT_PAYLOAD, payload);
  }
  explicit ClientMobAttackBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientMobAttack> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientMobAttack>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientMobAttack> CreateClientMobAttack(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t map_id = 0,
    ::flatbuffers::Offset<fbs::MobAttack> payload = 0) {
  ClientMobAttackBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_map_id(map_id);
  return builder_.Finish();
}

::flatbuffers::Offset<ClientMobAttack> CreateClientMobAttack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientMobAttackT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ClientCharacterChatT : public ::flatbuffers::NativeTable {
  typedef ClientCharacterChat TableType;
  uint32_t map_id = 0;
  std::unique_ptr<fbs::CharacterChatT> payload{};
  ClientCharacterChatT() = default;
  ClientCharacterChatT(const ClientCharacterChatT &o);
  ClientCharacterChatT(ClientCharacterChatT&&) FLATBUFFERS_NOEXCEPT = default;
  ClientCharacterChatT &operator=(ClientCharacterChatT o) FLATBUFFERS_NOEXCEPT;
};

struct ClientCharacterChat FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientCharacterChatT NativeTableType;
  typedef ClientCharacterChatBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MAP_ID = 4,
    VT_PAYLOAD = 6
  };
  uint32_t map_id() const {
    return GetField<uint32_t>(VT_MAP_ID, 0);
  }
  bool mutate_map_id(uint32_t _map_id = 0) {
    return SetField<uint32_t>(VT_MAP_ID, _map_id, 0);
  }
  const fbs::CharacterChat *payload() const {
    return GetPointer<const fbs::CharacterChat *>(VT_PAYLOAD);
  }
  fbs::CharacterChat *mutable_payload() {
    return GetPointer<fbs::CharacterChat *>(VT_PAYLOAD);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_MAP_ID, 4) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           verifier.VerifyTable(payload()) &&
           verifier.EndTable();
  }
  ClientCharacterChatT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ClientCharacterChatT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ClientCharacterChat> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientCharacterChatT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ClientCharacterChatBuilder {
  typedef ClientCharacterChat Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_map_id(uint32_t map_id) {
    fbb_.AddElement<uint32_t>(ClientCharacterChat::VT_MAP_ID, map_id, 0);
  }
  void add_payload(::flatbuffers::Offset<fbs::CharacterChat> payload) {
    fbb_.AddOffset(ClientCharacterChat::VT_PAYLOAD, payload);
  }
  explicit ClientCharacterChatBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientCharacterChat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientCharacterChat>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientCharacterChat> CreateClientCharacterChat(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t map_id = 0,
    ::flatbuffers::Offset<fbs::CharacterChat> payload = 0) {
  ClientCharacterChatBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_map_id(map_id);
  return builder_.Finish();
}

::flatbuffers::Offset<ClientCharacterChat> CreateClientCharacterChat(::flatbuffers::FlatBufferBuilder &_fbb, const ClientCharacterChatT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ClientCharacterStatT : public ::flatbuffers::NativeTable {
  typedef ClientCharacterStat TableType;
  std::unique_ptr<fbs::CharacterStatT> payload{};
  ClientCharacterStatT() = default;
  ClientCharacterStatT(const ClientCharacterStatT &o);
  ClientCharacterStatT(ClientCharacterStatT&&) FLATBUFFERS_NOEXCEPT = default;
  ClientCharacterStatT &operator=(ClientCharacterStatT o) FLATBUFFERS_NOEXCEPT;
};

struct ClientCharacterStat FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientCharacterStatT NativeTableType;
  typedef ClientCharacterStatBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD = 4
  };
  const fbs::CharacterStat *payload() const {
    return GetPointer<const fbs::CharacterStat *>(VT_PAYLOAD);
  }
  fbs::CharacterStat *mutable_payload() {
    return GetPointer<fbs::CharacterStat *>(VT_PAYLOAD);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           verifier.VerifyTable(payload()) &&
           verifier.EndTable();
  }
  ClientCharacterStatT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ClientCharacterStatT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ClientCharacterStat> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientCharacterStatT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ClientCharacterStatBuilder {
  typedef ClientCharacterStat Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_payload(::flatbuffers::Offset<fbs::CharacterStat> payload) {
    fbb_.AddOffset(ClientCharacterStat::VT_PAYLOAD, payload);
  }
  explicit ClientCharacterStatBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientCharacterStat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientCharacterStat>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientCharacterStat> CreateClientCharacterStat(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<fbs::CharacterStat> payload = 0) {
  ClientCharacterStatBuilder builder_(_fbb);
  builder_.add_payload(payload);
  return builder_.Finish();
}

::flatbuffers::Offset<ClientCharacterStat> CreateClientCharacterStat(::flatbuffers::FlatBufferBuilder &_fbb, const ClientCharacterStatT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline ClientHeartbeatT *ClientHeartbeat::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ClientHeartbeatT>(new ClientHeartbeatT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ClientHeartbeat::UnPackTo(ClientHeartbeatT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
}

inline ::flatbuffers::Offset<ClientHeartbeat> CreateClientHeartbeat(::flatbuffers::FlatBufferBuilder &_fbb, const ClientHeartbeatT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ClientHeartbeat::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ClientHeartbeat> ClientHeartbeat::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientHeartbeatT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ClientHeartbeatT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  return fbs::CreateClientHeartbeat(
      _fbb);
}

inline ClientSceneT::ClientSceneT(const ClientSceneT &o)
      : come(o.come),
        map_id(o.map_id),
        character((o.character) ? new fbs::CharacterT(*o.character) : nullptr) {
}

inline ClientSceneT &ClientSceneT::operator=(ClientSceneT o) FLATBUFFERS_NOEXCEPT {
  std::swap(come, o.come);
  std::swap(map_id, o.map_id);
  std::swap(character, o.character);
  return *this;
}

inline ClientSceneT *ClientScene::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ClientSceneT>(new ClientSceneT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ClientScene::UnPackTo(ClientSceneT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = come(); _o->come = _e; }
  { auto _e = map_id(); _o->map_id = _e; }
  { auto _e = character(); if (_e) { if(_o->character) { _e->UnPackTo(_o->character.get(), _resolver); } else { _o->character = std::unique_ptr<fbs::CharacterT>(_e->UnPack(_resolver)); } } else if (_o->character) { _o->character.reset(); } }
}

inline ::flatbuffers::Offset<ClientScene> CreateClientScene(::flatbuffers::FlatBufferBuilder &_fbb, const ClientSceneT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ClientScene::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ClientScene> ClientScene::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientSceneT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ClientSceneT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _come = _o->come;
  auto _map_id = _o->map_id;
  auto _character = _o->character ? CreateCharacter(_fbb, _o->character.get(), _rehasher) : 0;
  return fbs::CreateClientScene(
      _fbb,
      _come,
      _map_id,
      _character);
}

inline ClientCharacterLogicT *ClientCharacterLogic::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ClientCharacterLogicT>(new ClientCharacterLogicT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ClientCharacterLogic::UnPackTo(ClientCharacterLogicT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = map_id(); _o->map_id = _e; }
  { auto _e = payload_type(); _o->payload.type = _e; }
  { auto _e = payload(); if (_e) _o->payload.value = fbs::CharacterLogicTypeUnion::UnPack(_e, payload_type(), _resolver); }
}

inline ::flatbuffers::Offset<ClientCharacterLogic> CreateClientCharacterLogic(::flatbuffers::FlatBufferBuilder &_fbb, const ClientCharacterLogicT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ClientCharacterLogic::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ClientCharacterLogic> ClientCharacterLogic::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientCharacterLogicT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ClientCharacterLogicT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _map_id = _o->map_id;
  auto _payload_type = _o->payload.type;
  auto _payload = _o->payload.Pack(_fbb);
  return fbs::CreateClientCharacterLogic(
      _fbb,
      _map_id,
      _payload_type,
      _payload);
}

inline ClientCharacterAttackT::ClientCharacterAttackT(const ClientCharacterAttackT &o) {
  payload.reserve(o.payload.size());
  for (const auto &payload_ : o.payload) { payload.emplace_back((payload_) ? new fbs::CharacterAttackT(*payload_) : nullptr); }
}

inline ClientCharacterAttackT &ClientCharacterAttackT::operator=(ClientCharacterAttackT o) FLATBUFFERS_NOEXCEPT {
  std::swap(payload, o.payload);
  return *this;
}

inline ClientCharacterAttackT *ClientCharacterAttack::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ClientCharacterAttackT>(new ClientCharacterAttackT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ClientCharacterAttack::UnPackTo(ClientCharacterAttackT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = payload(); if (_e) { _o->payload.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->payload[_i]) { _e->Get(_i)->UnPackTo(_o->payload[_i].get(), _resolver); } else { _o->payload[_i] = std::unique_ptr<fbs::CharacterAttackT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->payload.resize(0); } }
}

inline ::flatbuffers::Offset<ClientCharacterAttack> CreateClientCharacterAttack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientCharacterAttackT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ClientCharacterAttack::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ClientCharacterAttack> ClientCharacterAttack::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientCharacterAttackT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ClientCharacterAttackT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _payload = _o->payload.size() ? _fbb.CreateVector<::flatbuffers::Offset<fbs::CharacterAttack>> (_o->payload.size(), [](size_t i, _VectorArgs *__va) { return CreateCharacterAttack(*__va->__fbb, __va->__o->payload[i].get(), __va->__rehasher); }, &_va ) : 0;
  return fbs::CreateClientCharacterAttack(
      _fbb,
      _payload);
}

inline ClientCharacterSkillT::ClientCharacterSkillT(const ClientCharacterSkillT &o)
      : ski_id(o.ski_id) {
  payload.reserve(o.payload.size());
  for (const auto &payload_ : o.payload) { payload.emplace_back((payload_) ? new fbs::CharacterSkillT(*payload_) : nullptr); }
}

inline ClientCharacterSkillT &ClientCharacterSkillT::operator=(ClientCharacterSkillT o) FLATBUFFERS_NOEXCEPT {
  std::swap(ski_id, o.ski_id);
  std::swap(payload, o.payload);
  return *this;
}

inline ClientCharacterSkillT *ClientCharacterSkill::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ClientCharacterSkillT>(new ClientCharacterSkillT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ClientCharacterSkill::UnPackTo(ClientCharacterSkillT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = ski_id(); _o->ski_id = _e; }
  { auto _e = payload(); if (_e) { _o->payload.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->payload[_i]) { _e->Get(_i)->UnPackTo(_o->payload[_i].get(), _resolver); } else { _o->payload[_i] = std::unique_ptr<fbs::CharacterSkillT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->payload.resize(0); } }
}

inline ::flatbuffers::Offset<ClientCharacterSkill> CreateClientCharacterSkill(::flatbuffers::FlatBufferBuilder &_fbb, const ClientCharacterSkillT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ClientCharacterSkill::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ClientCharacterSkill> ClientCharacterSkill::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientCharacterSkillT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ClientCharacterSkillT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _ski_id = _o->ski_id;
  auto _payload = _o->payload.size() ? _fbb.CreateVector<::flatbuffers::Offset<fbs::CharacterSkill>> (_o->payload.size(), [](size_t i, _VectorArgs *__va) { return CreateCharacterSkill(*__va->__fbb, __va->__o->payload[i].get(), __va->__rehasher); }, &_va ) : 0;
  return fbs::CreateClientCharacterSkill(
      _fbb,
      _ski_id,
      _payload);
}

inline ClientCharacterBallT::ClientCharacterBallT(const ClientCharacterBallT &o) {
  payload.reserve(o.payload.size());
  for (const auto &payload_ : o.payload) { payload.emplace_back((payload_) ? new fbs::CharacterBallT(*payload_) : nullptr); }
}

inline ClientCharacterBallT &ClientCharacterBallT::operator=(ClientCharacterBallT o) FLATBUFFERS_NOEXCEPT {
  std::swap(payload, o.payload);
  return *this;
}

inline ClientCharacterBallT *ClientCharacterBall::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ClientCharacterBallT>(new ClientCharacterBallT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ClientCharacterBall::UnPackTo(ClientCharacterBallT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = payload(); if (_e) { _o->payload.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->payload[_i]) { _e->Get(_i)->UnPackTo(_o->payload[_i].get(), _resolver); } else { _o->payload[_i] = std::unique_ptr<fbs::CharacterBallT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->payload.resize(0); } }
}

inline ::flatbuffers::Offset<ClientCharacterBall> CreateClientCharacterBall(::flatbuffers::FlatBufferBuilder &_fbb, const ClientCharacterBallT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ClientCharacterBall::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ClientCharacterBall> ClientCharacterBall::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientCharacterBallT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ClientCharacterBallT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _payload = _o->payload.size() ? _fbb.CreateVector<::flatbuffers::Offset<fbs::CharacterBall>> (_o->payload.size(), [](size_t i, _VectorArgs *__va) { return CreateCharacterBall(*__va->__fbb, __va->__o->payload[i].get(), __va->__rehasher); }, &_va ) : 0;
  return fbs::CreateClientCharacterBall(
      _fbb,
      _payload);
}

inline ClientMobAttackT::ClientMobAttackT(const ClientMobAttackT &o)
      : map_id(o.map_id),
        payload((o.payload) ? new fbs::MobAttackT(*o.payload) : nullptr) {
}

inline ClientMobAttackT &ClientMobAttackT::operator=(ClientMobAttackT o) FLATBUFFERS_NOEXCEPT {
  std::swap(map_id, o.map_id);
  std::swap(payload, o.payload);
  return *this;
}

inline ClientMobAttackT *ClientMobAttack::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ClientMobAttackT>(new ClientMobAttackT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ClientMobAttack::UnPackTo(ClientMobAttackT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = map_id(); _o->map_id = _e; }
  { auto _e = payload(); if (_e) { if(_o->payload) { _e->UnPackTo(_o->payload.get(), _resolver); } else { _o->payload = std::unique_ptr<fbs::MobAttackT>(_e->UnPack(_resolver)); } } else if (_o->payload) { _o->payload.reset(); } }
}

inline ::flatbuffers::Offset<ClientMobAttack> CreateClientMobAttack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientMobAttackT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ClientMobAttack::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ClientMobAttack> ClientMobAttack::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientMobAttackT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ClientMobAttackT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _map_id = _o->map_id;
  auto _payload = _o->payload ? CreateMobAttack(_fbb, _o->payload.get(), _rehasher) : 0;
  return fbs::CreateClientMobAttack(
      _fbb,
      _map_id,
      _payload);
}

inline ClientCharacterChatT::ClientCharacterChatT(const ClientCharacterChatT &o)
      : map_id(o.map_id),
        payload((o.payload) ? new fbs::CharacterChatT(*o.payload) : nullptr) {
}

inline ClientCharacterChatT &ClientCharacterChatT::operator=(ClientCharacterChatT o) FLATBUFFERS_NOEXCEPT {
  std::swap(map_id, o.map_id);
  std::swap(payload, o.payload);
  return *this;
}

inline ClientCharacterChatT *ClientCharacterChat::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ClientCharacterChatT>(new ClientCharacterChatT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ClientCharacterChat::UnPackTo(ClientCharacterChatT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = map_id(); _o->map_id = _e; }
  { auto _e = payload(); if (_e) { if(_o->payload) { _e->UnPackTo(_o->payload.get(), _resolver); } else { _o->payload = std::unique_ptr<fbs::CharacterChatT>(_e->UnPack(_resolver)); } } else if (_o->payload) { _o->payload.reset(); } }
}

inline ::flatbuffers::Offset<ClientCharacterChat> CreateClientCharacterChat(::flatbuffers::FlatBufferBuilder &_fbb, const ClientCharacterChatT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ClientCharacterChat::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ClientCharacterChat> ClientCharacterChat::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientCharacterChatT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ClientCharacterChatT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _map_id = _o->map_id;
  auto _payload = _o->payload ? CreateCharacterChat(_fbb, _o->payload.get(), _rehasher) : 0;
  return fbs::CreateClientCharacterChat(
      _fbb,
      _map_id,
      _payload);
}

inline ClientCharacterStatT::ClientCharacterStatT(const ClientCharacterStatT &o)
      : payload((o.payload) ? new fbs::CharacterStatT(*o.payload) : nullptr) {
}

inline ClientCharacterStatT &ClientCharacterStatT::operator=(ClientCharacterStatT o) FLATBUFFERS_NOEXCEPT {
  std::swap(payload, o.payload);
  return *this;
}

inline ClientCharacterStatT *ClientCharacterStat::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ClientCharacterStatT>(new ClientCharacterStatT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ClientCharacterStat::UnPackTo(ClientCharacterStatT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = payload(); if (_e) { if(_o->payload) { _e->UnPackTo(_o->payload.get(), _resolver); } else { _o->payload = std::unique_ptr<fbs::CharacterStatT>(_e->UnPack(_resolver)); } } else if (_o->payload) { _o->payload.reset(); } }
}

inline ::flatbuffers::Offset<ClientCharacterStat> CreateClientCharacterStat(::flatbuffers::FlatBufferBuilder &_fbb, const ClientCharacterStatT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ClientCharacterStat::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ClientCharacterStat> ClientCharacterStat::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientCharacterStatT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ClientCharacterStatT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _payload = _o->payload ? CreateCharacterStat(_fbb, _o->payload.get(), _rehasher) : 0;
  return fbs::CreateClientCharacterStat(
      _fbb,
      _payload);
}

}  // namespace fbs

#endif  // FLATBUFFERS_GENERATED_CLIENT_FBS_H_
