// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMMON_FBS_H_
#define FLATBUFFERS_GENERATED_COMMON_FBS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace fbs {

struct CharacterAppearance;
struct CharacterAppearanceBuilder;
struct CharacterAppearanceT;

struct Character;
struct CharacterBuilder;
struct CharacterT;

struct Player;
struct PlayerBuilder;
struct PlayerT;

struct Movement;
struct MovementBuilder;
struct MovementT;

struct CharacterAppearanceT : public ::flatbuffers::NativeTable {
  typedef CharacterAppearance TableType;
  uint32_t body = 0;
  uint32_t head = 0;
  uint32_t weapon = 0;
  uint32_t cap = 0;
  uint32_t cape = 0;
  uint32_t coat = 0;
  uint32_t glove = 0;
  uint32_t pant = 0;
  uint32_t shield = 0;
  uint32_t longcoat = 0;
  uint32_t shoes = 0;
  uint32_t accessory = 0;
};

struct CharacterAppearance FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CharacterAppearanceT NativeTableType;
  typedef CharacterAppearanceBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BODY = 4,
    VT_HEAD = 6,
    VT_WEAPON = 8,
    VT_CAP = 10,
    VT_CAPE = 12,
    VT_COAT = 14,
    VT_GLOVE = 16,
    VT_PANT = 18,
    VT_SHIELD = 20,
    VT_LONGCOAT = 22,
    VT_SHOES = 24,
    VT_ACCESSORY = 26
  };
  uint32_t body() const {
    return GetField<uint32_t>(VT_BODY, 0);
  }
  bool mutate_body(uint32_t _body = 0) {
    return SetField<uint32_t>(VT_BODY, _body, 0);
  }
  uint32_t head() const {
    return GetField<uint32_t>(VT_HEAD, 0);
  }
  bool mutate_head(uint32_t _head = 0) {
    return SetField<uint32_t>(VT_HEAD, _head, 0);
  }
  uint32_t weapon() const {
    return GetField<uint32_t>(VT_WEAPON, 0);
  }
  bool mutate_weapon(uint32_t _weapon = 0) {
    return SetField<uint32_t>(VT_WEAPON, _weapon, 0);
  }
  uint32_t cap() const {
    return GetField<uint32_t>(VT_CAP, 0);
  }
  bool mutate_cap(uint32_t _cap = 0) {
    return SetField<uint32_t>(VT_CAP, _cap, 0);
  }
  uint32_t cape() const {
    return GetField<uint32_t>(VT_CAPE, 0);
  }
  bool mutate_cape(uint32_t _cape = 0) {
    return SetField<uint32_t>(VT_CAPE, _cape, 0);
  }
  uint32_t coat() const {
    return GetField<uint32_t>(VT_COAT, 0);
  }
  bool mutate_coat(uint32_t _coat = 0) {
    return SetField<uint32_t>(VT_COAT, _coat, 0);
  }
  uint32_t glove() const {
    return GetField<uint32_t>(VT_GLOVE, 0);
  }
  bool mutate_glove(uint32_t _glove = 0) {
    return SetField<uint32_t>(VT_GLOVE, _glove, 0);
  }
  uint32_t pant() const {
    return GetField<uint32_t>(VT_PANT, 0);
  }
  bool mutate_pant(uint32_t _pant = 0) {
    return SetField<uint32_t>(VT_PANT, _pant, 0);
  }
  uint32_t shield() const {
    return GetField<uint32_t>(VT_SHIELD, 0);
  }
  bool mutate_shield(uint32_t _shield = 0) {
    return SetField<uint32_t>(VT_SHIELD, _shield, 0);
  }
  uint32_t longcoat() const {
    return GetField<uint32_t>(VT_LONGCOAT, 0);
  }
  bool mutate_longcoat(uint32_t _longcoat = 0) {
    return SetField<uint32_t>(VT_LONGCOAT, _longcoat, 0);
  }
  uint32_t shoes() const {
    return GetField<uint32_t>(VT_SHOES, 0);
  }
  bool mutate_shoes(uint32_t _shoes = 0) {
    return SetField<uint32_t>(VT_SHOES, _shoes, 0);
  }
  uint32_t accessory() const {
    return GetField<uint32_t>(VT_ACCESSORY, 0);
  }
  bool mutate_accessory(uint32_t _accessory = 0) {
    return SetField<uint32_t>(VT_ACCESSORY, _accessory, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_BODY, 4) &&
           VerifyField<uint32_t>(verifier, VT_HEAD, 4) &&
           VerifyField<uint32_t>(verifier, VT_WEAPON, 4) &&
           VerifyField<uint32_t>(verifier, VT_CAP, 4) &&
           VerifyField<uint32_t>(verifier, VT_CAPE, 4) &&
           VerifyField<uint32_t>(verifier, VT_COAT, 4) &&
           VerifyField<uint32_t>(verifier, VT_GLOVE, 4) &&
           VerifyField<uint32_t>(verifier, VT_PANT, 4) &&
           VerifyField<uint32_t>(verifier, VT_SHIELD, 4) &&
           VerifyField<uint32_t>(verifier, VT_LONGCOAT, 4) &&
           VerifyField<uint32_t>(verifier, VT_SHOES, 4) &&
           VerifyField<uint32_t>(verifier, VT_ACCESSORY, 4) &&
           verifier.EndTable();
  }
  CharacterAppearanceT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CharacterAppearanceT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CharacterAppearance> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterAppearanceT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CharacterAppearanceBuilder {
  typedef CharacterAppearance Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_body(uint32_t body) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_BODY, body, 0);
  }
  void add_head(uint32_t head) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_HEAD, head, 0);
  }
  void add_weapon(uint32_t weapon) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_WEAPON, weapon, 0);
  }
  void add_cap(uint32_t cap) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_CAP, cap, 0);
  }
  void add_cape(uint32_t cape) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_CAPE, cape, 0);
  }
  void add_coat(uint32_t coat) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_COAT, coat, 0);
  }
  void add_glove(uint32_t glove) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_GLOVE, glove, 0);
  }
  void add_pant(uint32_t pant) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_PANT, pant, 0);
  }
  void add_shield(uint32_t shield) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_SHIELD, shield, 0);
  }
  void add_longcoat(uint32_t longcoat) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_LONGCOAT, longcoat, 0);
  }
  void add_shoes(uint32_t shoes) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_SHOES, shoes, 0);
  }
  void add_accessory(uint32_t accessory) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_ACCESSORY, accessory, 0);
  }
  explicit CharacterAppearanceBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CharacterAppearance> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CharacterAppearance>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CharacterAppearance> CreateCharacterAppearance(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t body = 0,
    uint32_t head = 0,
    uint32_t weapon = 0,
    uint32_t cap = 0,
    uint32_t cape = 0,
    uint32_t coat = 0,
    uint32_t glove = 0,
    uint32_t pant = 0,
    uint32_t shield = 0,
    uint32_t longcoat = 0,
    uint32_t shoes = 0,
    uint32_t accessory = 0) {
  CharacterAppearanceBuilder builder_(_fbb);
  builder_.add_accessory(accessory);
  builder_.add_shoes(shoes);
  builder_.add_longcoat(longcoat);
  builder_.add_shield(shield);
  builder_.add_pant(pant);
  builder_.add_glove(glove);
  builder_.add_coat(coat);
  builder_.add_cape(cape);
  builder_.add_cap(cap);
  builder_.add_weapon(weapon);
  builder_.add_head(head);
  builder_.add_body(body);
  return builder_.Finish();
}

::flatbuffers::Offset<CharacterAppearance> CreateCharacterAppearance(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterAppearanceT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CharacterT : public ::flatbuffers::NativeTable {
  typedef Character TableType;
  std::string name{};
  float x = 0.0f;
  float y = 0.0f;
  std::string action{};
  uint8_t action_index = 0;
  std::unique_ptr<fbs::CharacterAppearanceT> appearance{};
  CharacterT() = default;
  CharacterT(const CharacterT &o);
  CharacterT(CharacterT&&) FLATBUFFERS_NOEXCEPT = default;
  CharacterT &operator=(CharacterT o) FLATBUFFERS_NOEXCEPT;
};

struct Character FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CharacterT NativeTableType;
  typedef CharacterBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_X = 6,
    VT_Y = 8,
    VT_ACTION = 10,
    VT_ACTION_INDEX = 12,
    VT_APPEARANCE = 14
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  ::flatbuffers::String *mutable_name() {
    return GetPointer<::flatbuffers::String *>(VT_NAME);
  }
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  bool mutate_x(float _x = 0.0f) {
    return SetField<float>(VT_X, _x, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  bool mutate_y(float _y = 0.0f) {
    return SetField<float>(VT_Y, _y, 0.0f);
  }
  const ::flatbuffers::String *action() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ACTION);
  }
  ::flatbuffers::String *mutable_action() {
    return GetPointer<::flatbuffers::String *>(VT_ACTION);
  }
  uint8_t action_index() const {
    return GetField<uint8_t>(VT_ACTION_INDEX, 0);
  }
  bool mutate_action_index(uint8_t _action_index = 0) {
    return SetField<uint8_t>(VT_ACTION_INDEX, _action_index, 0);
  }
  const fbs::CharacterAppearance *appearance() const {
    return GetPointer<const fbs::CharacterAppearance *>(VT_APPEARANCE);
  }
  fbs::CharacterAppearance *mutable_appearance() {
    return GetPointer<fbs::CharacterAppearance *>(VT_APPEARANCE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyOffset(verifier, VT_ACTION) &&
           verifier.VerifyString(action()) &&
           VerifyField<uint8_t>(verifier, VT_ACTION_INDEX, 1) &&
           VerifyOffset(verifier, VT_APPEARANCE) &&
           verifier.VerifyTable(appearance()) &&
           verifier.EndTable();
  }
  CharacterT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CharacterT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Character> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CharacterBuilder {
  typedef Character Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Character::VT_NAME, name);
  }
  void add_x(float x) {
    fbb_.AddElement<float>(Character::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(Character::VT_Y, y, 0.0f);
  }
  void add_action(::flatbuffers::Offset<::flatbuffers::String> action) {
    fbb_.AddOffset(Character::VT_ACTION, action);
  }
  void add_action_index(uint8_t action_index) {
    fbb_.AddElement<uint8_t>(Character::VT_ACTION_INDEX, action_index, 0);
  }
  void add_appearance(::flatbuffers::Offset<fbs::CharacterAppearance> appearance) {
    fbb_.AddOffset(Character::VT_APPEARANCE, appearance);
  }
  explicit CharacterBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Character> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Character>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Character> CreateCharacter(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    float x = 0.0f,
    float y = 0.0f,
    ::flatbuffers::Offset<::flatbuffers::String> action = 0,
    uint8_t action_index = 0,
    ::flatbuffers::Offset<fbs::CharacterAppearance> appearance = 0) {
  CharacterBuilder builder_(_fbb);
  builder_.add_appearance(appearance);
  builder_.add_action(action);
  builder_.add_y(y);
  builder_.add_x(x);
  builder_.add_name(name);
  builder_.add_action_index(action_index);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Character> CreateCharacterDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    float x = 0.0f,
    float y = 0.0f,
    const char *action = nullptr,
    uint8_t action_index = 0,
    ::flatbuffers::Offset<fbs::CharacterAppearance> appearance = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto action__ = action ? _fbb.CreateString(action) : 0;
  return fbs::CreateCharacter(
      _fbb,
      name__,
      x,
      y,
      action__,
      action_index,
      appearance);
}

::flatbuffers::Offset<Character> CreateCharacter(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct PlayerT : public ::flatbuffers::NativeTable {
  typedef Player TableType;
  uint64_t client_id = 0;
  std::unique_ptr<fbs::CharacterT> character{};
  PlayerT() = default;
  PlayerT(const PlayerT &o);
  PlayerT(PlayerT&&) FLATBUFFERS_NOEXCEPT = default;
  PlayerT &operator=(PlayerT o) FLATBUFFERS_NOEXCEPT;
};

struct Player FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PlayerT NativeTableType;
  typedef PlayerBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLIENT_ID = 4,
    VT_CHARACTER = 6
  };
  uint64_t client_id() const {
    return GetField<uint64_t>(VT_CLIENT_ID, 0);
  }
  bool mutate_client_id(uint64_t _client_id = 0) {
    return SetField<uint64_t>(VT_CLIENT_ID, _client_id, 0);
  }
  const fbs::Character *character() const {
    return GetPointer<const fbs::Character *>(VT_CHARACTER);
  }
  fbs::Character *mutable_character() {
    return GetPointer<fbs::Character *>(VT_CHARACTER);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CLIENT_ID, 8) &&
           VerifyOffset(verifier, VT_CHARACTER) &&
           verifier.VerifyTable(character()) &&
           verifier.EndTable();
  }
  PlayerT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(PlayerT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Player> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PlayerT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct PlayerBuilder {
  typedef Player Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_client_id(uint64_t client_id) {
    fbb_.AddElement<uint64_t>(Player::VT_CLIENT_ID, client_id, 0);
  }
  void add_character(::flatbuffers::Offset<fbs::Character> character) {
    fbb_.AddOffset(Player::VT_CHARACTER, character);
  }
  explicit PlayerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Player> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Player>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Player> CreatePlayer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t client_id = 0,
    ::flatbuffers::Offset<fbs::Character> character = 0) {
  PlayerBuilder builder_(_fbb);
  builder_.add_client_id(client_id);
  builder_.add_character(character);
  return builder_.Finish();
}

::flatbuffers::Offset<Player> CreatePlayer(::flatbuffers::FlatBufferBuilder &_fbb, const PlayerT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct MovementT : public ::flatbuffers::NativeTable {
  typedef Movement TableType;
  float x1 = 0.0f;
  float y1 = 0.0f;
  float x2 = 0.0f;
  float y2 = 0.0f;
  uint32_t time = 0;
  uint8_t page = 0;
};

struct Movement FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MovementT NativeTableType;
  typedef MovementBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X1 = 4,
    VT_Y1 = 6,
    VT_X2 = 8,
    VT_Y2 = 10,
    VT_TIME = 12,
    VT_PAGE = 14
  };
  float x1() const {
    return GetField<float>(VT_X1, 0.0f);
  }
  bool mutate_x1(float _x1 = 0.0f) {
    return SetField<float>(VT_X1, _x1, 0.0f);
  }
  float y1() const {
    return GetField<float>(VT_Y1, 0.0f);
  }
  bool mutate_y1(float _y1 = 0.0f) {
    return SetField<float>(VT_Y1, _y1, 0.0f);
  }
  float x2() const {
    return GetField<float>(VT_X2, 0.0f);
  }
  bool mutate_x2(float _x2 = 0.0f) {
    return SetField<float>(VT_X2, _x2, 0.0f);
  }
  float y2() const {
    return GetField<float>(VT_Y2, 0.0f);
  }
  bool mutate_y2(float _y2 = 0.0f) {
    return SetField<float>(VT_Y2, _y2, 0.0f);
  }
  uint32_t time() const {
    return GetField<uint32_t>(VT_TIME, 0);
  }
  bool mutate_time(uint32_t _time = 0) {
    return SetField<uint32_t>(VT_TIME, _time, 0);
  }
  uint8_t page() const {
    return GetField<uint8_t>(VT_PAGE, 0);
  }
  bool mutate_page(uint8_t _page = 0) {
    return SetField<uint8_t>(VT_PAGE, _page, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X1, 4) &&
           VerifyField<float>(verifier, VT_Y1, 4) &&
           VerifyField<float>(verifier, VT_X2, 4) &&
           VerifyField<float>(verifier, VT_Y2, 4) &&
           VerifyField<uint32_t>(verifier, VT_TIME, 4) &&
           VerifyField<uint8_t>(verifier, VT_PAGE, 1) &&
           verifier.EndTable();
  }
  MovementT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(MovementT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Movement> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MovementT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct MovementBuilder {
  typedef Movement Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x1(float x1) {
    fbb_.AddElement<float>(Movement::VT_X1, x1, 0.0f);
  }
  void add_y1(float y1) {
    fbb_.AddElement<float>(Movement::VT_Y1, y1, 0.0f);
  }
  void add_x2(float x2) {
    fbb_.AddElement<float>(Movement::VT_X2, x2, 0.0f);
  }
  void add_y2(float y2) {
    fbb_.AddElement<float>(Movement::VT_Y2, y2, 0.0f);
  }
  void add_time(uint32_t time) {
    fbb_.AddElement<uint32_t>(Movement::VT_TIME, time, 0);
  }
  void add_page(uint8_t page) {
    fbb_.AddElement<uint8_t>(Movement::VT_PAGE, page, 0);
  }
  explicit MovementBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Movement> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Movement>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Movement> CreateMovement(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x1 = 0.0f,
    float y1 = 0.0f,
    float x2 = 0.0f,
    float y2 = 0.0f,
    uint32_t time = 0,
    uint8_t page = 0) {
  MovementBuilder builder_(_fbb);
  builder_.add_time(time);
  builder_.add_y2(y2);
  builder_.add_x2(x2);
  builder_.add_y1(y1);
  builder_.add_x1(x1);
  builder_.add_page(page);
  return builder_.Finish();
}

::flatbuffers::Offset<Movement> CreateMovement(::flatbuffers::FlatBufferBuilder &_fbb, const MovementT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline CharacterAppearanceT *CharacterAppearance::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CharacterAppearanceT>(new CharacterAppearanceT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CharacterAppearance::UnPackTo(CharacterAppearanceT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = body(); _o->body = _e; }
  { auto _e = head(); _o->head = _e; }
  { auto _e = weapon(); _o->weapon = _e; }
  { auto _e = cap(); _o->cap = _e; }
  { auto _e = cape(); _o->cape = _e; }
  { auto _e = coat(); _o->coat = _e; }
  { auto _e = glove(); _o->glove = _e; }
  { auto _e = pant(); _o->pant = _e; }
  { auto _e = shield(); _o->shield = _e; }
  { auto _e = longcoat(); _o->longcoat = _e; }
  { auto _e = shoes(); _o->shoes = _e; }
  { auto _e = accessory(); _o->accessory = _e; }
}

inline ::flatbuffers::Offset<CharacterAppearance> CreateCharacterAppearance(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterAppearanceT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CharacterAppearance::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CharacterAppearance> CharacterAppearance::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterAppearanceT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CharacterAppearanceT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _body = _o->body;
  auto _head = _o->head;
  auto _weapon = _o->weapon;
  auto _cap = _o->cap;
  auto _cape = _o->cape;
  auto _coat = _o->coat;
  auto _glove = _o->glove;
  auto _pant = _o->pant;
  auto _shield = _o->shield;
  auto _longcoat = _o->longcoat;
  auto _shoes = _o->shoes;
  auto _accessory = _o->accessory;
  return fbs::CreateCharacterAppearance(
      _fbb,
      _body,
      _head,
      _weapon,
      _cap,
      _cape,
      _coat,
      _glove,
      _pant,
      _shield,
      _longcoat,
      _shoes,
      _accessory);
}

inline CharacterT::CharacterT(const CharacterT &o)
      : name(o.name),
        x(o.x),
        y(o.y),
        action(o.action),
        action_index(o.action_index),
        appearance((o.appearance) ? new fbs::CharacterAppearanceT(*o.appearance) : nullptr) {
}

inline CharacterT &CharacterT::operator=(CharacterT o) FLATBUFFERS_NOEXCEPT {
  std::swap(name, o.name);
  std::swap(x, o.x);
  std::swap(y, o.y);
  std::swap(action, o.action);
  std::swap(action_index, o.action_index);
  std::swap(appearance, o.appearance);
  return *this;
}

inline CharacterT *Character::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CharacterT>(new CharacterT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Character::UnPackTo(CharacterT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = name(); if (_e) _o->name = _e->str(); }
  { auto _e = x(); _o->x = _e; }
  { auto _e = y(); _o->y = _e; }
  { auto _e = action(); if (_e) _o->action = _e->str(); }
  { auto _e = action_index(); _o->action_index = _e; }
  { auto _e = appearance(); if (_e) { if(_o->appearance) { _e->UnPackTo(_o->appearance.get(), _resolver); } else { _o->appearance = std::unique_ptr<fbs::CharacterAppearanceT>(_e->UnPack(_resolver)); } } else if (_o->appearance) { _o->appearance.reset(); } }
}

inline ::flatbuffers::Offset<Character> CreateCharacter(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Character::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Character> Character::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CharacterT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _x = _o->x;
  auto _y = _o->y;
  auto _action = _o->action.empty() ? 0 : _fbb.CreateString(_o->action);
  auto _action_index = _o->action_index;
  auto _appearance = _o->appearance ? CreateCharacterAppearance(_fbb, _o->appearance.get(), _rehasher) : 0;
  return fbs::CreateCharacter(
      _fbb,
      _name,
      _x,
      _y,
      _action,
      _action_index,
      _appearance);
}

inline PlayerT::PlayerT(const PlayerT &o)
      : client_id(o.client_id),
        character((o.character) ? new fbs::CharacterT(*o.character) : nullptr) {
}

inline PlayerT &PlayerT::operator=(PlayerT o) FLATBUFFERS_NOEXCEPT {
  std::swap(client_id, o.client_id);
  std::swap(character, o.character);
  return *this;
}

inline PlayerT *Player::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<PlayerT>(new PlayerT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Player::UnPackTo(PlayerT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = client_id(); _o->client_id = _e; }
  { auto _e = character(); if (_e) { if(_o->character) { _e->UnPackTo(_o->character.get(), _resolver); } else { _o->character = std::unique_ptr<fbs::CharacterT>(_e->UnPack(_resolver)); } } else if (_o->character) { _o->character.reset(); } }
}

inline ::flatbuffers::Offset<Player> CreatePlayer(::flatbuffers::FlatBufferBuilder &_fbb, const PlayerT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Player::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Player> Player::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PlayerT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const PlayerT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _client_id = _o->client_id;
  auto _character = _o->character ? CreateCharacter(_fbb, _o->character.get(), _rehasher) : 0;
  return fbs::CreatePlayer(
      _fbb,
      _client_id,
      _character);
}

inline MovementT *Movement::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<MovementT>(new MovementT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Movement::UnPackTo(MovementT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x1(); _o->x1 = _e; }
  { auto _e = y1(); _o->y1 = _e; }
  { auto _e = x2(); _o->x2 = _e; }
  { auto _e = y2(); _o->y2 = _e; }
  { auto _e = time(); _o->time = _e; }
  { auto _e = page(); _o->page = _e; }
}

inline ::flatbuffers::Offset<Movement> CreateMovement(::flatbuffers::FlatBufferBuilder &_fbb, const MovementT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Movement::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Movement> Movement::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MovementT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const MovementT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x1 = _o->x1;
  auto _y1 = _o->y1;
  auto _x2 = _o->x2;
  auto _y2 = _o->y2;
  auto _time = _o->time;
  auto _page = _o->page;
  return fbs::CreateMovement(
      _fbb,
      _x1,
      _y1,
      _x2,
      _y2,
      _time,
      _page);
}

}  // namespace fbs

#endif  // FLATBUFFERS_GENERATED_COMMON_FBS_H_
