// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMMON_FBS_H_
#define FLATBUFFERS_GENERATED_COMMON_FBS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace fbs {

struct LifeState;
struct LifeStateBuilder;
struct LifeStateT;

struct CharacterAppearance;
struct CharacterAppearanceBuilder;
struct CharacterAppearanceT;

struct Character;
struct CharacterBuilder;
struct CharacterT;

struct Player;
struct PlayerBuilder;
struct PlayerT;

struct Movement;
struct MovementBuilder;
struct MovementT;

struct Mob;
struct MobBuilder;
struct MobT;

struct MobMovement;
struct MobMovementBuilder;
struct MobMovementT;

struct DropEquip;
struct DropEquipBuilder;
struct DropEquipT;

struct DropItem;
struct DropItemBuilder;
struct DropItemT;

struct LifeStateT : public ::flatbuffers::NativeTable {
  typedef LifeState TableType;
  float x = 0.0f;
  float y = 0.0f;
  std::string action{};
  uint8_t action_index = 0;
  int32_t fh = 0;
  bool flip = false;
};

struct LifeState FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LifeStateT NativeTableType;
  typedef LifeStateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_ACTION = 8,
    VT_ACTION_INDEX = 10,
    VT_FH = 12,
    VT_FLIP = 14
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  bool mutate_x(float _x = 0.0f) {
    return SetField<float>(VT_X, _x, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  bool mutate_y(float _y = 0.0f) {
    return SetField<float>(VT_Y, _y, 0.0f);
  }
  const ::flatbuffers::String *action() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ACTION);
  }
  ::flatbuffers::String *mutable_action() {
    return GetPointer<::flatbuffers::String *>(VT_ACTION);
  }
  uint8_t action_index() const {
    return GetField<uint8_t>(VT_ACTION_INDEX, 0);
  }
  bool mutate_action_index(uint8_t _action_index = 0) {
    return SetField<uint8_t>(VT_ACTION_INDEX, _action_index, 0);
  }
  int32_t fh() const {
    return GetField<int32_t>(VT_FH, 0);
  }
  bool mutate_fh(int32_t _fh = 0) {
    return SetField<int32_t>(VT_FH, _fh, 0);
  }
  bool flip() const {
    return GetField<uint8_t>(VT_FLIP, 0) != 0;
  }
  bool mutate_flip(bool _flip = 0) {
    return SetField<uint8_t>(VT_FLIP, static_cast<uint8_t>(_flip), 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyOffset(verifier, VT_ACTION) &&
           verifier.VerifyString(action()) &&
           VerifyField<uint8_t>(verifier, VT_ACTION_INDEX, 1) &&
           VerifyField<int32_t>(verifier, VT_FH, 4) &&
           VerifyField<uint8_t>(verifier, VT_FLIP, 1) &&
           verifier.EndTable();
  }
  LifeStateT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(LifeStateT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<LifeState> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const LifeStateT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct LifeStateBuilder {
  typedef LifeState Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(LifeState::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(LifeState::VT_Y, y, 0.0f);
  }
  void add_action(::flatbuffers::Offset<::flatbuffers::String> action) {
    fbb_.AddOffset(LifeState::VT_ACTION, action);
  }
  void add_action_index(uint8_t action_index) {
    fbb_.AddElement<uint8_t>(LifeState::VT_ACTION_INDEX, action_index, 0);
  }
  void add_fh(int32_t fh) {
    fbb_.AddElement<int32_t>(LifeState::VT_FH, fh, 0);
  }
  void add_flip(bool flip) {
    fbb_.AddElement<uint8_t>(LifeState::VT_FLIP, static_cast<uint8_t>(flip), 0);
  }
  explicit LifeStateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LifeState> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LifeState>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LifeState> CreateLifeState(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    ::flatbuffers::Offset<::flatbuffers::String> action = 0,
    uint8_t action_index = 0,
    int32_t fh = 0,
    bool flip = false) {
  LifeStateBuilder builder_(_fbb);
  builder_.add_fh(fh);
  builder_.add_action(action);
  builder_.add_y(y);
  builder_.add_x(x);
  builder_.add_flip(flip);
  builder_.add_action_index(action_index);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<LifeState> CreateLifeStateDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    const char *action = nullptr,
    uint8_t action_index = 0,
    int32_t fh = 0,
    bool flip = false) {
  auto action__ = action ? _fbb.CreateString(action) : 0;
  return fbs::CreateLifeState(
      _fbb,
      x,
      y,
      action__,
      action_index,
      fh,
      flip);
}

::flatbuffers::Offset<LifeState> CreateLifeState(::flatbuffers::FlatBufferBuilder &_fbb, const LifeStateT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CharacterAppearanceT : public ::flatbuffers::NativeTable {
  typedef CharacterAppearance TableType;
  uint32_t body = 0;
  uint32_t head = 0;
  uint32_t face = 0;
  uint32_t hair = 0;
  uint32_t weapon = 0;
  uint32_t cap = 0;
  uint32_t cape = 0;
  uint32_t coat = 0;
  uint32_t glove = 0;
  uint32_t pant = 0;
  uint32_t shield = 0;
  uint32_t longcoat = 0;
  uint32_t shoes = 0;
  uint32_t accessory = 0;
};

struct CharacterAppearance FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CharacterAppearanceT NativeTableType;
  typedef CharacterAppearanceBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BODY = 4,
    VT_HEAD = 6,
    VT_FACE = 8,
    VT_HAIR = 10,
    VT_WEAPON = 12,
    VT_CAP = 14,
    VT_CAPE = 16,
    VT_COAT = 18,
    VT_GLOVE = 20,
    VT_PANT = 22,
    VT_SHIELD = 24,
    VT_LONGCOAT = 26,
    VT_SHOES = 28,
    VT_ACCESSORY = 30
  };
  uint32_t body() const {
    return GetField<uint32_t>(VT_BODY, 0);
  }
  bool mutate_body(uint32_t _body = 0) {
    return SetField<uint32_t>(VT_BODY, _body, 0);
  }
  uint32_t head() const {
    return GetField<uint32_t>(VT_HEAD, 0);
  }
  bool mutate_head(uint32_t _head = 0) {
    return SetField<uint32_t>(VT_HEAD, _head, 0);
  }
  uint32_t face() const {
    return GetField<uint32_t>(VT_FACE, 0);
  }
  bool mutate_face(uint32_t _face = 0) {
    return SetField<uint32_t>(VT_FACE, _face, 0);
  }
  uint32_t hair() const {
    return GetField<uint32_t>(VT_HAIR, 0);
  }
  bool mutate_hair(uint32_t _hair = 0) {
    return SetField<uint32_t>(VT_HAIR, _hair, 0);
  }
  uint32_t weapon() const {
    return GetField<uint32_t>(VT_WEAPON, 0);
  }
  bool mutate_weapon(uint32_t _weapon = 0) {
    return SetField<uint32_t>(VT_WEAPON, _weapon, 0);
  }
  uint32_t cap() const {
    return GetField<uint32_t>(VT_CAP, 0);
  }
  bool mutate_cap(uint32_t _cap = 0) {
    return SetField<uint32_t>(VT_CAP, _cap, 0);
  }
  uint32_t cape() const {
    return GetField<uint32_t>(VT_CAPE, 0);
  }
  bool mutate_cape(uint32_t _cape = 0) {
    return SetField<uint32_t>(VT_CAPE, _cape, 0);
  }
  uint32_t coat() const {
    return GetField<uint32_t>(VT_COAT, 0);
  }
  bool mutate_coat(uint32_t _coat = 0) {
    return SetField<uint32_t>(VT_COAT, _coat, 0);
  }
  uint32_t glove() const {
    return GetField<uint32_t>(VT_GLOVE, 0);
  }
  bool mutate_glove(uint32_t _glove = 0) {
    return SetField<uint32_t>(VT_GLOVE, _glove, 0);
  }
  uint32_t pant() const {
    return GetField<uint32_t>(VT_PANT, 0);
  }
  bool mutate_pant(uint32_t _pant = 0) {
    return SetField<uint32_t>(VT_PANT, _pant, 0);
  }
  uint32_t shield() const {
    return GetField<uint32_t>(VT_SHIELD, 0);
  }
  bool mutate_shield(uint32_t _shield = 0) {
    return SetField<uint32_t>(VT_SHIELD, _shield, 0);
  }
  uint32_t longcoat() const {
    return GetField<uint32_t>(VT_LONGCOAT, 0);
  }
  bool mutate_longcoat(uint32_t _longcoat = 0) {
    return SetField<uint32_t>(VT_LONGCOAT, _longcoat, 0);
  }
  uint32_t shoes() const {
    return GetField<uint32_t>(VT_SHOES, 0);
  }
  bool mutate_shoes(uint32_t _shoes = 0) {
    return SetField<uint32_t>(VT_SHOES, _shoes, 0);
  }
  uint32_t accessory() const {
    return GetField<uint32_t>(VT_ACCESSORY, 0);
  }
  bool mutate_accessory(uint32_t _accessory = 0) {
    return SetField<uint32_t>(VT_ACCESSORY, _accessory, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_BODY, 4) &&
           VerifyField<uint32_t>(verifier, VT_HEAD, 4) &&
           VerifyField<uint32_t>(verifier, VT_FACE, 4) &&
           VerifyField<uint32_t>(verifier, VT_HAIR, 4) &&
           VerifyField<uint32_t>(verifier, VT_WEAPON, 4) &&
           VerifyField<uint32_t>(verifier, VT_CAP, 4) &&
           VerifyField<uint32_t>(verifier, VT_CAPE, 4) &&
           VerifyField<uint32_t>(verifier, VT_COAT, 4) &&
           VerifyField<uint32_t>(verifier, VT_GLOVE, 4) &&
           VerifyField<uint32_t>(verifier, VT_PANT, 4) &&
           VerifyField<uint32_t>(verifier, VT_SHIELD, 4) &&
           VerifyField<uint32_t>(verifier, VT_LONGCOAT, 4) &&
           VerifyField<uint32_t>(verifier, VT_SHOES, 4) &&
           VerifyField<uint32_t>(verifier, VT_ACCESSORY, 4) &&
           verifier.EndTable();
  }
  CharacterAppearanceT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CharacterAppearanceT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CharacterAppearance> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterAppearanceT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CharacterAppearanceBuilder {
  typedef CharacterAppearance Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_body(uint32_t body) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_BODY, body, 0);
  }
  void add_head(uint32_t head) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_HEAD, head, 0);
  }
  void add_face(uint32_t face) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_FACE, face, 0);
  }
  void add_hair(uint32_t hair) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_HAIR, hair, 0);
  }
  void add_weapon(uint32_t weapon) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_WEAPON, weapon, 0);
  }
  void add_cap(uint32_t cap) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_CAP, cap, 0);
  }
  void add_cape(uint32_t cape) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_CAPE, cape, 0);
  }
  void add_coat(uint32_t coat) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_COAT, coat, 0);
  }
  void add_glove(uint32_t glove) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_GLOVE, glove, 0);
  }
  void add_pant(uint32_t pant) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_PANT, pant, 0);
  }
  void add_shield(uint32_t shield) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_SHIELD, shield, 0);
  }
  void add_longcoat(uint32_t longcoat) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_LONGCOAT, longcoat, 0);
  }
  void add_shoes(uint32_t shoes) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_SHOES, shoes, 0);
  }
  void add_accessory(uint32_t accessory) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_ACCESSORY, accessory, 0);
  }
  explicit CharacterAppearanceBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CharacterAppearance> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CharacterAppearance>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CharacterAppearance> CreateCharacterAppearance(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t body = 0,
    uint32_t head = 0,
    uint32_t face = 0,
    uint32_t hair = 0,
    uint32_t weapon = 0,
    uint32_t cap = 0,
    uint32_t cape = 0,
    uint32_t coat = 0,
    uint32_t glove = 0,
    uint32_t pant = 0,
    uint32_t shield = 0,
    uint32_t longcoat = 0,
    uint32_t shoes = 0,
    uint32_t accessory = 0) {
  CharacterAppearanceBuilder builder_(_fbb);
  builder_.add_accessory(accessory);
  builder_.add_shoes(shoes);
  builder_.add_longcoat(longcoat);
  builder_.add_shield(shield);
  builder_.add_pant(pant);
  builder_.add_glove(glove);
  builder_.add_coat(coat);
  builder_.add_cape(cape);
  builder_.add_cap(cap);
  builder_.add_weapon(weapon);
  builder_.add_hair(hair);
  builder_.add_face(face);
  builder_.add_head(head);
  builder_.add_body(body);
  return builder_.Finish();
}

::flatbuffers::Offset<CharacterAppearance> CreateCharacterAppearance(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterAppearanceT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CharacterT : public ::flatbuffers::NativeTable {
  typedef Character TableType;
  std::string name{};
  std::unique_ptr<fbs::LifeStateT> state{};
  std::unique_ptr<fbs::CharacterAppearanceT> appearance{};
  CharacterT() = default;
  CharacterT(const CharacterT &o);
  CharacterT(CharacterT&&) FLATBUFFERS_NOEXCEPT = default;
  CharacterT &operator=(CharacterT o) FLATBUFFERS_NOEXCEPT;
};

struct Character FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CharacterT NativeTableType;
  typedef CharacterBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_STATE = 6,
    VT_APPEARANCE = 8
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  ::flatbuffers::String *mutable_name() {
    return GetPointer<::flatbuffers::String *>(VT_NAME);
  }
  const fbs::LifeState *state() const {
    return GetPointer<const fbs::LifeState *>(VT_STATE);
  }
  fbs::LifeState *mutable_state() {
    return GetPointer<fbs::LifeState *>(VT_STATE);
  }
  const fbs::CharacterAppearance *appearance() const {
    return GetPointer<const fbs::CharacterAppearance *>(VT_APPEARANCE);
  }
  fbs::CharacterAppearance *mutable_appearance() {
    return GetPointer<fbs::CharacterAppearance *>(VT_APPEARANCE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_STATE) &&
           verifier.VerifyTable(state()) &&
           VerifyOffset(verifier, VT_APPEARANCE) &&
           verifier.VerifyTable(appearance()) &&
           verifier.EndTable();
  }
  CharacterT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CharacterT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Character> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CharacterBuilder {
  typedef Character Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Character::VT_NAME, name);
  }
  void add_state(::flatbuffers::Offset<fbs::LifeState> state) {
    fbb_.AddOffset(Character::VT_STATE, state);
  }
  void add_appearance(::flatbuffers::Offset<fbs::CharacterAppearance> appearance) {
    fbb_.AddOffset(Character::VT_APPEARANCE, appearance);
  }
  explicit CharacterBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Character> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Character>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Character> CreateCharacter(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<fbs::LifeState> state = 0,
    ::flatbuffers::Offset<fbs::CharacterAppearance> appearance = 0) {
  CharacterBuilder builder_(_fbb);
  builder_.add_appearance(appearance);
  builder_.add_state(state);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Character> CreateCharacterDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    ::flatbuffers::Offset<fbs::LifeState> state = 0,
    ::flatbuffers::Offset<fbs::CharacterAppearance> appearance = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return fbs::CreateCharacter(
      _fbb,
      name__,
      state,
      appearance);
}

::flatbuffers::Offset<Character> CreateCharacter(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct PlayerT : public ::flatbuffers::NativeTable {
  typedef Player TableType;
  uint64_t client_id = 0;
  std::unique_ptr<fbs::CharacterT> character{};
  PlayerT() = default;
  PlayerT(const PlayerT &o);
  PlayerT(PlayerT&&) FLATBUFFERS_NOEXCEPT = default;
  PlayerT &operator=(PlayerT o) FLATBUFFERS_NOEXCEPT;
};

struct Player FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PlayerT NativeTableType;
  typedef PlayerBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLIENT_ID = 4,
    VT_CHARACTER = 6
  };
  uint64_t client_id() const {
    return GetField<uint64_t>(VT_CLIENT_ID, 0);
  }
  bool mutate_client_id(uint64_t _client_id = 0) {
    return SetField<uint64_t>(VT_CLIENT_ID, _client_id, 0);
  }
  const fbs::Character *character() const {
    return GetPointer<const fbs::Character *>(VT_CHARACTER);
  }
  fbs::Character *mutable_character() {
    return GetPointer<fbs::Character *>(VT_CHARACTER);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CLIENT_ID, 8) &&
           VerifyOffset(verifier, VT_CHARACTER) &&
           verifier.VerifyTable(character()) &&
           verifier.EndTable();
  }
  PlayerT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(PlayerT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Player> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PlayerT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct PlayerBuilder {
  typedef Player Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_client_id(uint64_t client_id) {
    fbb_.AddElement<uint64_t>(Player::VT_CLIENT_ID, client_id, 0);
  }
  void add_character(::flatbuffers::Offset<fbs::Character> character) {
    fbb_.AddOffset(Player::VT_CHARACTER, character);
  }
  explicit PlayerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Player> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Player>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Player> CreatePlayer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t client_id = 0,
    ::flatbuffers::Offset<fbs::Character> character = 0) {
  PlayerBuilder builder_(_fbb);
  builder_.add_client_id(client_id);
  builder_.add_character(character);
  return builder_.Finish();
}

::flatbuffers::Offset<Player> CreatePlayer(::flatbuffers::FlatBufferBuilder &_fbb, const PlayerT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct MovementT : public ::flatbuffers::NativeTable {
  typedef Movement TableType;
  float x1 = 0.0f;
  float y1 = 0.0f;
  float x2 = 0.0f;
  float y2 = 0.0f;
  uint32_t time = 0;
  int32_t fh = 0;
  std::string action{};
  bool flip = false;
};

struct Movement FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MovementT NativeTableType;
  typedef MovementBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X1 = 4,
    VT_Y1 = 6,
    VT_X2 = 8,
    VT_Y2 = 10,
    VT_TIME = 12,
    VT_FH = 14,
    VT_ACTION = 16,
    VT_FLIP = 18
  };
  float x1() const {
    return GetField<float>(VT_X1, 0.0f);
  }
  bool mutate_x1(float _x1 = 0.0f) {
    return SetField<float>(VT_X1, _x1, 0.0f);
  }
  float y1() const {
    return GetField<float>(VT_Y1, 0.0f);
  }
  bool mutate_y1(float _y1 = 0.0f) {
    return SetField<float>(VT_Y1, _y1, 0.0f);
  }
  float x2() const {
    return GetField<float>(VT_X2, 0.0f);
  }
  bool mutate_x2(float _x2 = 0.0f) {
    return SetField<float>(VT_X2, _x2, 0.0f);
  }
  float y2() const {
    return GetField<float>(VT_Y2, 0.0f);
  }
  bool mutate_y2(float _y2 = 0.0f) {
    return SetField<float>(VT_Y2, _y2, 0.0f);
  }
  uint32_t time() const {
    return GetField<uint32_t>(VT_TIME, 0);
  }
  bool mutate_time(uint32_t _time = 0) {
    return SetField<uint32_t>(VT_TIME, _time, 0);
  }
  int32_t fh() const {
    return GetField<int32_t>(VT_FH, 0);
  }
  bool mutate_fh(int32_t _fh = 0) {
    return SetField<int32_t>(VT_FH, _fh, 0);
  }
  const ::flatbuffers::String *action() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ACTION);
  }
  ::flatbuffers::String *mutable_action() {
    return GetPointer<::flatbuffers::String *>(VT_ACTION);
  }
  bool flip() const {
    return GetField<uint8_t>(VT_FLIP, 0) != 0;
  }
  bool mutate_flip(bool _flip = 0) {
    return SetField<uint8_t>(VT_FLIP, static_cast<uint8_t>(_flip), 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X1, 4) &&
           VerifyField<float>(verifier, VT_Y1, 4) &&
           VerifyField<float>(verifier, VT_X2, 4) &&
           VerifyField<float>(verifier, VT_Y2, 4) &&
           VerifyField<uint32_t>(verifier, VT_TIME, 4) &&
           VerifyField<int32_t>(verifier, VT_FH, 4) &&
           VerifyOffset(verifier, VT_ACTION) &&
           verifier.VerifyString(action()) &&
           VerifyField<uint8_t>(verifier, VT_FLIP, 1) &&
           verifier.EndTable();
  }
  MovementT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(MovementT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Movement> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MovementT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct MovementBuilder {
  typedef Movement Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x1(float x1) {
    fbb_.AddElement<float>(Movement::VT_X1, x1, 0.0f);
  }
  void add_y1(float y1) {
    fbb_.AddElement<float>(Movement::VT_Y1, y1, 0.0f);
  }
  void add_x2(float x2) {
    fbb_.AddElement<float>(Movement::VT_X2, x2, 0.0f);
  }
  void add_y2(float y2) {
    fbb_.AddElement<float>(Movement::VT_Y2, y2, 0.0f);
  }
  void add_time(uint32_t time) {
    fbb_.AddElement<uint32_t>(Movement::VT_TIME, time, 0);
  }
  void add_fh(int32_t fh) {
    fbb_.AddElement<int32_t>(Movement::VT_FH, fh, 0);
  }
  void add_action(::flatbuffers::Offset<::flatbuffers::String> action) {
    fbb_.AddOffset(Movement::VT_ACTION, action);
  }
  void add_flip(bool flip) {
    fbb_.AddElement<uint8_t>(Movement::VT_FLIP, static_cast<uint8_t>(flip), 0);
  }
  explicit MovementBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Movement> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Movement>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Movement> CreateMovement(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x1 = 0.0f,
    float y1 = 0.0f,
    float x2 = 0.0f,
    float y2 = 0.0f,
    uint32_t time = 0,
    int32_t fh = 0,
    ::flatbuffers::Offset<::flatbuffers::String> action = 0,
    bool flip = false) {
  MovementBuilder builder_(_fbb);
  builder_.add_action(action);
  builder_.add_fh(fh);
  builder_.add_time(time);
  builder_.add_y2(y2);
  builder_.add_x2(x2);
  builder_.add_y1(y1);
  builder_.add_x1(x1);
  builder_.add_flip(flip);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Movement> CreateMovementDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x1 = 0.0f,
    float y1 = 0.0f,
    float x2 = 0.0f,
    float y2 = 0.0f,
    uint32_t time = 0,
    int32_t fh = 0,
    const char *action = nullptr,
    bool flip = false) {
  auto action__ = action ? _fbb.CreateString(action) : 0;
  return fbs::CreateMovement(
      _fbb,
      x1,
      y1,
      x2,
      y2,
      time,
      fh,
      action__,
      flip);
}

::flatbuffers::Offset<Movement> CreateMovement(::flatbuffers::FlatBufferBuilder &_fbb, const MovementT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct MobT : public ::flatbuffers::NativeTable {
  typedef Mob TableType;
  uint32_t mob_id = 0;
  bool summon = false;
  std::unique_ptr<fbs::LifeStateT> state{};
  MobT() = default;
  MobT(const MobT &o);
  MobT(MobT&&) FLATBUFFERS_NOEXCEPT = default;
  MobT &operator=(MobT o) FLATBUFFERS_NOEXCEPT;
};

struct Mob FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MobT NativeTableType;
  typedef MobBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MOB_ID = 4,
    VT_SUMMON = 6,
    VT_STATE = 8
  };
  uint32_t mob_id() const {
    return GetField<uint32_t>(VT_MOB_ID, 0);
  }
  bool mutate_mob_id(uint32_t _mob_id = 0) {
    return SetField<uint32_t>(VT_MOB_ID, _mob_id, 0);
  }
  bool summon() const {
    return GetField<uint8_t>(VT_SUMMON, 0) != 0;
  }
  bool mutate_summon(bool _summon = 0) {
    return SetField<uint8_t>(VT_SUMMON, static_cast<uint8_t>(_summon), 0);
  }
  const fbs::LifeState *state() const {
    return GetPointer<const fbs::LifeState *>(VT_STATE);
  }
  fbs::LifeState *mutable_state() {
    return GetPointer<fbs::LifeState *>(VT_STATE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_MOB_ID, 4) &&
           VerifyField<uint8_t>(verifier, VT_SUMMON, 1) &&
           VerifyOffset(verifier, VT_STATE) &&
           verifier.VerifyTable(state()) &&
           verifier.EndTable();
  }
  MobT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(MobT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Mob> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MobT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct MobBuilder {
  typedef Mob Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_mob_id(uint32_t mob_id) {
    fbb_.AddElement<uint32_t>(Mob::VT_MOB_ID, mob_id, 0);
  }
  void add_summon(bool summon) {
    fbb_.AddElement<uint8_t>(Mob::VT_SUMMON, static_cast<uint8_t>(summon), 0);
  }
  void add_state(::flatbuffers::Offset<fbs::LifeState> state) {
    fbb_.AddOffset(Mob::VT_STATE, state);
  }
  explicit MobBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Mob> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Mob>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Mob> CreateMob(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t mob_id = 0,
    bool summon = false,
    ::flatbuffers::Offset<fbs::LifeState> state = 0) {
  MobBuilder builder_(_fbb);
  builder_.add_state(state);
  builder_.add_mob_id(mob_id);
  builder_.add_summon(summon);
  return builder_.Finish();
}

::flatbuffers::Offset<Mob> CreateMob(::flatbuffers::FlatBufferBuilder &_fbb, const MobT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct MobMovementT : public ::flatbuffers::NativeTable {
  typedef MobMovement TableType;
  uint32_t mob_id = 0;
  std::unique_ptr<fbs::MovementT> movement{};
  MobMovementT() = default;
  MobMovementT(const MobMovementT &o);
  MobMovementT(MobMovementT&&) FLATBUFFERS_NOEXCEPT = default;
  MobMovementT &operator=(MobMovementT o) FLATBUFFERS_NOEXCEPT;
};

struct MobMovement FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MobMovementT NativeTableType;
  typedef MobMovementBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MOB_ID = 4,
    VT_MOVEMENT = 6
  };
  uint32_t mob_id() const {
    return GetField<uint32_t>(VT_MOB_ID, 0);
  }
  bool mutate_mob_id(uint32_t _mob_id = 0) {
    return SetField<uint32_t>(VT_MOB_ID, _mob_id, 0);
  }
  const fbs::Movement *movement() const {
    return GetPointer<const fbs::Movement *>(VT_MOVEMENT);
  }
  fbs::Movement *mutable_movement() {
    return GetPointer<fbs::Movement *>(VT_MOVEMENT);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_MOB_ID, 4) &&
           VerifyOffset(verifier, VT_MOVEMENT) &&
           verifier.VerifyTable(movement()) &&
           verifier.EndTable();
  }
  MobMovementT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(MobMovementT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<MobMovement> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MobMovementT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct MobMovementBuilder {
  typedef MobMovement Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_mob_id(uint32_t mob_id) {
    fbb_.AddElement<uint32_t>(MobMovement::VT_MOB_ID, mob_id, 0);
  }
  void add_movement(::flatbuffers::Offset<fbs::Movement> movement) {
    fbb_.AddOffset(MobMovement::VT_MOVEMENT, movement);
  }
  explicit MobMovementBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MobMovement> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MobMovement>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MobMovement> CreateMobMovement(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t mob_id = 0,
    ::flatbuffers::Offset<fbs::Movement> movement = 0) {
  MobMovementBuilder builder_(_fbb);
  builder_.add_movement(movement);
  builder_.add_mob_id(mob_id);
  return builder_.Finish();
}

::flatbuffers::Offset<MobMovement> CreateMobMovement(::flatbuffers::FlatBufferBuilder &_fbb, const MobMovementT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct DropEquipT : public ::flatbuffers::NativeTable {
  typedef DropEquip TableType;
  uint32_t equip_id = 0;
  float x = 0.0f;
  float y = 0.0f;
  uint32_t rotate = 0;
  float hspeed = 0.0f;
  float vspeed = 0.0f;
};

struct DropEquip FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DropEquipT NativeTableType;
  typedef DropEquipBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_EQUIP_ID = 4,
    VT_X = 6,
    VT_Y = 8,
    VT_ROTATE = 10,
    VT_HSPEED = 12,
    VT_VSPEED = 14
  };
  uint32_t equip_id() const {
    return GetField<uint32_t>(VT_EQUIP_ID, 0);
  }
  bool mutate_equip_id(uint32_t _equip_id = 0) {
    return SetField<uint32_t>(VT_EQUIP_ID, _equip_id, 0);
  }
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  bool mutate_x(float _x = 0.0f) {
    return SetField<float>(VT_X, _x, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  bool mutate_y(float _y = 0.0f) {
    return SetField<float>(VT_Y, _y, 0.0f);
  }
  uint32_t rotate() const {
    return GetField<uint32_t>(VT_ROTATE, 0);
  }
  bool mutate_rotate(uint32_t _rotate = 0) {
    return SetField<uint32_t>(VT_ROTATE, _rotate, 0);
  }
  float hspeed() const {
    return GetField<float>(VT_HSPEED, 0.0f);
  }
  bool mutate_hspeed(float _hspeed = 0.0f) {
    return SetField<float>(VT_HSPEED, _hspeed, 0.0f);
  }
  float vspeed() const {
    return GetField<float>(VT_VSPEED, 0.0f);
  }
  bool mutate_vspeed(float _vspeed = 0.0f) {
    return SetField<float>(VT_VSPEED, _vspeed, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_EQUIP_ID, 4) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<uint32_t>(verifier, VT_ROTATE, 4) &&
           VerifyField<float>(verifier, VT_HSPEED, 4) &&
           VerifyField<float>(verifier, VT_VSPEED, 4) &&
           verifier.EndTable();
  }
  DropEquipT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(DropEquipT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<DropEquip> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DropEquipT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct DropEquipBuilder {
  typedef DropEquip Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_equip_id(uint32_t equip_id) {
    fbb_.AddElement<uint32_t>(DropEquip::VT_EQUIP_ID, equip_id, 0);
  }
  void add_x(float x) {
    fbb_.AddElement<float>(DropEquip::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(DropEquip::VT_Y, y, 0.0f);
  }
  void add_rotate(uint32_t rotate) {
    fbb_.AddElement<uint32_t>(DropEquip::VT_ROTATE, rotate, 0);
  }
  void add_hspeed(float hspeed) {
    fbb_.AddElement<float>(DropEquip::VT_HSPEED, hspeed, 0.0f);
  }
  void add_vspeed(float vspeed) {
    fbb_.AddElement<float>(DropEquip::VT_VSPEED, vspeed, 0.0f);
  }
  explicit DropEquipBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DropEquip> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DropEquip>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DropEquip> CreateDropEquip(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t equip_id = 0,
    float x = 0.0f,
    float y = 0.0f,
    uint32_t rotate = 0,
    float hspeed = 0.0f,
    float vspeed = 0.0f) {
  DropEquipBuilder builder_(_fbb);
  builder_.add_vspeed(vspeed);
  builder_.add_hspeed(hspeed);
  builder_.add_rotate(rotate);
  builder_.add_y(y);
  builder_.add_x(x);
  builder_.add_equip_id(equip_id);
  return builder_.Finish();
}

::flatbuffers::Offset<DropEquip> CreateDropEquip(::flatbuffers::FlatBufferBuilder &_fbb, const DropEquipT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct DropItemT : public ::flatbuffers::NativeTable {
  typedef DropItem TableType;
  uint32_t item_id = 0;
  float x = 0.0f;
  float y = 0.0f;
  uint32_t num = 0;
  uint32_t rotate = 0;
  float hspeed = 0.0f;
  float vspeed = 0.0f;
};

struct DropItem FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DropItemT NativeTableType;
  typedef DropItemBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ITEM_ID = 4,
    VT_X = 6,
    VT_Y = 8,
    VT_NUM = 10,
    VT_ROTATE = 12,
    VT_HSPEED = 14,
    VT_VSPEED = 16
  };
  uint32_t item_id() const {
    return GetField<uint32_t>(VT_ITEM_ID, 0);
  }
  bool mutate_item_id(uint32_t _item_id = 0) {
    return SetField<uint32_t>(VT_ITEM_ID, _item_id, 0);
  }
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  bool mutate_x(float _x = 0.0f) {
    return SetField<float>(VT_X, _x, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  bool mutate_y(float _y = 0.0f) {
    return SetField<float>(VT_Y, _y, 0.0f);
  }
  uint32_t num() const {
    return GetField<uint32_t>(VT_NUM, 0);
  }
  bool mutate_num(uint32_t _num = 0) {
    return SetField<uint32_t>(VT_NUM, _num, 0);
  }
  uint32_t rotate() const {
    return GetField<uint32_t>(VT_ROTATE, 0);
  }
  bool mutate_rotate(uint32_t _rotate = 0) {
    return SetField<uint32_t>(VT_ROTATE, _rotate, 0);
  }
  float hspeed() const {
    return GetField<float>(VT_HSPEED, 0.0f);
  }
  bool mutate_hspeed(float _hspeed = 0.0f) {
    return SetField<float>(VT_HSPEED, _hspeed, 0.0f);
  }
  float vspeed() const {
    return GetField<float>(VT_VSPEED, 0.0f);
  }
  bool mutate_vspeed(float _vspeed = 0.0f) {
    return SetField<float>(VT_VSPEED, _vspeed, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ITEM_ID, 4) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<uint32_t>(verifier, VT_NUM, 4) &&
           VerifyField<uint32_t>(verifier, VT_ROTATE, 4) &&
           VerifyField<float>(verifier, VT_HSPEED, 4) &&
           VerifyField<float>(verifier, VT_VSPEED, 4) &&
           verifier.EndTable();
  }
  DropItemT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(DropItemT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<DropItem> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DropItemT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct DropItemBuilder {
  typedef DropItem Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_item_id(uint32_t item_id) {
    fbb_.AddElement<uint32_t>(DropItem::VT_ITEM_ID, item_id, 0);
  }
  void add_x(float x) {
    fbb_.AddElement<float>(DropItem::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(DropItem::VT_Y, y, 0.0f);
  }
  void add_num(uint32_t num) {
    fbb_.AddElement<uint32_t>(DropItem::VT_NUM, num, 0);
  }
  void add_rotate(uint32_t rotate) {
    fbb_.AddElement<uint32_t>(DropItem::VT_ROTATE, rotate, 0);
  }
  void add_hspeed(float hspeed) {
    fbb_.AddElement<float>(DropItem::VT_HSPEED, hspeed, 0.0f);
  }
  void add_vspeed(float vspeed) {
    fbb_.AddElement<float>(DropItem::VT_VSPEED, vspeed, 0.0f);
  }
  explicit DropItemBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DropItem> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DropItem>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DropItem> CreateDropItem(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t item_id = 0,
    float x = 0.0f,
    float y = 0.0f,
    uint32_t num = 0,
    uint32_t rotate = 0,
    float hspeed = 0.0f,
    float vspeed = 0.0f) {
  DropItemBuilder builder_(_fbb);
  builder_.add_vspeed(vspeed);
  builder_.add_hspeed(hspeed);
  builder_.add_rotate(rotate);
  builder_.add_num(num);
  builder_.add_y(y);
  builder_.add_x(x);
  builder_.add_item_id(item_id);
  return builder_.Finish();
}

::flatbuffers::Offset<DropItem> CreateDropItem(::flatbuffers::FlatBufferBuilder &_fbb, const DropItemT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline LifeStateT *LifeState::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<LifeStateT>(new LifeStateT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void LifeState::UnPackTo(LifeStateT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x(); _o->x = _e; }
  { auto _e = y(); _o->y = _e; }
  { auto _e = action(); if (_e) _o->action = _e->str(); }
  { auto _e = action_index(); _o->action_index = _e; }
  { auto _e = fh(); _o->fh = _e; }
  { auto _e = flip(); _o->flip = _e; }
}

inline ::flatbuffers::Offset<LifeState> CreateLifeState(::flatbuffers::FlatBufferBuilder &_fbb, const LifeStateT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return LifeState::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<LifeState> LifeState::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const LifeStateT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const LifeStateT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x = _o->x;
  auto _y = _o->y;
  auto _action = _o->action.empty() ? 0 : _fbb.CreateString(_o->action);
  auto _action_index = _o->action_index;
  auto _fh = _o->fh;
  auto _flip = _o->flip;
  return fbs::CreateLifeState(
      _fbb,
      _x,
      _y,
      _action,
      _action_index,
      _fh,
      _flip);
}

inline CharacterAppearanceT *CharacterAppearance::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CharacterAppearanceT>(new CharacterAppearanceT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CharacterAppearance::UnPackTo(CharacterAppearanceT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = body(); _o->body = _e; }
  { auto _e = head(); _o->head = _e; }
  { auto _e = face(); _o->face = _e; }
  { auto _e = hair(); _o->hair = _e; }
  { auto _e = weapon(); _o->weapon = _e; }
  { auto _e = cap(); _o->cap = _e; }
  { auto _e = cape(); _o->cape = _e; }
  { auto _e = coat(); _o->coat = _e; }
  { auto _e = glove(); _o->glove = _e; }
  { auto _e = pant(); _o->pant = _e; }
  { auto _e = shield(); _o->shield = _e; }
  { auto _e = longcoat(); _o->longcoat = _e; }
  { auto _e = shoes(); _o->shoes = _e; }
  { auto _e = accessory(); _o->accessory = _e; }
}

inline ::flatbuffers::Offset<CharacterAppearance> CreateCharacterAppearance(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterAppearanceT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CharacterAppearance::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CharacterAppearance> CharacterAppearance::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterAppearanceT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CharacterAppearanceT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _body = _o->body;
  auto _head = _o->head;
  auto _face = _o->face;
  auto _hair = _o->hair;
  auto _weapon = _o->weapon;
  auto _cap = _o->cap;
  auto _cape = _o->cape;
  auto _coat = _o->coat;
  auto _glove = _o->glove;
  auto _pant = _o->pant;
  auto _shield = _o->shield;
  auto _longcoat = _o->longcoat;
  auto _shoes = _o->shoes;
  auto _accessory = _o->accessory;
  return fbs::CreateCharacterAppearance(
      _fbb,
      _body,
      _head,
      _face,
      _hair,
      _weapon,
      _cap,
      _cape,
      _coat,
      _glove,
      _pant,
      _shield,
      _longcoat,
      _shoes,
      _accessory);
}

inline CharacterT::CharacterT(const CharacterT &o)
      : name(o.name),
        state((o.state) ? new fbs::LifeStateT(*o.state) : nullptr),
        appearance((o.appearance) ? new fbs::CharacterAppearanceT(*o.appearance) : nullptr) {
}

inline CharacterT &CharacterT::operator=(CharacterT o) FLATBUFFERS_NOEXCEPT {
  std::swap(name, o.name);
  std::swap(state, o.state);
  std::swap(appearance, o.appearance);
  return *this;
}

inline CharacterT *Character::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CharacterT>(new CharacterT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Character::UnPackTo(CharacterT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = name(); if (_e) _o->name = _e->str(); }
  { auto _e = state(); if (_e) { if(_o->state) { _e->UnPackTo(_o->state.get(), _resolver); } else { _o->state = std::unique_ptr<fbs::LifeStateT>(_e->UnPack(_resolver)); } } else if (_o->state) { _o->state.reset(); } }
  { auto _e = appearance(); if (_e) { if(_o->appearance) { _e->UnPackTo(_o->appearance.get(), _resolver); } else { _o->appearance = std::unique_ptr<fbs::CharacterAppearanceT>(_e->UnPack(_resolver)); } } else if (_o->appearance) { _o->appearance.reset(); } }
}

inline ::flatbuffers::Offset<Character> CreateCharacter(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Character::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Character> Character::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CharacterT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _state = _o->state ? CreateLifeState(_fbb, _o->state.get(), _rehasher) : 0;
  auto _appearance = _o->appearance ? CreateCharacterAppearance(_fbb, _o->appearance.get(), _rehasher) : 0;
  return fbs::CreateCharacter(
      _fbb,
      _name,
      _state,
      _appearance);
}

inline PlayerT::PlayerT(const PlayerT &o)
      : client_id(o.client_id),
        character((o.character) ? new fbs::CharacterT(*o.character) : nullptr) {
}

inline PlayerT &PlayerT::operator=(PlayerT o) FLATBUFFERS_NOEXCEPT {
  std::swap(client_id, o.client_id);
  std::swap(character, o.character);
  return *this;
}

inline PlayerT *Player::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<PlayerT>(new PlayerT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Player::UnPackTo(PlayerT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = client_id(); _o->client_id = _e; }
  { auto _e = character(); if (_e) { if(_o->character) { _e->UnPackTo(_o->character.get(), _resolver); } else { _o->character = std::unique_ptr<fbs::CharacterT>(_e->UnPack(_resolver)); } } else if (_o->character) { _o->character.reset(); } }
}

inline ::flatbuffers::Offset<Player> CreatePlayer(::flatbuffers::FlatBufferBuilder &_fbb, const PlayerT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Player::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Player> Player::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PlayerT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const PlayerT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _client_id = _o->client_id;
  auto _character = _o->character ? CreateCharacter(_fbb, _o->character.get(), _rehasher) : 0;
  return fbs::CreatePlayer(
      _fbb,
      _client_id,
      _character);
}

inline MovementT *Movement::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<MovementT>(new MovementT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Movement::UnPackTo(MovementT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x1(); _o->x1 = _e; }
  { auto _e = y1(); _o->y1 = _e; }
  { auto _e = x2(); _o->x2 = _e; }
  { auto _e = y2(); _o->y2 = _e; }
  { auto _e = time(); _o->time = _e; }
  { auto _e = fh(); _o->fh = _e; }
  { auto _e = action(); if (_e) _o->action = _e->str(); }
  { auto _e = flip(); _o->flip = _e; }
}

inline ::flatbuffers::Offset<Movement> CreateMovement(::flatbuffers::FlatBufferBuilder &_fbb, const MovementT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Movement::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Movement> Movement::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MovementT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const MovementT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x1 = _o->x1;
  auto _y1 = _o->y1;
  auto _x2 = _o->x2;
  auto _y2 = _o->y2;
  auto _time = _o->time;
  auto _fh = _o->fh;
  auto _action = _o->action.empty() ? 0 : _fbb.CreateString(_o->action);
  auto _flip = _o->flip;
  return fbs::CreateMovement(
      _fbb,
      _x1,
      _y1,
      _x2,
      _y2,
      _time,
      _fh,
      _action,
      _flip);
}

inline MobT::MobT(const MobT &o)
      : mob_id(o.mob_id),
        summon(o.summon),
        state((o.state) ? new fbs::LifeStateT(*o.state) : nullptr) {
}

inline MobT &MobT::operator=(MobT o) FLATBUFFERS_NOEXCEPT {
  std::swap(mob_id, o.mob_id);
  std::swap(summon, o.summon);
  std::swap(state, o.state);
  return *this;
}

inline MobT *Mob::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<MobT>(new MobT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Mob::UnPackTo(MobT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = mob_id(); _o->mob_id = _e; }
  { auto _e = summon(); _o->summon = _e; }
  { auto _e = state(); if (_e) { if(_o->state) { _e->UnPackTo(_o->state.get(), _resolver); } else { _o->state = std::unique_ptr<fbs::LifeStateT>(_e->UnPack(_resolver)); } } else if (_o->state) { _o->state.reset(); } }
}

inline ::flatbuffers::Offset<Mob> CreateMob(::flatbuffers::FlatBufferBuilder &_fbb, const MobT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Mob::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Mob> Mob::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MobT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const MobT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _mob_id = _o->mob_id;
  auto _summon = _o->summon;
  auto _state = _o->state ? CreateLifeState(_fbb, _o->state.get(), _rehasher) : 0;
  return fbs::CreateMob(
      _fbb,
      _mob_id,
      _summon,
      _state);
}

inline MobMovementT::MobMovementT(const MobMovementT &o)
      : mob_id(o.mob_id),
        movement((o.movement) ? new fbs::MovementT(*o.movement) : nullptr) {
}

inline MobMovementT &MobMovementT::operator=(MobMovementT o) FLATBUFFERS_NOEXCEPT {
  std::swap(mob_id, o.mob_id);
  std::swap(movement, o.movement);
  return *this;
}

inline MobMovementT *MobMovement::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<MobMovementT>(new MobMovementT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void MobMovement::UnPackTo(MobMovementT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = mob_id(); _o->mob_id = _e; }
  { auto _e = movement(); if (_e) { if(_o->movement) { _e->UnPackTo(_o->movement.get(), _resolver); } else { _o->movement = std::unique_ptr<fbs::MovementT>(_e->UnPack(_resolver)); } } else if (_o->movement) { _o->movement.reset(); } }
}

inline ::flatbuffers::Offset<MobMovement> CreateMobMovement(::flatbuffers::FlatBufferBuilder &_fbb, const MobMovementT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return MobMovement::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<MobMovement> MobMovement::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MobMovementT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const MobMovementT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _mob_id = _o->mob_id;
  auto _movement = _o->movement ? CreateMovement(_fbb, _o->movement.get(), _rehasher) : 0;
  return fbs::CreateMobMovement(
      _fbb,
      _mob_id,
      _movement);
}

inline DropEquipT *DropEquip::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<DropEquipT>(new DropEquipT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void DropEquip::UnPackTo(DropEquipT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = equip_id(); _o->equip_id = _e; }
  { auto _e = x(); _o->x = _e; }
  { auto _e = y(); _o->y = _e; }
  { auto _e = rotate(); _o->rotate = _e; }
  { auto _e = hspeed(); _o->hspeed = _e; }
  { auto _e = vspeed(); _o->vspeed = _e; }
}

inline ::flatbuffers::Offset<DropEquip> CreateDropEquip(::flatbuffers::FlatBufferBuilder &_fbb, const DropEquipT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return DropEquip::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<DropEquip> DropEquip::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DropEquipT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const DropEquipT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _equip_id = _o->equip_id;
  auto _x = _o->x;
  auto _y = _o->y;
  auto _rotate = _o->rotate;
  auto _hspeed = _o->hspeed;
  auto _vspeed = _o->vspeed;
  return fbs::CreateDropEquip(
      _fbb,
      _equip_id,
      _x,
      _y,
      _rotate,
      _hspeed,
      _vspeed);
}

inline DropItemT *DropItem::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<DropItemT>(new DropItemT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void DropItem::UnPackTo(DropItemT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = item_id(); _o->item_id = _e; }
  { auto _e = x(); _o->x = _e; }
  { auto _e = y(); _o->y = _e; }
  { auto _e = num(); _o->num = _e; }
  { auto _e = rotate(); _o->rotate = _e; }
  { auto _e = hspeed(); _o->hspeed = _e; }
  { auto _e = vspeed(); _o->vspeed = _e; }
}

inline ::flatbuffers::Offset<DropItem> CreateDropItem(::flatbuffers::FlatBufferBuilder &_fbb, const DropItemT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return DropItem::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<DropItem> DropItem::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DropItemT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const DropItemT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _item_id = _o->item_id;
  auto _x = _o->x;
  auto _y = _o->y;
  auto _num = _o->num;
  auto _rotate = _o->rotate;
  auto _hspeed = _o->hspeed;
  auto _vspeed = _o->vspeed;
  return fbs::CreateDropItem(
      _fbb,
      _item_id,
      _x,
      _y,
      _num,
      _rotate,
      _hspeed,
      _vspeed);
}

}  // namespace fbs

#endif  // FLATBUFFERS_GENERATED_COMMON_FBS_H_
