// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMMON_FBS_H_
#define FLATBUFFERS_GENERATED_COMMON_FBS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace fbs {

struct LifeState;
struct LifeStateBuilder;
struct LifeStateT;

struct CharacterAppearance;
struct CharacterAppearanceBuilder;
struct CharacterAppearanceT;

struct Character;
struct CharacterBuilder;
struct CharacterT;

struct Movement;
struct MovementBuilder;
struct MovementT;

struct Flip;
struct FlipBuilder;
struct FlipT;

struct Action;
struct ActionBuilder;
struct ActionT;

struct Attack;
struct AttackBuilder;
struct AttackT;

struct CharacterAttack;
struct CharacterAttackBuilder;
struct CharacterAttackT;

struct CharacterSkill;
struct CharacterSkillBuilder;
struct CharacterSkillT;

struct Player;
struct PlayerBuilder;
struct PlayerT;

struct Mob;
struct MobBuilder;
struct MobT;

struct CharacterLogic;
struct CharacterLogicBuilder;
struct CharacterLogicT;

struct MobLogic;
struct MobLogicBuilder;
struct MobLogicT;

enum CharacterLogicType : uint8_t {
  CharacterLogicType_NONE = 0,
  CharacterLogicType_Movement = 1,
  CharacterLogicType_Flip = 2,
  CharacterLogicType_Action = 3,
  CharacterLogicType_MIN = CharacterLogicType_NONE,
  CharacterLogicType_MAX = CharacterLogicType_Action
};

inline const CharacterLogicType (&EnumValuesCharacterLogicType())[4] {
  static const CharacterLogicType values[] = {
    CharacterLogicType_NONE,
    CharacterLogicType_Movement,
    CharacterLogicType_Flip,
    CharacterLogicType_Action
  };
  return values;
}

inline const char * const *EnumNamesCharacterLogicType() {
  static const char * const names[5] = {
    "NONE",
    "Movement",
    "Flip",
    "Action",
    nullptr
  };
  return names;
}

inline const char *EnumNameCharacterLogicType(CharacterLogicType e) {
  if (::flatbuffers::IsOutRange(e, CharacterLogicType_NONE, CharacterLogicType_Action)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCharacterLogicType()[index];
}

template<typename T> struct CharacterLogicTypeTraits {
  static const CharacterLogicType enum_value = CharacterLogicType_NONE;
};

template<> struct CharacterLogicTypeTraits<fbs::Movement> {
  static const CharacterLogicType enum_value = CharacterLogicType_Movement;
};

template<> struct CharacterLogicTypeTraits<fbs::Flip> {
  static const CharacterLogicType enum_value = CharacterLogicType_Flip;
};

template<> struct CharacterLogicTypeTraits<fbs::Action> {
  static const CharacterLogicType enum_value = CharacterLogicType_Action;
};

template<typename T> struct CharacterLogicTypeUnionTraits {
  static const CharacterLogicType enum_value = CharacterLogicType_NONE;
};

template<> struct CharacterLogicTypeUnionTraits<fbs::MovementT> {
  static const CharacterLogicType enum_value = CharacterLogicType_Movement;
};

template<> struct CharacterLogicTypeUnionTraits<fbs::FlipT> {
  static const CharacterLogicType enum_value = CharacterLogicType_Flip;
};

template<> struct CharacterLogicTypeUnionTraits<fbs::ActionT> {
  static const CharacterLogicType enum_value = CharacterLogicType_Action;
};

struct CharacterLogicTypeUnion {
  CharacterLogicType type;
  void *value;

  CharacterLogicTypeUnion() : type(CharacterLogicType_NONE), value(nullptr) {}
  CharacterLogicTypeUnion(CharacterLogicTypeUnion&& u) FLATBUFFERS_NOEXCEPT :
    type(CharacterLogicType_NONE), value(nullptr)
    { std::swap(type, u.type); std::swap(value, u.value); }
  CharacterLogicTypeUnion(const CharacterLogicTypeUnion &);
  CharacterLogicTypeUnion &operator=(const CharacterLogicTypeUnion &u)
    { CharacterLogicTypeUnion t(u); std::swap(type, t.type); std::swap(value, t.value); return *this; }
  CharacterLogicTypeUnion &operator=(CharacterLogicTypeUnion &&u) FLATBUFFERS_NOEXCEPT
    { std::swap(type, u.type); std::swap(value, u.value); return *this; }
  ~CharacterLogicTypeUnion() { Reset(); }

  void Reset();

  template <typename T>
  void Set(T&& val) {
    typedef typename std::remove_reference<T>::type RT;
    Reset();
    type = CharacterLogicTypeUnionTraits<RT>::enum_value;
    if (type != CharacterLogicType_NONE) {
      value = new RT(std::forward<T>(val));
    }
  }

  static void *UnPack(const void *obj, CharacterLogicType type, const ::flatbuffers::resolver_function_t *resolver);
  ::flatbuffers::Offset<void> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr) const;

  fbs::MovementT *AsMovement() {
    return type == CharacterLogicType_Movement ?
      reinterpret_cast<fbs::MovementT *>(value) : nullptr;
  }
  const fbs::MovementT *AsMovement() const {
    return type == CharacterLogicType_Movement ?
      reinterpret_cast<const fbs::MovementT *>(value) : nullptr;
  }
  fbs::FlipT *AsFlip() {
    return type == CharacterLogicType_Flip ?
      reinterpret_cast<fbs::FlipT *>(value) : nullptr;
  }
  const fbs::FlipT *AsFlip() const {
    return type == CharacterLogicType_Flip ?
      reinterpret_cast<const fbs::FlipT *>(value) : nullptr;
  }
  fbs::ActionT *AsAction() {
    return type == CharacterLogicType_Action ?
      reinterpret_cast<fbs::ActionT *>(value) : nullptr;
  }
  const fbs::ActionT *AsAction() const {
    return type == CharacterLogicType_Action ?
      reinterpret_cast<const fbs::ActionT *>(value) : nullptr;
  }
};

template <bool B = false>
bool VerifyCharacterLogicType(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, CharacterLogicType type);
template <bool B = false>
bool VerifyCharacterLogicTypeVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

enum MobLogicType : uint8_t {
  MobLogicType_NONE = 0,
  MobLogicType_Movement = 1,
  MobLogicType_Flip = 2,
  MobLogicType_Action = 3,
  MobLogicType_MIN = MobLogicType_NONE,
  MobLogicType_MAX = MobLogicType_Action
};

inline const MobLogicType (&EnumValuesMobLogicType())[4] {
  static const MobLogicType values[] = {
    MobLogicType_NONE,
    MobLogicType_Movement,
    MobLogicType_Flip,
    MobLogicType_Action
  };
  return values;
}

inline const char * const *EnumNamesMobLogicType() {
  static const char * const names[5] = {
    "NONE",
    "Movement",
    "Flip",
    "Action",
    nullptr
  };
  return names;
}

inline const char *EnumNameMobLogicType(MobLogicType e) {
  if (::flatbuffers::IsOutRange(e, MobLogicType_NONE, MobLogicType_Action)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMobLogicType()[index];
}

template<typename T> struct MobLogicTypeTraits {
  static const MobLogicType enum_value = MobLogicType_NONE;
};

template<> struct MobLogicTypeTraits<fbs::Movement> {
  static const MobLogicType enum_value = MobLogicType_Movement;
};

template<> struct MobLogicTypeTraits<fbs::Flip> {
  static const MobLogicType enum_value = MobLogicType_Flip;
};

template<> struct MobLogicTypeTraits<fbs::Action> {
  static const MobLogicType enum_value = MobLogicType_Action;
};

template<typename T> struct MobLogicTypeUnionTraits {
  static const MobLogicType enum_value = MobLogicType_NONE;
};

template<> struct MobLogicTypeUnionTraits<fbs::MovementT> {
  static const MobLogicType enum_value = MobLogicType_Movement;
};

template<> struct MobLogicTypeUnionTraits<fbs::FlipT> {
  static const MobLogicType enum_value = MobLogicType_Flip;
};

template<> struct MobLogicTypeUnionTraits<fbs::ActionT> {
  static const MobLogicType enum_value = MobLogicType_Action;
};

struct MobLogicTypeUnion {
  MobLogicType type;
  void *value;

  MobLogicTypeUnion() : type(MobLogicType_NONE), value(nullptr) {}
  MobLogicTypeUnion(MobLogicTypeUnion&& u) FLATBUFFERS_NOEXCEPT :
    type(MobLogicType_NONE), value(nullptr)
    { std::swap(type, u.type); std::swap(value, u.value); }
  MobLogicTypeUnion(const MobLogicTypeUnion &);
  MobLogicTypeUnion &operator=(const MobLogicTypeUnion &u)
    { MobLogicTypeUnion t(u); std::swap(type, t.type); std::swap(value, t.value); return *this; }
  MobLogicTypeUnion &operator=(MobLogicTypeUnion &&u) FLATBUFFERS_NOEXCEPT
    { std::swap(type, u.type); std::swap(value, u.value); return *this; }
  ~MobLogicTypeUnion() { Reset(); }

  void Reset();

  template <typename T>
  void Set(T&& val) {
    typedef typename std::remove_reference<T>::type RT;
    Reset();
    type = MobLogicTypeUnionTraits<RT>::enum_value;
    if (type != MobLogicType_NONE) {
      value = new RT(std::forward<T>(val));
    }
  }

  static void *UnPack(const void *obj, MobLogicType type, const ::flatbuffers::resolver_function_t *resolver);
  ::flatbuffers::Offset<void> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr) const;

  fbs::MovementT *AsMovement() {
    return type == MobLogicType_Movement ?
      reinterpret_cast<fbs::MovementT *>(value) : nullptr;
  }
  const fbs::MovementT *AsMovement() const {
    return type == MobLogicType_Movement ?
      reinterpret_cast<const fbs::MovementT *>(value) : nullptr;
  }
  fbs::FlipT *AsFlip() {
    return type == MobLogicType_Flip ?
      reinterpret_cast<fbs::FlipT *>(value) : nullptr;
  }
  const fbs::FlipT *AsFlip() const {
    return type == MobLogicType_Flip ?
      reinterpret_cast<const fbs::FlipT *>(value) : nullptr;
  }
  fbs::ActionT *AsAction() {
    return type == MobLogicType_Action ?
      reinterpret_cast<fbs::ActionT *>(value) : nullptr;
  }
  const fbs::ActionT *AsAction() const {
    return type == MobLogicType_Action ?
      reinterpret_cast<const fbs::ActionT *>(value) : nullptr;
  }
};

template <bool B = false>
bool VerifyMobLogicType(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, MobLogicType type);
template <bool B = false>
bool VerifyMobLogicTypeVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct LifeStateT : public ::flatbuffers::NativeTable {
  typedef LifeState TableType;
  float x = 0.0f;
  float y = 0.0f;
  std::string action{};
  uint8_t action_index = 0;
  bool action_animate = false;
  uint8_t page = 0;
  bool flip = false;
};

struct LifeState FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LifeStateT NativeTableType;
  typedef LifeStateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_ACTION = 8,
    VT_ACTION_INDEX = 10,
    VT_ACTION_ANIMATE = 12,
    VT_PAGE = 14,
    VT_FLIP = 16
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  bool mutate_x(float _x = 0.0f) {
    return SetField<float>(VT_X, _x, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  bool mutate_y(float _y = 0.0f) {
    return SetField<float>(VT_Y, _y, 0.0f);
  }
  const ::flatbuffers::String *action() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ACTION);
  }
  ::flatbuffers::String *mutable_action() {
    return GetPointer<::flatbuffers::String *>(VT_ACTION);
  }
  uint8_t action_index() const {
    return GetField<uint8_t>(VT_ACTION_INDEX, 0);
  }
  bool mutate_action_index(uint8_t _action_index = 0) {
    return SetField<uint8_t>(VT_ACTION_INDEX, _action_index, 0);
  }
  bool action_animate() const {
    return GetField<uint8_t>(VT_ACTION_ANIMATE, 0) != 0;
  }
  bool mutate_action_animate(bool _action_animate = 0) {
    return SetField<uint8_t>(VT_ACTION_ANIMATE, static_cast<uint8_t>(_action_animate), 0);
  }
  uint8_t page() const {
    return GetField<uint8_t>(VT_PAGE, 0);
  }
  bool mutate_page(uint8_t _page = 0) {
    return SetField<uint8_t>(VT_PAGE, _page, 0);
  }
  bool flip() const {
    return GetField<uint8_t>(VT_FLIP, 0) != 0;
  }
  bool mutate_flip(bool _flip = 0) {
    return SetField<uint8_t>(VT_FLIP, static_cast<uint8_t>(_flip), 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyOffset(verifier, VT_ACTION) &&
           verifier.VerifyString(action()) &&
           VerifyField<uint8_t>(verifier, VT_ACTION_INDEX, 1) &&
           VerifyField<uint8_t>(verifier, VT_ACTION_ANIMATE, 1) &&
           VerifyField<uint8_t>(verifier, VT_PAGE, 1) &&
           VerifyField<uint8_t>(verifier, VT_FLIP, 1) &&
           verifier.EndTable();
  }
  LifeStateT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(LifeStateT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<LifeState> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const LifeStateT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct LifeStateBuilder {
  typedef LifeState Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(LifeState::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(LifeState::VT_Y, y, 0.0f);
  }
  void add_action(::flatbuffers::Offset<::flatbuffers::String> action) {
    fbb_.AddOffset(LifeState::VT_ACTION, action);
  }
  void add_action_index(uint8_t action_index) {
    fbb_.AddElement<uint8_t>(LifeState::VT_ACTION_INDEX, action_index, 0);
  }
  void add_action_animate(bool action_animate) {
    fbb_.AddElement<uint8_t>(LifeState::VT_ACTION_ANIMATE, static_cast<uint8_t>(action_animate), 0);
  }
  void add_page(uint8_t page) {
    fbb_.AddElement<uint8_t>(LifeState::VT_PAGE, page, 0);
  }
  void add_flip(bool flip) {
    fbb_.AddElement<uint8_t>(LifeState::VT_FLIP, static_cast<uint8_t>(flip), 0);
  }
  explicit LifeStateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LifeState> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LifeState>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LifeState> CreateLifeState(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    ::flatbuffers::Offset<::flatbuffers::String> action = 0,
    uint8_t action_index = 0,
    bool action_animate = false,
    uint8_t page = 0,
    bool flip = false) {
  LifeStateBuilder builder_(_fbb);
  builder_.add_action(action);
  builder_.add_y(y);
  builder_.add_x(x);
  builder_.add_flip(flip);
  builder_.add_page(page);
  builder_.add_action_animate(action_animate);
  builder_.add_action_index(action_index);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<LifeState> CreateLifeStateDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    const char *action = nullptr,
    uint8_t action_index = 0,
    bool action_animate = false,
    uint8_t page = 0,
    bool flip = false) {
  auto action__ = action ? _fbb.CreateString(action) : 0;
  return fbs::CreateLifeState(
      _fbb,
      x,
      y,
      action__,
      action_index,
      action_animate,
      page,
      flip);
}

::flatbuffers::Offset<LifeState> CreateLifeState(::flatbuffers::FlatBufferBuilder &_fbb, const LifeStateT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CharacterAppearanceT : public ::flatbuffers::NativeTable {
  typedef CharacterAppearance TableType;
  uint32_t body = 0;
  uint32_t head = 0;
  uint32_t face = 0;
  uint32_t hair = 0;
  uint32_t weapon = 0;
  uint32_t cap = 0;
  uint32_t cape = 0;
  uint32_t coat = 0;
  uint32_t glove = 0;
  uint32_t pant = 0;
  uint32_t shield = 0;
  uint32_t longcoat = 0;
  uint32_t shoes = 0;
  uint32_t accessory = 0;
};

struct CharacterAppearance FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CharacterAppearanceT NativeTableType;
  typedef CharacterAppearanceBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BODY = 4,
    VT_HEAD = 6,
    VT_FACE = 8,
    VT_HAIR = 10,
    VT_WEAPON = 12,
    VT_CAP = 14,
    VT_CAPE = 16,
    VT_COAT = 18,
    VT_GLOVE = 20,
    VT_PANT = 22,
    VT_SHIELD = 24,
    VT_LONGCOAT = 26,
    VT_SHOES = 28,
    VT_ACCESSORY = 30
  };
  uint32_t body() const {
    return GetField<uint32_t>(VT_BODY, 0);
  }
  bool mutate_body(uint32_t _body = 0) {
    return SetField<uint32_t>(VT_BODY, _body, 0);
  }
  uint32_t head() const {
    return GetField<uint32_t>(VT_HEAD, 0);
  }
  bool mutate_head(uint32_t _head = 0) {
    return SetField<uint32_t>(VT_HEAD, _head, 0);
  }
  uint32_t face() const {
    return GetField<uint32_t>(VT_FACE, 0);
  }
  bool mutate_face(uint32_t _face = 0) {
    return SetField<uint32_t>(VT_FACE, _face, 0);
  }
  uint32_t hair() const {
    return GetField<uint32_t>(VT_HAIR, 0);
  }
  bool mutate_hair(uint32_t _hair = 0) {
    return SetField<uint32_t>(VT_HAIR, _hair, 0);
  }
  uint32_t weapon() const {
    return GetField<uint32_t>(VT_WEAPON, 0);
  }
  bool mutate_weapon(uint32_t _weapon = 0) {
    return SetField<uint32_t>(VT_WEAPON, _weapon, 0);
  }
  uint32_t cap() const {
    return GetField<uint32_t>(VT_CAP, 0);
  }
  bool mutate_cap(uint32_t _cap = 0) {
    return SetField<uint32_t>(VT_CAP, _cap, 0);
  }
  uint32_t cape() const {
    return GetField<uint32_t>(VT_CAPE, 0);
  }
  bool mutate_cape(uint32_t _cape = 0) {
    return SetField<uint32_t>(VT_CAPE, _cape, 0);
  }
  uint32_t coat() const {
    return GetField<uint32_t>(VT_COAT, 0);
  }
  bool mutate_coat(uint32_t _coat = 0) {
    return SetField<uint32_t>(VT_COAT, _coat, 0);
  }
  uint32_t glove() const {
    return GetField<uint32_t>(VT_GLOVE, 0);
  }
  bool mutate_glove(uint32_t _glove = 0) {
    return SetField<uint32_t>(VT_GLOVE, _glove, 0);
  }
  uint32_t pant() const {
    return GetField<uint32_t>(VT_PANT, 0);
  }
  bool mutate_pant(uint32_t _pant = 0) {
    return SetField<uint32_t>(VT_PANT, _pant, 0);
  }
  uint32_t shield() const {
    return GetField<uint32_t>(VT_SHIELD, 0);
  }
  bool mutate_shield(uint32_t _shield = 0) {
    return SetField<uint32_t>(VT_SHIELD, _shield, 0);
  }
  uint32_t longcoat() const {
    return GetField<uint32_t>(VT_LONGCOAT, 0);
  }
  bool mutate_longcoat(uint32_t _longcoat = 0) {
    return SetField<uint32_t>(VT_LONGCOAT, _longcoat, 0);
  }
  uint32_t shoes() const {
    return GetField<uint32_t>(VT_SHOES, 0);
  }
  bool mutate_shoes(uint32_t _shoes = 0) {
    return SetField<uint32_t>(VT_SHOES, _shoes, 0);
  }
  uint32_t accessory() const {
    return GetField<uint32_t>(VT_ACCESSORY, 0);
  }
  bool mutate_accessory(uint32_t _accessory = 0) {
    return SetField<uint32_t>(VT_ACCESSORY, _accessory, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_BODY, 4) &&
           VerifyField<uint32_t>(verifier, VT_HEAD, 4) &&
           VerifyField<uint32_t>(verifier, VT_FACE, 4) &&
           VerifyField<uint32_t>(verifier, VT_HAIR, 4) &&
           VerifyField<uint32_t>(verifier, VT_WEAPON, 4) &&
           VerifyField<uint32_t>(verifier, VT_CAP, 4) &&
           VerifyField<uint32_t>(verifier, VT_CAPE, 4) &&
           VerifyField<uint32_t>(verifier, VT_COAT, 4) &&
           VerifyField<uint32_t>(verifier, VT_GLOVE, 4) &&
           VerifyField<uint32_t>(verifier, VT_PANT, 4) &&
           VerifyField<uint32_t>(verifier, VT_SHIELD, 4) &&
           VerifyField<uint32_t>(verifier, VT_LONGCOAT, 4) &&
           VerifyField<uint32_t>(verifier, VT_SHOES, 4) &&
           VerifyField<uint32_t>(verifier, VT_ACCESSORY, 4) &&
           verifier.EndTable();
  }
  CharacterAppearanceT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CharacterAppearanceT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CharacterAppearance> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterAppearanceT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CharacterAppearanceBuilder {
  typedef CharacterAppearance Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_body(uint32_t body) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_BODY, body, 0);
  }
  void add_head(uint32_t head) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_HEAD, head, 0);
  }
  void add_face(uint32_t face) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_FACE, face, 0);
  }
  void add_hair(uint32_t hair) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_HAIR, hair, 0);
  }
  void add_weapon(uint32_t weapon) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_WEAPON, weapon, 0);
  }
  void add_cap(uint32_t cap) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_CAP, cap, 0);
  }
  void add_cape(uint32_t cape) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_CAPE, cape, 0);
  }
  void add_coat(uint32_t coat) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_COAT, coat, 0);
  }
  void add_glove(uint32_t glove) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_GLOVE, glove, 0);
  }
  void add_pant(uint32_t pant) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_PANT, pant, 0);
  }
  void add_shield(uint32_t shield) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_SHIELD, shield, 0);
  }
  void add_longcoat(uint32_t longcoat) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_LONGCOAT, longcoat, 0);
  }
  void add_shoes(uint32_t shoes) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_SHOES, shoes, 0);
  }
  void add_accessory(uint32_t accessory) {
    fbb_.AddElement<uint32_t>(CharacterAppearance::VT_ACCESSORY, accessory, 0);
  }
  explicit CharacterAppearanceBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CharacterAppearance> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CharacterAppearance>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CharacterAppearance> CreateCharacterAppearance(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t body = 0,
    uint32_t head = 0,
    uint32_t face = 0,
    uint32_t hair = 0,
    uint32_t weapon = 0,
    uint32_t cap = 0,
    uint32_t cape = 0,
    uint32_t coat = 0,
    uint32_t glove = 0,
    uint32_t pant = 0,
    uint32_t shield = 0,
    uint32_t longcoat = 0,
    uint32_t shoes = 0,
    uint32_t accessory = 0) {
  CharacterAppearanceBuilder builder_(_fbb);
  builder_.add_accessory(accessory);
  builder_.add_shoes(shoes);
  builder_.add_longcoat(longcoat);
  builder_.add_shield(shield);
  builder_.add_pant(pant);
  builder_.add_glove(glove);
  builder_.add_coat(coat);
  builder_.add_cape(cape);
  builder_.add_cap(cap);
  builder_.add_weapon(weapon);
  builder_.add_hair(hair);
  builder_.add_face(face);
  builder_.add_head(head);
  builder_.add_body(body);
  return builder_.Finish();
}

::flatbuffers::Offset<CharacterAppearance> CreateCharacterAppearance(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterAppearanceT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CharacterT : public ::flatbuffers::NativeTable {
  typedef Character TableType;
  std::string name{};
  std::unique_ptr<fbs::LifeStateT> state{};
  std::unique_ptr<fbs::CharacterAppearanceT> appearance{};
  CharacterT() = default;
  CharacterT(const CharacterT &o);
  CharacterT(CharacterT&&) FLATBUFFERS_NOEXCEPT = default;
  CharacterT &operator=(CharacterT o) FLATBUFFERS_NOEXCEPT;
};

struct Character FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CharacterT NativeTableType;
  typedef CharacterBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_STATE = 6,
    VT_APPEARANCE = 8
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  ::flatbuffers::String *mutable_name() {
    return GetPointer<::flatbuffers::String *>(VT_NAME);
  }
  const fbs::LifeState *state() const {
    return GetPointer<const fbs::LifeState *>(VT_STATE);
  }
  fbs::LifeState *mutable_state() {
    return GetPointer<fbs::LifeState *>(VT_STATE);
  }
  const fbs::CharacterAppearance *appearance() const {
    return GetPointer<const fbs::CharacterAppearance *>(VT_APPEARANCE);
  }
  fbs::CharacterAppearance *mutable_appearance() {
    return GetPointer<fbs::CharacterAppearance *>(VT_APPEARANCE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_STATE) &&
           verifier.VerifyTable(state()) &&
           VerifyOffset(verifier, VT_APPEARANCE) &&
           verifier.VerifyTable(appearance()) &&
           verifier.EndTable();
  }
  CharacterT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CharacterT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Character> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CharacterBuilder {
  typedef Character Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Character::VT_NAME, name);
  }
  void add_state(::flatbuffers::Offset<fbs::LifeState> state) {
    fbb_.AddOffset(Character::VT_STATE, state);
  }
  void add_appearance(::flatbuffers::Offset<fbs::CharacterAppearance> appearance) {
    fbb_.AddOffset(Character::VT_APPEARANCE, appearance);
  }
  explicit CharacterBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Character> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Character>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Character> CreateCharacter(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<fbs::LifeState> state = 0,
    ::flatbuffers::Offset<fbs::CharacterAppearance> appearance = 0) {
  CharacterBuilder builder_(_fbb);
  builder_.add_appearance(appearance);
  builder_.add_state(state);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Character> CreateCharacterDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    ::flatbuffers::Offset<fbs::LifeState> state = 0,
    ::flatbuffers::Offset<fbs::CharacterAppearance> appearance = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return fbs::CreateCharacter(
      _fbb,
      name__,
      state,
      appearance);
}

::flatbuffers::Offset<Character> CreateCharacter(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct MovementT : public ::flatbuffers::NativeTable {
  typedef Movement TableType;
  float x1 = 0.0f;
  float y1 = 0.0f;
  float x2 = 0.0f;
  float y2 = 0.0f;
  uint32_t time = 0;
  uint8_t page = 0;
};

struct Movement FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MovementT NativeTableType;
  typedef MovementBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X1 = 4,
    VT_Y1 = 6,
    VT_X2 = 8,
    VT_Y2 = 10,
    VT_TIME = 12,
    VT_PAGE = 14
  };
  float x1() const {
    return GetField<float>(VT_X1, 0.0f);
  }
  bool mutate_x1(float _x1 = 0.0f) {
    return SetField<float>(VT_X1, _x1, 0.0f);
  }
  float y1() const {
    return GetField<float>(VT_Y1, 0.0f);
  }
  bool mutate_y1(float _y1 = 0.0f) {
    return SetField<float>(VT_Y1, _y1, 0.0f);
  }
  float x2() const {
    return GetField<float>(VT_X2, 0.0f);
  }
  bool mutate_x2(float _x2 = 0.0f) {
    return SetField<float>(VT_X2, _x2, 0.0f);
  }
  float y2() const {
    return GetField<float>(VT_Y2, 0.0f);
  }
  bool mutate_y2(float _y2 = 0.0f) {
    return SetField<float>(VT_Y2, _y2, 0.0f);
  }
  uint32_t time() const {
    return GetField<uint32_t>(VT_TIME, 0);
  }
  bool mutate_time(uint32_t _time = 0) {
    return SetField<uint32_t>(VT_TIME, _time, 0);
  }
  uint8_t page() const {
    return GetField<uint8_t>(VT_PAGE, 0);
  }
  bool mutate_page(uint8_t _page = 0) {
    return SetField<uint8_t>(VT_PAGE, _page, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X1, 4) &&
           VerifyField<float>(verifier, VT_Y1, 4) &&
           VerifyField<float>(verifier, VT_X2, 4) &&
           VerifyField<float>(verifier, VT_Y2, 4) &&
           VerifyField<uint32_t>(verifier, VT_TIME, 4) &&
           VerifyField<uint8_t>(verifier, VT_PAGE, 1) &&
           verifier.EndTable();
  }
  MovementT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(MovementT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Movement> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MovementT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct MovementBuilder {
  typedef Movement Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x1(float x1) {
    fbb_.AddElement<float>(Movement::VT_X1, x1, 0.0f);
  }
  void add_y1(float y1) {
    fbb_.AddElement<float>(Movement::VT_Y1, y1, 0.0f);
  }
  void add_x2(float x2) {
    fbb_.AddElement<float>(Movement::VT_X2, x2, 0.0f);
  }
  void add_y2(float y2) {
    fbb_.AddElement<float>(Movement::VT_Y2, y2, 0.0f);
  }
  void add_time(uint32_t time) {
    fbb_.AddElement<uint32_t>(Movement::VT_TIME, time, 0);
  }
  void add_page(uint8_t page) {
    fbb_.AddElement<uint8_t>(Movement::VT_PAGE, page, 0);
  }
  explicit MovementBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Movement> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Movement>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Movement> CreateMovement(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x1 = 0.0f,
    float y1 = 0.0f,
    float x2 = 0.0f,
    float y2 = 0.0f,
    uint32_t time = 0,
    uint8_t page = 0) {
  MovementBuilder builder_(_fbb);
  builder_.add_time(time);
  builder_.add_y2(y2);
  builder_.add_x2(x2);
  builder_.add_y1(y1);
  builder_.add_x1(x1);
  builder_.add_page(page);
  return builder_.Finish();
}

::flatbuffers::Offset<Movement> CreateMovement(::flatbuffers::FlatBufferBuilder &_fbb, const MovementT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct FlipT : public ::flatbuffers::NativeTable {
  typedef Flip TableType;
  bool flip = false;
};

struct Flip FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FlipT NativeTableType;
  typedef FlipBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FLIP = 4
  };
  bool flip() const {
    return GetField<uint8_t>(VT_FLIP, 0) != 0;
  }
  bool mutate_flip(bool _flip = 0) {
    return SetField<uint8_t>(VT_FLIP, static_cast<uint8_t>(_flip), 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_FLIP, 1) &&
           verifier.EndTable();
  }
  FlipT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(FlipT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Flip> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const FlipT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct FlipBuilder {
  typedef Flip Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_flip(bool flip) {
    fbb_.AddElement<uint8_t>(Flip::VT_FLIP, static_cast<uint8_t>(flip), 0);
  }
  explicit FlipBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Flip> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Flip>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Flip> CreateFlip(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool flip = false) {
  FlipBuilder builder_(_fbb);
  builder_.add_flip(flip);
  return builder_.Finish();
}

::flatbuffers::Offset<Flip> CreateFlip(::flatbuffers::FlatBufferBuilder &_fbb, const FlipT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ActionT : public ::flatbuffers::NativeTable {
  typedef Action TableType;
  std::string action{};
  uint8_t action_index = 0;
  bool action_animate = false;
};

struct Action FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ActionT NativeTableType;
  typedef ActionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ACTION = 4,
    VT_ACTION_INDEX = 6,
    VT_ACTION_ANIMATE = 8
  };
  const ::flatbuffers::String *action() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ACTION);
  }
  ::flatbuffers::String *mutable_action() {
    return GetPointer<::flatbuffers::String *>(VT_ACTION);
  }
  uint8_t action_index() const {
    return GetField<uint8_t>(VT_ACTION_INDEX, 0);
  }
  bool mutate_action_index(uint8_t _action_index = 0) {
    return SetField<uint8_t>(VT_ACTION_INDEX, _action_index, 0);
  }
  bool action_animate() const {
    return GetField<uint8_t>(VT_ACTION_ANIMATE, 0) != 0;
  }
  bool mutate_action_animate(bool _action_animate = 0) {
    return SetField<uint8_t>(VT_ACTION_ANIMATE, static_cast<uint8_t>(_action_animate), 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ACTION) &&
           verifier.VerifyString(action()) &&
           VerifyField<uint8_t>(verifier, VT_ACTION_INDEX, 1) &&
           VerifyField<uint8_t>(verifier, VT_ACTION_ANIMATE, 1) &&
           verifier.EndTable();
  }
  ActionT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ActionT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Action> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ActionT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ActionBuilder {
  typedef Action Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_action(::flatbuffers::Offset<::flatbuffers::String> action) {
    fbb_.AddOffset(Action::VT_ACTION, action);
  }
  void add_action_index(uint8_t action_index) {
    fbb_.AddElement<uint8_t>(Action::VT_ACTION_INDEX, action_index, 0);
  }
  void add_action_animate(bool action_animate) {
    fbb_.AddElement<uint8_t>(Action::VT_ACTION_ANIMATE, static_cast<uint8_t>(action_animate), 0);
  }
  explicit ActionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Action> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Action>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Action> CreateAction(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> action = 0,
    uint8_t action_index = 0,
    bool action_animate = false) {
  ActionBuilder builder_(_fbb);
  builder_.add_action(action);
  builder_.add_action_animate(action_animate);
  builder_.add_action_index(action_index);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Action> CreateActionDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *action = nullptr,
    uint8_t action_index = 0,
    bool action_animate = false) {
  auto action__ = action ? _fbb.CreateString(action) : 0;
  return fbs::CreateAction(
      _fbb,
      action__,
      action_index,
      action_animate);
}

::flatbuffers::Offset<Action> CreateAction(::flatbuffers::FlatBufferBuilder &_fbb, const ActionT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct AttackT : public ::flatbuffers::NativeTable {
  typedef Attack TableType;
  uint64_t time = 0;
  uint64_t num = 0;
};

struct Attack FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AttackT NativeTableType;
  typedef AttackBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIME = 4,
    VT_NUM = 6
  };
  uint64_t time() const {
    return GetField<uint64_t>(VT_TIME, 0);
  }
  bool mutate_time(uint64_t _time = 0) {
    return SetField<uint64_t>(VT_TIME, _time, 0);
  }
  uint64_t num() const {
    return GetField<uint64_t>(VT_NUM, 0);
  }
  bool mutate_num(uint64_t _num = 0) {
    return SetField<uint64_t>(VT_NUM, _num, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TIME, 8) &&
           VerifyField<uint64_t>(verifier, VT_NUM, 8) &&
           verifier.EndTable();
  }
  AttackT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(AttackT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Attack> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const AttackT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct AttackBuilder {
  typedef Attack Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_time(uint64_t time) {
    fbb_.AddElement<uint64_t>(Attack::VT_TIME, time, 0);
  }
  void add_num(uint64_t num) {
    fbb_.AddElement<uint64_t>(Attack::VT_NUM, num, 0);
  }
  explicit AttackBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Attack> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Attack>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Attack> CreateAttack(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t time = 0,
    uint64_t num = 0) {
  AttackBuilder builder_(_fbb);
  builder_.add_num(num);
  builder_.add_time(time);
  return builder_.Finish();
}

::flatbuffers::Offset<Attack> CreateAttack(::flatbuffers::FlatBufferBuilder &_fbb, const AttackT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CharacterAttackT : public ::flatbuffers::NativeTable {
  typedef CharacterAttack TableType;
  uint32_t mob_id = 0;
  std::unique_ptr<fbs::AttackT> attack{};
  bool afterimage = false;
  bool left = false;
  CharacterAttackT() = default;
  CharacterAttackT(const CharacterAttackT &o);
  CharacterAttackT(CharacterAttackT&&) FLATBUFFERS_NOEXCEPT = default;
  CharacterAttackT &operator=(CharacterAttackT o) FLATBUFFERS_NOEXCEPT;
};

struct CharacterAttack FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CharacterAttackT NativeTableType;
  typedef CharacterAttackBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MOB_ID = 4,
    VT_ATTACK = 6,
    VT_AFTERIMAGE = 8,
    VT_LEFT = 10
  };
  uint32_t mob_id() const {
    return GetField<uint32_t>(VT_MOB_ID, 0);
  }
  bool mutate_mob_id(uint32_t _mob_id = 0) {
    return SetField<uint32_t>(VT_MOB_ID, _mob_id, 0);
  }
  const fbs::Attack *attack() const {
    return GetPointer<const fbs::Attack *>(VT_ATTACK);
  }
  fbs::Attack *mutable_attack() {
    return GetPointer<fbs::Attack *>(VT_ATTACK);
  }
  bool afterimage() const {
    return GetField<uint8_t>(VT_AFTERIMAGE, 0) != 0;
  }
  bool mutate_afterimage(bool _afterimage = 0) {
    return SetField<uint8_t>(VT_AFTERIMAGE, static_cast<uint8_t>(_afterimage), 0);
  }
  bool left() const {
    return GetField<uint8_t>(VT_LEFT, 0) != 0;
  }
  bool mutate_left(bool _left = 0) {
    return SetField<uint8_t>(VT_LEFT, static_cast<uint8_t>(_left), 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_MOB_ID, 4) &&
           VerifyOffset(verifier, VT_ATTACK) &&
           verifier.VerifyTable(attack()) &&
           VerifyField<uint8_t>(verifier, VT_AFTERIMAGE, 1) &&
           VerifyField<uint8_t>(verifier, VT_LEFT, 1) &&
           verifier.EndTable();
  }
  CharacterAttackT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CharacterAttackT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CharacterAttack> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterAttackT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CharacterAttackBuilder {
  typedef CharacterAttack Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_mob_id(uint32_t mob_id) {
    fbb_.AddElement<uint32_t>(CharacterAttack::VT_MOB_ID, mob_id, 0);
  }
  void add_attack(::flatbuffers::Offset<fbs::Attack> attack) {
    fbb_.AddOffset(CharacterAttack::VT_ATTACK, attack);
  }
  void add_afterimage(bool afterimage) {
    fbb_.AddElement<uint8_t>(CharacterAttack::VT_AFTERIMAGE, static_cast<uint8_t>(afterimage), 0);
  }
  void add_left(bool left) {
    fbb_.AddElement<uint8_t>(CharacterAttack::VT_LEFT, static_cast<uint8_t>(left), 0);
  }
  explicit CharacterAttackBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CharacterAttack> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CharacterAttack>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CharacterAttack> CreateCharacterAttack(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t mob_id = 0,
    ::flatbuffers::Offset<fbs::Attack> attack = 0,
    bool afterimage = false,
    bool left = false) {
  CharacterAttackBuilder builder_(_fbb);
  builder_.add_attack(attack);
  builder_.add_mob_id(mob_id);
  builder_.add_left(left);
  builder_.add_afterimage(afterimage);
  return builder_.Finish();
}

::flatbuffers::Offset<CharacterAttack> CreateCharacterAttack(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterAttackT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CharacterSkillT : public ::flatbuffers::NativeTable {
  typedef CharacterSkill TableType;
  uint32_t ski_id = 0;
  uint64_t time = 0;
  std::vector<uint32_t> mobs{};
  std::vector<uint64_t> players{};
};

struct CharacterSkill FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CharacterSkillT NativeTableType;
  typedef CharacterSkillBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SKI_ID = 4,
    VT_TIME = 6,
    VT_MOBS = 8,
    VT_PLAYERS = 10
  };
  uint32_t ski_id() const {
    return GetField<uint32_t>(VT_SKI_ID, 0);
  }
  bool mutate_ski_id(uint32_t _ski_id = 0) {
    return SetField<uint32_t>(VT_SKI_ID, _ski_id, 0);
  }
  uint64_t time() const {
    return GetField<uint64_t>(VT_TIME, 0);
  }
  bool mutate_time(uint64_t _time = 0) {
    return SetField<uint64_t>(VT_TIME, _time, 0);
  }
  const ::flatbuffers::Vector<uint32_t> *mobs() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_MOBS);
  }
  ::flatbuffers::Vector<uint32_t> *mutable_mobs() {
    return GetPointer<::flatbuffers::Vector<uint32_t> *>(VT_MOBS);
  }
  const ::flatbuffers::Vector<uint64_t> *players() const {
    return GetPointer<const ::flatbuffers::Vector<uint64_t> *>(VT_PLAYERS);
  }
  ::flatbuffers::Vector<uint64_t> *mutable_players() {
    return GetPointer<::flatbuffers::Vector<uint64_t> *>(VT_PLAYERS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_SKI_ID, 4) &&
           VerifyField<uint64_t>(verifier, VT_TIME, 8) &&
           VerifyOffset(verifier, VT_MOBS) &&
           verifier.VerifyVector(mobs()) &&
           VerifyOffset(verifier, VT_PLAYERS) &&
           verifier.VerifyVector(players()) &&
           verifier.EndTable();
  }
  CharacterSkillT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CharacterSkillT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CharacterSkill> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterSkillT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CharacterSkillBuilder {
  typedef CharacterSkill Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_ski_id(uint32_t ski_id) {
    fbb_.AddElement<uint32_t>(CharacterSkill::VT_SKI_ID, ski_id, 0);
  }
  void add_time(uint64_t time) {
    fbb_.AddElement<uint64_t>(CharacterSkill::VT_TIME, time, 0);
  }
  void add_mobs(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> mobs) {
    fbb_.AddOffset(CharacterSkill::VT_MOBS, mobs);
  }
  void add_players(::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> players) {
    fbb_.AddOffset(CharacterSkill::VT_PLAYERS, players);
  }
  explicit CharacterSkillBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CharacterSkill> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CharacterSkill>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CharacterSkill> CreateCharacterSkill(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t ski_id = 0,
    uint64_t time = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> mobs = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> players = 0) {
  CharacterSkillBuilder builder_(_fbb);
  builder_.add_time(time);
  builder_.add_players(players);
  builder_.add_mobs(mobs);
  builder_.add_ski_id(ski_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CharacterSkill> CreateCharacterSkillDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t ski_id = 0,
    uint64_t time = 0,
    const std::vector<uint32_t> *mobs = nullptr,
    const std::vector<uint64_t> *players = nullptr) {
  auto mobs__ = mobs ? _fbb.CreateVector<uint32_t>(*mobs) : 0;
  auto players__ = players ? _fbb.CreateVector<uint64_t>(*players) : 0;
  return fbs::CreateCharacterSkill(
      _fbb,
      ski_id,
      time,
      mobs__,
      players__);
}

::flatbuffers::Offset<CharacterSkill> CreateCharacterSkill(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterSkillT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct PlayerT : public ::flatbuffers::NativeTable {
  typedef Player TableType;
  uint64_t client_id = 0;
  std::unique_ptr<fbs::CharacterT> character{};
  PlayerT() = default;
  PlayerT(const PlayerT &o);
  PlayerT(PlayerT&&) FLATBUFFERS_NOEXCEPT = default;
  PlayerT &operator=(PlayerT o) FLATBUFFERS_NOEXCEPT;
};

struct Player FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PlayerT NativeTableType;
  typedef PlayerBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLIENT_ID = 4,
    VT_CHARACTER = 6
  };
  uint64_t client_id() const {
    return GetField<uint64_t>(VT_CLIENT_ID, 0);
  }
  bool mutate_client_id(uint64_t _client_id = 0) {
    return SetField<uint64_t>(VT_CLIENT_ID, _client_id, 0);
  }
  const fbs::Character *character() const {
    return GetPointer<const fbs::Character *>(VT_CHARACTER);
  }
  fbs::Character *mutable_character() {
    return GetPointer<fbs::Character *>(VT_CHARACTER);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CLIENT_ID, 8) &&
           VerifyOffset(verifier, VT_CHARACTER) &&
           verifier.VerifyTable(character()) &&
           verifier.EndTable();
  }
  PlayerT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(PlayerT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Player> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PlayerT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct PlayerBuilder {
  typedef Player Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_client_id(uint64_t client_id) {
    fbb_.AddElement<uint64_t>(Player::VT_CLIENT_ID, client_id, 0);
  }
  void add_character(::flatbuffers::Offset<fbs::Character> character) {
    fbb_.AddOffset(Player::VT_CHARACTER, character);
  }
  explicit PlayerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Player> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Player>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Player> CreatePlayer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t client_id = 0,
    ::flatbuffers::Offset<fbs::Character> character = 0) {
  PlayerBuilder builder_(_fbb);
  builder_.add_client_id(client_id);
  builder_.add_character(character);
  return builder_.Finish();
}

::flatbuffers::Offset<Player> CreatePlayer(::flatbuffers::FlatBufferBuilder &_fbb, const PlayerT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct MobT : public ::flatbuffers::NativeTable {
  typedef Mob TableType;
  uint32_t mob_index = 0;
  uint32_t mob_id = 0;
  std::unique_ptr<fbs::LifeStateT> state{};
  MobT() = default;
  MobT(const MobT &o);
  MobT(MobT&&) FLATBUFFERS_NOEXCEPT = default;
  MobT &operator=(MobT o) FLATBUFFERS_NOEXCEPT;
};

struct Mob FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MobT NativeTableType;
  typedef MobBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MOB_INDEX = 4,
    VT_MOB_ID = 6,
    VT_STATE = 8
  };
  uint32_t mob_index() const {
    return GetField<uint32_t>(VT_MOB_INDEX, 0);
  }
  bool mutate_mob_index(uint32_t _mob_index = 0) {
    return SetField<uint32_t>(VT_MOB_INDEX, _mob_index, 0);
  }
  uint32_t mob_id() const {
    return GetField<uint32_t>(VT_MOB_ID, 0);
  }
  bool mutate_mob_id(uint32_t _mob_id = 0) {
    return SetField<uint32_t>(VT_MOB_ID, _mob_id, 0);
  }
  const fbs::LifeState *state() const {
    return GetPointer<const fbs::LifeState *>(VT_STATE);
  }
  fbs::LifeState *mutable_state() {
    return GetPointer<fbs::LifeState *>(VT_STATE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_MOB_INDEX, 4) &&
           VerifyField<uint32_t>(verifier, VT_MOB_ID, 4) &&
           VerifyOffset(verifier, VT_STATE) &&
           verifier.VerifyTable(state()) &&
           verifier.EndTable();
  }
  MobT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(MobT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Mob> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MobT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct MobBuilder {
  typedef Mob Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_mob_index(uint32_t mob_index) {
    fbb_.AddElement<uint32_t>(Mob::VT_MOB_INDEX, mob_index, 0);
  }
  void add_mob_id(uint32_t mob_id) {
    fbb_.AddElement<uint32_t>(Mob::VT_MOB_ID, mob_id, 0);
  }
  void add_state(::flatbuffers::Offset<fbs::LifeState> state) {
    fbb_.AddOffset(Mob::VT_STATE, state);
  }
  explicit MobBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Mob> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Mob>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Mob> CreateMob(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t mob_index = 0,
    uint32_t mob_id = 0,
    ::flatbuffers::Offset<fbs::LifeState> state = 0) {
  MobBuilder builder_(_fbb);
  builder_.add_state(state);
  builder_.add_mob_id(mob_id);
  builder_.add_mob_index(mob_index);
  return builder_.Finish();
}

::flatbuffers::Offset<Mob> CreateMob(::flatbuffers::FlatBufferBuilder &_fbb, const MobT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CharacterLogicT : public ::flatbuffers::NativeTable {
  typedef CharacterLogic TableType;
  uint64_t client_id = 0;
  fbs::CharacterLogicTypeUnion payload{};
};

struct CharacterLogic FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CharacterLogicT NativeTableType;
  typedef CharacterLogicBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLIENT_ID = 4,
    VT_PAYLOAD_TYPE = 6,
    VT_PAYLOAD = 8
  };
  uint64_t client_id() const {
    return GetField<uint64_t>(VT_CLIENT_ID, 0);
  }
  bool mutate_client_id(uint64_t _client_id = 0) {
    return SetField<uint64_t>(VT_CLIENT_ID, _client_id, 0);
  }
  fbs::CharacterLogicType payload_type() const {
    return static_cast<fbs::CharacterLogicType>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const fbs::Movement *payload_as_Movement() const {
    return payload_type() == fbs::CharacterLogicType_Movement ? static_cast<const fbs::Movement *>(payload()) : nullptr;
  }
  const fbs::Flip *payload_as_Flip() const {
    return payload_type() == fbs::CharacterLogicType_Flip ? static_cast<const fbs::Flip *>(payload()) : nullptr;
  }
  const fbs::Action *payload_as_Action() const {
    return payload_type() == fbs::CharacterLogicType_Action ? static_cast<const fbs::Action *>(payload()) : nullptr;
  }
  template<typename T> T *mutable_payload_as();
  fbs::Movement *mutable_payload_as_Movement() {
    return payload_type() == fbs::CharacterLogicType_Movement ? static_cast<fbs::Movement *>(mutable_payload()) : nullptr;
  }
  fbs::Flip *mutable_payload_as_Flip() {
    return payload_type() == fbs::CharacterLogicType_Flip ? static_cast<fbs::Flip *>(mutable_payload()) : nullptr;
  }
  fbs::Action *mutable_payload_as_Action() {
    return payload_type() == fbs::CharacterLogicType_Action ? static_cast<fbs::Action *>(mutable_payload()) : nullptr;
  }
  void *mutable_payload() {
    return GetPointer<void *>(VT_PAYLOAD);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CLIENT_ID, 8) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyCharacterLogicType(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
  CharacterLogicT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CharacterLogicT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CharacterLogic> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterLogicT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

template<> inline const fbs::Movement *CharacterLogic::payload_as<fbs::Movement>() const {
  return payload_as_Movement();
}

template<> inline fbs::Movement *CharacterLogic::mutable_payload_as<fbs::Movement>() {
  return mutable_payload_as_Movement();
}

template<> inline const fbs::Flip *CharacterLogic::payload_as<fbs::Flip>() const {
  return payload_as_Flip();
}

template<> inline fbs::Flip *CharacterLogic::mutable_payload_as<fbs::Flip>() {
  return mutable_payload_as_Flip();
}

template<> inline const fbs::Action *CharacterLogic::payload_as<fbs::Action>() const {
  return payload_as_Action();
}

template<> inline fbs::Action *CharacterLogic::mutable_payload_as<fbs::Action>() {
  return mutable_payload_as_Action();
}

struct CharacterLogicBuilder {
  typedef CharacterLogic Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_client_id(uint64_t client_id) {
    fbb_.AddElement<uint64_t>(CharacterLogic::VT_CLIENT_ID, client_id, 0);
  }
  void add_payload_type(fbs::CharacterLogicType payload_type) {
    fbb_.AddElement<uint8_t>(CharacterLogic::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(CharacterLogic::VT_PAYLOAD, payload);
  }
  explicit CharacterLogicBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CharacterLogic> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CharacterLogic>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CharacterLogic> CreateCharacterLogic(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t client_id = 0,
    fbs::CharacterLogicType payload_type = fbs::CharacterLogicType_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  CharacterLogicBuilder builder_(_fbb);
  builder_.add_client_id(client_id);
  builder_.add_payload(payload);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

::flatbuffers::Offset<CharacterLogic> CreateCharacterLogic(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterLogicT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct MobLogicT : public ::flatbuffers::NativeTable {
  typedef MobLogic TableType;
  uint32_t mob_index = 0;
  uint32_t mob_id = 0;
  fbs::MobLogicTypeUnion payload{};
};

struct MobLogic FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MobLogicT NativeTableType;
  typedef MobLogicBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MOB_INDEX = 4,
    VT_MOB_ID = 6,
    VT_PAYLOAD_TYPE = 8,
    VT_PAYLOAD = 10
  };
  uint32_t mob_index() const {
    return GetField<uint32_t>(VT_MOB_INDEX, 0);
  }
  bool mutate_mob_index(uint32_t _mob_index = 0) {
    return SetField<uint32_t>(VT_MOB_INDEX, _mob_index, 0);
  }
  uint32_t mob_id() const {
    return GetField<uint32_t>(VT_MOB_ID, 0);
  }
  bool mutate_mob_id(uint32_t _mob_id = 0) {
    return SetField<uint32_t>(VT_MOB_ID, _mob_id, 0);
  }
  fbs::MobLogicType payload_type() const {
    return static_cast<fbs::MobLogicType>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const fbs::Movement *payload_as_Movement() const {
    return payload_type() == fbs::MobLogicType_Movement ? static_cast<const fbs::Movement *>(payload()) : nullptr;
  }
  const fbs::Flip *payload_as_Flip() const {
    return payload_type() == fbs::MobLogicType_Flip ? static_cast<const fbs::Flip *>(payload()) : nullptr;
  }
  const fbs::Action *payload_as_Action() const {
    return payload_type() == fbs::MobLogicType_Action ? static_cast<const fbs::Action *>(payload()) : nullptr;
  }
  template<typename T> T *mutable_payload_as();
  fbs::Movement *mutable_payload_as_Movement() {
    return payload_type() == fbs::MobLogicType_Movement ? static_cast<fbs::Movement *>(mutable_payload()) : nullptr;
  }
  fbs::Flip *mutable_payload_as_Flip() {
    return payload_type() == fbs::MobLogicType_Flip ? static_cast<fbs::Flip *>(mutable_payload()) : nullptr;
  }
  fbs::Action *mutable_payload_as_Action() {
    return payload_type() == fbs::MobLogicType_Action ? static_cast<fbs::Action *>(mutable_payload()) : nullptr;
  }
  void *mutable_payload() {
    return GetPointer<void *>(VT_PAYLOAD);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_MOB_INDEX, 4) &&
           VerifyField<uint32_t>(verifier, VT_MOB_ID, 4) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyMobLogicType(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
  MobLogicT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(MobLogicT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<MobLogic> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MobLogicT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

template<> inline const fbs::Movement *MobLogic::payload_as<fbs::Movement>() const {
  return payload_as_Movement();
}

template<> inline fbs::Movement *MobLogic::mutable_payload_as<fbs::Movement>() {
  return mutable_payload_as_Movement();
}

template<> inline const fbs::Flip *MobLogic::payload_as<fbs::Flip>() const {
  return payload_as_Flip();
}

template<> inline fbs::Flip *MobLogic::mutable_payload_as<fbs::Flip>() {
  return mutable_payload_as_Flip();
}

template<> inline const fbs::Action *MobLogic::payload_as<fbs::Action>() const {
  return payload_as_Action();
}

template<> inline fbs::Action *MobLogic::mutable_payload_as<fbs::Action>() {
  return mutable_payload_as_Action();
}

struct MobLogicBuilder {
  typedef MobLogic Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_mob_index(uint32_t mob_index) {
    fbb_.AddElement<uint32_t>(MobLogic::VT_MOB_INDEX, mob_index, 0);
  }
  void add_mob_id(uint32_t mob_id) {
    fbb_.AddElement<uint32_t>(MobLogic::VT_MOB_ID, mob_id, 0);
  }
  void add_payload_type(fbs::MobLogicType payload_type) {
    fbb_.AddElement<uint8_t>(MobLogic::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(MobLogic::VT_PAYLOAD, payload);
  }
  explicit MobLogicBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MobLogic> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MobLogic>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MobLogic> CreateMobLogic(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t mob_index = 0,
    uint32_t mob_id = 0,
    fbs::MobLogicType payload_type = fbs::MobLogicType_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  MobLogicBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_mob_id(mob_id);
  builder_.add_mob_index(mob_index);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

::flatbuffers::Offset<MobLogic> CreateMobLogic(::flatbuffers::FlatBufferBuilder &_fbb, const MobLogicT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline LifeStateT *LifeState::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<LifeStateT>(new LifeStateT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void LifeState::UnPackTo(LifeStateT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x(); _o->x = _e; }
  { auto _e = y(); _o->y = _e; }
  { auto _e = action(); if (_e) _o->action = _e->str(); }
  { auto _e = action_index(); _o->action_index = _e; }
  { auto _e = action_animate(); _o->action_animate = _e; }
  { auto _e = page(); _o->page = _e; }
  { auto _e = flip(); _o->flip = _e; }
}

inline ::flatbuffers::Offset<LifeState> CreateLifeState(::flatbuffers::FlatBufferBuilder &_fbb, const LifeStateT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return LifeState::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<LifeState> LifeState::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const LifeStateT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const LifeStateT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x = _o->x;
  auto _y = _o->y;
  auto _action = _o->action.empty() ? 0 : _fbb.CreateString(_o->action);
  auto _action_index = _o->action_index;
  auto _action_animate = _o->action_animate;
  auto _page = _o->page;
  auto _flip = _o->flip;
  return fbs::CreateLifeState(
      _fbb,
      _x,
      _y,
      _action,
      _action_index,
      _action_animate,
      _page,
      _flip);
}

inline CharacterAppearanceT *CharacterAppearance::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CharacterAppearanceT>(new CharacterAppearanceT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CharacterAppearance::UnPackTo(CharacterAppearanceT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = body(); _o->body = _e; }
  { auto _e = head(); _o->head = _e; }
  { auto _e = face(); _o->face = _e; }
  { auto _e = hair(); _o->hair = _e; }
  { auto _e = weapon(); _o->weapon = _e; }
  { auto _e = cap(); _o->cap = _e; }
  { auto _e = cape(); _o->cape = _e; }
  { auto _e = coat(); _o->coat = _e; }
  { auto _e = glove(); _o->glove = _e; }
  { auto _e = pant(); _o->pant = _e; }
  { auto _e = shield(); _o->shield = _e; }
  { auto _e = longcoat(); _o->longcoat = _e; }
  { auto _e = shoes(); _o->shoes = _e; }
  { auto _e = accessory(); _o->accessory = _e; }
}

inline ::flatbuffers::Offset<CharacterAppearance> CreateCharacterAppearance(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterAppearanceT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CharacterAppearance::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CharacterAppearance> CharacterAppearance::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterAppearanceT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CharacterAppearanceT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _body = _o->body;
  auto _head = _o->head;
  auto _face = _o->face;
  auto _hair = _o->hair;
  auto _weapon = _o->weapon;
  auto _cap = _o->cap;
  auto _cape = _o->cape;
  auto _coat = _o->coat;
  auto _glove = _o->glove;
  auto _pant = _o->pant;
  auto _shield = _o->shield;
  auto _longcoat = _o->longcoat;
  auto _shoes = _o->shoes;
  auto _accessory = _o->accessory;
  return fbs::CreateCharacterAppearance(
      _fbb,
      _body,
      _head,
      _face,
      _hair,
      _weapon,
      _cap,
      _cape,
      _coat,
      _glove,
      _pant,
      _shield,
      _longcoat,
      _shoes,
      _accessory);
}

inline CharacterT::CharacterT(const CharacterT &o)
      : name(o.name),
        state((o.state) ? new fbs::LifeStateT(*o.state) : nullptr),
        appearance((o.appearance) ? new fbs::CharacterAppearanceT(*o.appearance) : nullptr) {
}

inline CharacterT &CharacterT::operator=(CharacterT o) FLATBUFFERS_NOEXCEPT {
  std::swap(name, o.name);
  std::swap(state, o.state);
  std::swap(appearance, o.appearance);
  return *this;
}

inline CharacterT *Character::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CharacterT>(new CharacterT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Character::UnPackTo(CharacterT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = name(); if (_e) _o->name = _e->str(); }
  { auto _e = state(); if (_e) { if(_o->state) { _e->UnPackTo(_o->state.get(), _resolver); } else { _o->state = std::unique_ptr<fbs::LifeStateT>(_e->UnPack(_resolver)); } } else if (_o->state) { _o->state.reset(); } }
  { auto _e = appearance(); if (_e) { if(_o->appearance) { _e->UnPackTo(_o->appearance.get(), _resolver); } else { _o->appearance = std::unique_ptr<fbs::CharacterAppearanceT>(_e->UnPack(_resolver)); } } else if (_o->appearance) { _o->appearance.reset(); } }
}

inline ::flatbuffers::Offset<Character> CreateCharacter(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Character::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Character> Character::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CharacterT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _state = _o->state ? CreateLifeState(_fbb, _o->state.get(), _rehasher) : 0;
  auto _appearance = _o->appearance ? CreateCharacterAppearance(_fbb, _o->appearance.get(), _rehasher) : 0;
  return fbs::CreateCharacter(
      _fbb,
      _name,
      _state,
      _appearance);
}

inline MovementT *Movement::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<MovementT>(new MovementT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Movement::UnPackTo(MovementT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x1(); _o->x1 = _e; }
  { auto _e = y1(); _o->y1 = _e; }
  { auto _e = x2(); _o->x2 = _e; }
  { auto _e = y2(); _o->y2 = _e; }
  { auto _e = time(); _o->time = _e; }
  { auto _e = page(); _o->page = _e; }
}

inline ::flatbuffers::Offset<Movement> CreateMovement(::flatbuffers::FlatBufferBuilder &_fbb, const MovementT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Movement::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Movement> Movement::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MovementT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const MovementT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x1 = _o->x1;
  auto _y1 = _o->y1;
  auto _x2 = _o->x2;
  auto _y2 = _o->y2;
  auto _time = _o->time;
  auto _page = _o->page;
  return fbs::CreateMovement(
      _fbb,
      _x1,
      _y1,
      _x2,
      _y2,
      _time,
      _page);
}

inline FlipT *Flip::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<FlipT>(new FlipT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Flip::UnPackTo(FlipT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = flip(); _o->flip = _e; }
}

inline ::flatbuffers::Offset<Flip> CreateFlip(::flatbuffers::FlatBufferBuilder &_fbb, const FlipT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Flip::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Flip> Flip::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const FlipT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const FlipT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _flip = _o->flip;
  return fbs::CreateFlip(
      _fbb,
      _flip);
}

inline ActionT *Action::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ActionT>(new ActionT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Action::UnPackTo(ActionT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = action(); if (_e) _o->action = _e->str(); }
  { auto _e = action_index(); _o->action_index = _e; }
  { auto _e = action_animate(); _o->action_animate = _e; }
}

inline ::flatbuffers::Offset<Action> CreateAction(::flatbuffers::FlatBufferBuilder &_fbb, const ActionT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Action::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Action> Action::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ActionT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ActionT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _action = _o->action.empty() ? 0 : _fbb.CreateString(_o->action);
  auto _action_index = _o->action_index;
  auto _action_animate = _o->action_animate;
  return fbs::CreateAction(
      _fbb,
      _action,
      _action_index,
      _action_animate);
}

inline AttackT *Attack::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<AttackT>(new AttackT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Attack::UnPackTo(AttackT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = time(); _o->time = _e; }
  { auto _e = num(); _o->num = _e; }
}

inline ::flatbuffers::Offset<Attack> CreateAttack(::flatbuffers::FlatBufferBuilder &_fbb, const AttackT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Attack::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Attack> Attack::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const AttackT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const AttackT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _time = _o->time;
  auto _num = _o->num;
  return fbs::CreateAttack(
      _fbb,
      _time,
      _num);
}

inline CharacterAttackT::CharacterAttackT(const CharacterAttackT &o)
      : mob_id(o.mob_id),
        attack((o.attack) ? new fbs::AttackT(*o.attack) : nullptr),
        afterimage(o.afterimage),
        left(o.left) {
}

inline CharacterAttackT &CharacterAttackT::operator=(CharacterAttackT o) FLATBUFFERS_NOEXCEPT {
  std::swap(mob_id, o.mob_id);
  std::swap(attack, o.attack);
  std::swap(afterimage, o.afterimage);
  std::swap(left, o.left);
  return *this;
}

inline CharacterAttackT *CharacterAttack::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CharacterAttackT>(new CharacterAttackT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CharacterAttack::UnPackTo(CharacterAttackT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = mob_id(); _o->mob_id = _e; }
  { auto _e = attack(); if (_e) { if(_o->attack) { _e->UnPackTo(_o->attack.get(), _resolver); } else { _o->attack = std::unique_ptr<fbs::AttackT>(_e->UnPack(_resolver)); } } else if (_o->attack) { _o->attack.reset(); } }
  { auto _e = afterimage(); _o->afterimage = _e; }
  { auto _e = left(); _o->left = _e; }
}

inline ::flatbuffers::Offset<CharacterAttack> CreateCharacterAttack(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterAttackT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CharacterAttack::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CharacterAttack> CharacterAttack::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterAttackT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CharacterAttackT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _mob_id = _o->mob_id;
  auto _attack = _o->attack ? CreateAttack(_fbb, _o->attack.get(), _rehasher) : 0;
  auto _afterimage = _o->afterimage;
  auto _left = _o->left;
  return fbs::CreateCharacterAttack(
      _fbb,
      _mob_id,
      _attack,
      _afterimage,
      _left);
}

inline CharacterSkillT *CharacterSkill::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CharacterSkillT>(new CharacterSkillT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CharacterSkill::UnPackTo(CharacterSkillT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = ski_id(); _o->ski_id = _e; }
  { auto _e = time(); _o->time = _e; }
  { auto _e = mobs(); if (_e) { _o->mobs.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->mobs[_i] = _e->Get(_i); } } else { _o->mobs.resize(0); } }
  { auto _e = players(); if (_e) { _o->players.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->players[_i] = _e->Get(_i); } } else { _o->players.resize(0); } }
}

inline ::flatbuffers::Offset<CharacterSkill> CreateCharacterSkill(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterSkillT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CharacterSkill::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CharacterSkill> CharacterSkill::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterSkillT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CharacterSkillT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _ski_id = _o->ski_id;
  auto _time = _o->time;
  auto _mobs = _o->mobs.size() ? _fbb.CreateVector(_o->mobs) : 0;
  auto _players = _o->players.size() ? _fbb.CreateVector(_o->players) : 0;
  return fbs::CreateCharacterSkill(
      _fbb,
      _ski_id,
      _time,
      _mobs,
      _players);
}

inline PlayerT::PlayerT(const PlayerT &o)
      : client_id(o.client_id),
        character((o.character) ? new fbs::CharacterT(*o.character) : nullptr) {
}

inline PlayerT &PlayerT::operator=(PlayerT o) FLATBUFFERS_NOEXCEPT {
  std::swap(client_id, o.client_id);
  std::swap(character, o.character);
  return *this;
}

inline PlayerT *Player::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<PlayerT>(new PlayerT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Player::UnPackTo(PlayerT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = client_id(); _o->client_id = _e; }
  { auto _e = character(); if (_e) { if(_o->character) { _e->UnPackTo(_o->character.get(), _resolver); } else { _o->character = std::unique_ptr<fbs::CharacterT>(_e->UnPack(_resolver)); } } else if (_o->character) { _o->character.reset(); } }
}

inline ::flatbuffers::Offset<Player> CreatePlayer(::flatbuffers::FlatBufferBuilder &_fbb, const PlayerT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Player::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Player> Player::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PlayerT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const PlayerT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _client_id = _o->client_id;
  auto _character = _o->character ? CreateCharacter(_fbb, _o->character.get(), _rehasher) : 0;
  return fbs::CreatePlayer(
      _fbb,
      _client_id,
      _character);
}

inline MobT::MobT(const MobT &o)
      : mob_index(o.mob_index),
        mob_id(o.mob_id),
        state((o.state) ? new fbs::LifeStateT(*o.state) : nullptr) {
}

inline MobT &MobT::operator=(MobT o) FLATBUFFERS_NOEXCEPT {
  std::swap(mob_index, o.mob_index);
  std::swap(mob_id, o.mob_id);
  std::swap(state, o.state);
  return *this;
}

inline MobT *Mob::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<MobT>(new MobT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Mob::UnPackTo(MobT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = mob_index(); _o->mob_index = _e; }
  { auto _e = mob_id(); _o->mob_id = _e; }
  { auto _e = state(); if (_e) { if(_o->state) { _e->UnPackTo(_o->state.get(), _resolver); } else { _o->state = std::unique_ptr<fbs::LifeStateT>(_e->UnPack(_resolver)); } } else if (_o->state) { _o->state.reset(); } }
}

inline ::flatbuffers::Offset<Mob> CreateMob(::flatbuffers::FlatBufferBuilder &_fbb, const MobT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Mob::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Mob> Mob::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MobT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const MobT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _mob_index = _o->mob_index;
  auto _mob_id = _o->mob_id;
  auto _state = _o->state ? CreateLifeState(_fbb, _o->state.get(), _rehasher) : 0;
  return fbs::CreateMob(
      _fbb,
      _mob_index,
      _mob_id,
      _state);
}

inline CharacterLogicT *CharacterLogic::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CharacterLogicT>(new CharacterLogicT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CharacterLogic::UnPackTo(CharacterLogicT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = client_id(); _o->client_id = _e; }
  { auto _e = payload_type(); _o->payload.type = _e; }
  { auto _e = payload(); if (_e) _o->payload.value = fbs::CharacterLogicTypeUnion::UnPack(_e, payload_type(), _resolver); }
}

inline ::flatbuffers::Offset<CharacterLogic> CreateCharacterLogic(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterLogicT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CharacterLogic::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CharacterLogic> CharacterLogic::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CharacterLogicT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CharacterLogicT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _client_id = _o->client_id;
  auto _payload_type = _o->payload.type;
  auto _payload = _o->payload.Pack(_fbb);
  return fbs::CreateCharacterLogic(
      _fbb,
      _client_id,
      _payload_type,
      _payload);
}

inline MobLogicT *MobLogic::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<MobLogicT>(new MobLogicT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void MobLogic::UnPackTo(MobLogicT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = mob_index(); _o->mob_index = _e; }
  { auto _e = mob_id(); _o->mob_id = _e; }
  { auto _e = payload_type(); _o->payload.type = _e; }
  { auto _e = payload(); if (_e) _o->payload.value = fbs::MobLogicTypeUnion::UnPack(_e, payload_type(), _resolver); }
}

inline ::flatbuffers::Offset<MobLogic> CreateMobLogic(::flatbuffers::FlatBufferBuilder &_fbb, const MobLogicT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return MobLogic::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<MobLogic> MobLogic::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MobLogicT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const MobLogicT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _mob_index = _o->mob_index;
  auto _mob_id = _o->mob_id;
  auto _payload_type = _o->payload.type;
  auto _payload = _o->payload.Pack(_fbb);
  return fbs::CreateMobLogic(
      _fbb,
      _mob_index,
      _mob_id,
      _payload_type,
      _payload);
}

template <bool B>
inline bool VerifyCharacterLogicType(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, CharacterLogicType type) {
  switch (type) {
    case CharacterLogicType_NONE: {
      return true;
    }
    case CharacterLogicType_Movement: {
      auto ptr = reinterpret_cast<const fbs::Movement *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case CharacterLogicType_Flip: {
      auto ptr = reinterpret_cast<const fbs::Flip *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case CharacterLogicType_Action: {
      auto ptr = reinterpret_cast<const fbs::Action *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyCharacterLogicTypeVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyCharacterLogicType(
        verifier,  values->Get(i), types->GetEnum<CharacterLogicType>(i))) {
      return false;
    }
  }
  return true;
}

inline void *CharacterLogicTypeUnion::UnPack(const void *obj, CharacterLogicType type, const ::flatbuffers::resolver_function_t *resolver) {
  (void)resolver;
  switch (type) {
    case CharacterLogicType_Movement: {
      auto ptr = reinterpret_cast<const fbs::Movement *>(obj);
      return ptr->UnPack(resolver);
    }
    case CharacterLogicType_Flip: {
      auto ptr = reinterpret_cast<const fbs::Flip *>(obj);
      return ptr->UnPack(resolver);
    }
    case CharacterLogicType_Action: {
      auto ptr = reinterpret_cast<const fbs::Action *>(obj);
      return ptr->UnPack(resolver);
    }
    default: return nullptr;
  }
}

inline ::flatbuffers::Offset<void> CharacterLogicTypeUnion::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher) const {
  (void)_rehasher;
  switch (type) {
    case CharacterLogicType_Movement: {
      auto ptr = reinterpret_cast<const fbs::MovementT *>(value);
      return CreateMovement(_fbb, ptr, _rehasher).Union();
    }
    case CharacterLogicType_Flip: {
      auto ptr = reinterpret_cast<const fbs::FlipT *>(value);
      return CreateFlip(_fbb, ptr, _rehasher).Union();
    }
    case CharacterLogicType_Action: {
      auto ptr = reinterpret_cast<const fbs::ActionT *>(value);
      return CreateAction(_fbb, ptr, _rehasher).Union();
    }
    default: return 0;
  }
}

inline CharacterLogicTypeUnion::CharacterLogicTypeUnion(const CharacterLogicTypeUnion &u) : type(u.type), value(nullptr) {
  switch (type) {
    case CharacterLogicType_Movement: {
      value = new fbs::MovementT(*reinterpret_cast<fbs::MovementT *>(u.value));
      break;
    }
    case CharacterLogicType_Flip: {
      value = new fbs::FlipT(*reinterpret_cast<fbs::FlipT *>(u.value));
      break;
    }
    case CharacterLogicType_Action: {
      value = new fbs::ActionT(*reinterpret_cast<fbs::ActionT *>(u.value));
      break;
    }
    default:
      break;
  }
}

inline void CharacterLogicTypeUnion::Reset() {
  switch (type) {
    case CharacterLogicType_Movement: {
      auto ptr = reinterpret_cast<fbs::MovementT *>(value);
      delete ptr;
      break;
    }
    case CharacterLogicType_Flip: {
      auto ptr = reinterpret_cast<fbs::FlipT *>(value);
      delete ptr;
      break;
    }
    case CharacterLogicType_Action: {
      auto ptr = reinterpret_cast<fbs::ActionT *>(value);
      delete ptr;
      break;
    }
    default: break;
  }
  value = nullptr;
  type = CharacterLogicType_NONE;
}

template <bool B>
inline bool VerifyMobLogicType(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, MobLogicType type) {
  switch (type) {
    case MobLogicType_NONE: {
      return true;
    }
    case MobLogicType_Movement: {
      auto ptr = reinterpret_cast<const fbs::Movement *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MobLogicType_Flip: {
      auto ptr = reinterpret_cast<const fbs::Flip *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MobLogicType_Action: {
      auto ptr = reinterpret_cast<const fbs::Action *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyMobLogicTypeVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyMobLogicType(
        verifier,  values->Get(i), types->GetEnum<MobLogicType>(i))) {
      return false;
    }
  }
  return true;
}

inline void *MobLogicTypeUnion::UnPack(const void *obj, MobLogicType type, const ::flatbuffers::resolver_function_t *resolver) {
  (void)resolver;
  switch (type) {
    case MobLogicType_Movement: {
      auto ptr = reinterpret_cast<const fbs::Movement *>(obj);
      return ptr->UnPack(resolver);
    }
    case MobLogicType_Flip: {
      auto ptr = reinterpret_cast<const fbs::Flip *>(obj);
      return ptr->UnPack(resolver);
    }
    case MobLogicType_Action: {
      auto ptr = reinterpret_cast<const fbs::Action *>(obj);
      return ptr->UnPack(resolver);
    }
    default: return nullptr;
  }
}

inline ::flatbuffers::Offset<void> MobLogicTypeUnion::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher) const {
  (void)_rehasher;
  switch (type) {
    case MobLogicType_Movement: {
      auto ptr = reinterpret_cast<const fbs::MovementT *>(value);
      return CreateMovement(_fbb, ptr, _rehasher).Union();
    }
    case MobLogicType_Flip: {
      auto ptr = reinterpret_cast<const fbs::FlipT *>(value);
      return CreateFlip(_fbb, ptr, _rehasher).Union();
    }
    case MobLogicType_Action: {
      auto ptr = reinterpret_cast<const fbs::ActionT *>(value);
      return CreateAction(_fbb, ptr, _rehasher).Union();
    }
    default: return 0;
  }
}

inline MobLogicTypeUnion::MobLogicTypeUnion(const MobLogicTypeUnion &u) : type(u.type), value(nullptr) {
  switch (type) {
    case MobLogicType_Movement: {
      value = new fbs::MovementT(*reinterpret_cast<fbs::MovementT *>(u.value));
      break;
    }
    case MobLogicType_Flip: {
      value = new fbs::FlipT(*reinterpret_cast<fbs::FlipT *>(u.value));
      break;
    }
    case MobLogicType_Action: {
      value = new fbs::ActionT(*reinterpret_cast<fbs::ActionT *>(u.value));
      break;
    }
    default:
      break;
  }
}

inline void MobLogicTypeUnion::Reset() {
  switch (type) {
    case MobLogicType_Movement: {
      auto ptr = reinterpret_cast<fbs::MovementT *>(value);
      delete ptr;
      break;
    }
    case MobLogicType_Flip: {
      auto ptr = reinterpret_cast<fbs::FlipT *>(value);
      delete ptr;
      break;
    }
    case MobLogicType_Action: {
      auto ptr = reinterpret_cast<fbs::ActionT *>(value);
      delete ptr;
      break;
    }
    default: break;
  }
  value = nullptr;
  type = MobLogicType_NONE;
}

}  // namespace fbs

#endif  // FLATBUFFERS_GENERATED_COMMON_FBS_H_
