// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SERVER_FBS_H_
#define FLATBUFFERS_GENERATED_SERVER_FBS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "common.h"

namespace fbs {

struct ServerHeartbeat;
struct ServerHeartbeatBuilder;
struct ServerHeartbeatT;

struct ServerScene;
struct ServerSceneBuilder;
struct ServerSceneT;

struct ServerCharacterMove;
struct ServerCharacterMoveBuilder;
struct ServerCharacterMoveT;

struct ServerCharacterIn;
struct ServerCharacterInBuilder;
struct ServerCharacterInT;

struct ServerMobMove;
struct ServerMobMoveBuilder;
struct ServerMobMoveT;

struct ServerHeartbeatT : public ::flatbuffers::NativeTable {
  typedef ServerHeartbeat TableType;
};

struct ServerHeartbeat FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerHeartbeatT NativeTableType;
  typedef ServerHeartbeatBuilder Builder;
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
  ServerHeartbeatT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ServerHeartbeatT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ServerHeartbeat> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerHeartbeatT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ServerHeartbeatBuilder {
  typedef ServerHeartbeat Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit ServerHeartbeatBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerHeartbeat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerHeartbeat>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerHeartbeat> CreateServerHeartbeat(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  ServerHeartbeatBuilder builder_(_fbb);
  return builder_.Finish();
}

::flatbuffers::Offset<ServerHeartbeat> CreateServerHeartbeat(::flatbuffers::FlatBufferBuilder &_fbb, const ServerHeartbeatT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ServerSceneT : public ::flatbuffers::NativeTable {
  typedef ServerScene TableType;
  uint32_t map_id = 0;
  uint64_t your_id = 0;
  std::vector<std::unique_ptr<fbs::PlayerT>> players{};
  std::vector<std::unique_ptr<fbs::MobT>> mobs{};
  ServerSceneT() = default;
  ServerSceneT(const ServerSceneT &o);
  ServerSceneT(ServerSceneT&&) FLATBUFFERS_NOEXCEPT = default;
  ServerSceneT &operator=(ServerSceneT o) FLATBUFFERS_NOEXCEPT;
};

struct ServerScene FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerSceneT NativeTableType;
  typedef ServerSceneBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MAP_ID = 4,
    VT_YOUR_ID = 6,
    VT_PLAYERS = 8,
    VT_MOBS = 10
  };
  uint32_t map_id() const {
    return GetField<uint32_t>(VT_MAP_ID, 0);
  }
  bool mutate_map_id(uint32_t _map_id = 0) {
    return SetField<uint32_t>(VT_MAP_ID, _map_id, 0);
  }
  uint64_t your_id() const {
    return GetField<uint64_t>(VT_YOUR_ID, 0);
  }
  bool mutate_your_id(uint64_t _your_id = 0) {
    return SetField<uint64_t>(VT_YOUR_ID, _your_id, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::Player>> *players() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::Player>> *>(VT_PLAYERS);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<fbs::Player>> *mutable_players() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<fbs::Player>> *>(VT_PLAYERS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::Mob>> *mobs() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::Mob>> *>(VT_MOBS);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<fbs::Mob>> *mutable_mobs() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<fbs::Mob>> *>(VT_MOBS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_MAP_ID, 4) &&
           VerifyField<uint64_t>(verifier, VT_YOUR_ID, 8) &&
           VerifyOffset(verifier, VT_PLAYERS) &&
           verifier.VerifyVector(players()) &&
           verifier.VerifyVectorOfTables(players()) &&
           VerifyOffset(verifier, VT_MOBS) &&
           verifier.VerifyVector(mobs()) &&
           verifier.VerifyVectorOfTables(mobs()) &&
           verifier.EndTable();
  }
  ServerSceneT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ServerSceneT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ServerScene> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerSceneT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ServerSceneBuilder {
  typedef ServerScene Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_map_id(uint32_t map_id) {
    fbb_.AddElement<uint32_t>(ServerScene::VT_MAP_ID, map_id, 0);
  }
  void add_your_id(uint64_t your_id) {
    fbb_.AddElement<uint64_t>(ServerScene::VT_YOUR_ID, your_id, 0);
  }
  void add_players(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::Player>>> players) {
    fbb_.AddOffset(ServerScene::VT_PLAYERS, players);
  }
  void add_mobs(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::Mob>>> mobs) {
    fbb_.AddOffset(ServerScene::VT_MOBS, mobs);
  }
  explicit ServerSceneBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerScene> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerScene>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerScene> CreateServerScene(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t map_id = 0,
    uint64_t your_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::Player>>> players = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::Mob>>> mobs = 0) {
  ServerSceneBuilder builder_(_fbb);
  builder_.add_your_id(your_id);
  builder_.add_mobs(mobs);
  builder_.add_players(players);
  builder_.add_map_id(map_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ServerScene> CreateServerSceneDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t map_id = 0,
    uint64_t your_id = 0,
    const std::vector<::flatbuffers::Offset<fbs::Player>> *players = nullptr,
    const std::vector<::flatbuffers::Offset<fbs::Mob>> *mobs = nullptr) {
  auto players__ = players ? _fbb.CreateVector<::flatbuffers::Offset<fbs::Player>>(*players) : 0;
  auto mobs__ = mobs ? _fbb.CreateVector<::flatbuffers::Offset<fbs::Mob>>(*mobs) : 0;
  return fbs::CreateServerScene(
      _fbb,
      map_id,
      your_id,
      players__,
      mobs__);
}

::flatbuffers::Offset<ServerScene> CreateServerScene(::flatbuffers::FlatBufferBuilder &_fbb, const ServerSceneT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ServerCharacterMoveT : public ::flatbuffers::NativeTable {
  typedef ServerCharacterMove TableType;
  std::unique_ptr<fbs::MovementT> movement{};
  uint64_t client_id = 0;
  ServerCharacterMoveT() = default;
  ServerCharacterMoveT(const ServerCharacterMoveT &o);
  ServerCharacterMoveT(ServerCharacterMoveT&&) FLATBUFFERS_NOEXCEPT = default;
  ServerCharacterMoveT &operator=(ServerCharacterMoveT o) FLATBUFFERS_NOEXCEPT;
};

struct ServerCharacterMove FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerCharacterMoveT NativeTableType;
  typedef ServerCharacterMoveBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MOVEMENT = 4,
    VT_CLIENT_ID = 6
  };
  const fbs::Movement *movement() const {
    return GetPointer<const fbs::Movement *>(VT_MOVEMENT);
  }
  fbs::Movement *mutable_movement() {
    return GetPointer<fbs::Movement *>(VT_MOVEMENT);
  }
  uint64_t client_id() const {
    return GetField<uint64_t>(VT_CLIENT_ID, 0);
  }
  bool mutate_client_id(uint64_t _client_id = 0) {
    return SetField<uint64_t>(VT_CLIENT_ID, _client_id, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MOVEMENT) &&
           verifier.VerifyTable(movement()) &&
           VerifyField<uint64_t>(verifier, VT_CLIENT_ID, 8) &&
           verifier.EndTable();
  }
  ServerCharacterMoveT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ServerCharacterMoveT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ServerCharacterMove> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterMoveT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ServerCharacterMoveBuilder {
  typedef ServerCharacterMove Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_movement(::flatbuffers::Offset<fbs::Movement> movement) {
    fbb_.AddOffset(ServerCharacterMove::VT_MOVEMENT, movement);
  }
  void add_client_id(uint64_t client_id) {
    fbb_.AddElement<uint64_t>(ServerCharacterMove::VT_CLIENT_ID, client_id, 0);
  }
  explicit ServerCharacterMoveBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerCharacterMove> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerCharacterMove>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerCharacterMove> CreateServerCharacterMove(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<fbs::Movement> movement = 0,
    uint64_t client_id = 0) {
  ServerCharacterMoveBuilder builder_(_fbb);
  builder_.add_client_id(client_id);
  builder_.add_movement(movement);
  return builder_.Finish();
}

::flatbuffers::Offset<ServerCharacterMove> CreateServerCharacterMove(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterMoveT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ServerCharacterInT : public ::flatbuffers::NativeTable {
  typedef ServerCharacterIn TableType;
  std::unique_ptr<fbs::PlayerT> player{};
  ServerCharacterInT() = default;
  ServerCharacterInT(const ServerCharacterInT &o);
  ServerCharacterInT(ServerCharacterInT&&) FLATBUFFERS_NOEXCEPT = default;
  ServerCharacterInT &operator=(ServerCharacterInT o) FLATBUFFERS_NOEXCEPT;
};

struct ServerCharacterIn FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerCharacterInT NativeTableType;
  typedef ServerCharacterInBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PLAYER = 4
  };
  const fbs::Player *player() const {
    return GetPointer<const fbs::Player *>(VT_PLAYER);
  }
  fbs::Player *mutable_player() {
    return GetPointer<fbs::Player *>(VT_PLAYER);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PLAYER) &&
           verifier.VerifyTable(player()) &&
           verifier.EndTable();
  }
  ServerCharacterInT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ServerCharacterInT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ServerCharacterIn> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterInT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ServerCharacterInBuilder {
  typedef ServerCharacterIn Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_player(::flatbuffers::Offset<fbs::Player> player) {
    fbb_.AddOffset(ServerCharacterIn::VT_PLAYER, player);
  }
  explicit ServerCharacterInBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerCharacterIn> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerCharacterIn>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerCharacterIn> CreateServerCharacterIn(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<fbs::Player> player = 0) {
  ServerCharacterInBuilder builder_(_fbb);
  builder_.add_player(player);
  return builder_.Finish();
}

::flatbuffers::Offset<ServerCharacterIn> CreateServerCharacterIn(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterInT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ServerMobMoveT : public ::flatbuffers::NativeTable {
  typedef ServerMobMove TableType;
  std::vector<std::unique_ptr<fbs::MobMovementT>> movement{};
  ServerMobMoveT() = default;
  ServerMobMoveT(const ServerMobMoveT &o);
  ServerMobMoveT(ServerMobMoveT&&) FLATBUFFERS_NOEXCEPT = default;
  ServerMobMoveT &operator=(ServerMobMoveT o) FLATBUFFERS_NOEXCEPT;
};

struct ServerMobMove FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerMobMoveT NativeTableType;
  typedef ServerMobMoveBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MOVEMENT = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::MobMovement>> *movement() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::MobMovement>> *>(VT_MOVEMENT);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<fbs::MobMovement>> *mutable_movement() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<fbs::MobMovement>> *>(VT_MOVEMENT);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MOVEMENT) &&
           verifier.VerifyVector(movement()) &&
           verifier.VerifyVectorOfTables(movement()) &&
           verifier.EndTable();
  }
  ServerMobMoveT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ServerMobMoveT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ServerMobMove> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerMobMoveT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ServerMobMoveBuilder {
  typedef ServerMobMove Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_movement(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::MobMovement>>> movement) {
    fbb_.AddOffset(ServerMobMove::VT_MOVEMENT, movement);
  }
  explicit ServerMobMoveBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerMobMove> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerMobMove>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerMobMove> CreateServerMobMove(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::MobMovement>>> movement = 0) {
  ServerMobMoveBuilder builder_(_fbb);
  builder_.add_movement(movement);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ServerMobMove> CreateServerMobMoveDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<fbs::MobMovement>> *movement = nullptr) {
  auto movement__ = movement ? _fbb.CreateVector<::flatbuffers::Offset<fbs::MobMovement>>(*movement) : 0;
  return fbs::CreateServerMobMove(
      _fbb,
      movement__);
}

::flatbuffers::Offset<ServerMobMove> CreateServerMobMove(::flatbuffers::FlatBufferBuilder &_fbb, const ServerMobMoveT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline ServerHeartbeatT *ServerHeartbeat::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ServerHeartbeatT>(new ServerHeartbeatT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ServerHeartbeat::UnPackTo(ServerHeartbeatT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
}

inline ::flatbuffers::Offset<ServerHeartbeat> CreateServerHeartbeat(::flatbuffers::FlatBufferBuilder &_fbb, const ServerHeartbeatT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ServerHeartbeat::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ServerHeartbeat> ServerHeartbeat::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerHeartbeatT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ServerHeartbeatT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  return fbs::CreateServerHeartbeat(
      _fbb);
}

inline ServerSceneT::ServerSceneT(const ServerSceneT &o)
      : map_id(o.map_id),
        your_id(o.your_id) {
  players.reserve(o.players.size());
  for (const auto &players_ : o.players) { players.emplace_back((players_) ? new fbs::PlayerT(*players_) : nullptr); }
  mobs.reserve(o.mobs.size());
  for (const auto &mobs_ : o.mobs) { mobs.emplace_back((mobs_) ? new fbs::MobT(*mobs_) : nullptr); }
}

inline ServerSceneT &ServerSceneT::operator=(ServerSceneT o) FLATBUFFERS_NOEXCEPT {
  std::swap(map_id, o.map_id);
  std::swap(your_id, o.your_id);
  std::swap(players, o.players);
  std::swap(mobs, o.mobs);
  return *this;
}

inline ServerSceneT *ServerScene::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ServerSceneT>(new ServerSceneT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ServerScene::UnPackTo(ServerSceneT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = map_id(); _o->map_id = _e; }
  { auto _e = your_id(); _o->your_id = _e; }
  { auto _e = players(); if (_e) { _o->players.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->players[_i]) { _e->Get(_i)->UnPackTo(_o->players[_i].get(), _resolver); } else { _o->players[_i] = std::unique_ptr<fbs::PlayerT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->players.resize(0); } }
  { auto _e = mobs(); if (_e) { _o->mobs.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->mobs[_i]) { _e->Get(_i)->UnPackTo(_o->mobs[_i].get(), _resolver); } else { _o->mobs[_i] = std::unique_ptr<fbs::MobT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->mobs.resize(0); } }
}

inline ::flatbuffers::Offset<ServerScene> CreateServerScene(::flatbuffers::FlatBufferBuilder &_fbb, const ServerSceneT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ServerScene::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ServerScene> ServerScene::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerSceneT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ServerSceneT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _map_id = _o->map_id;
  auto _your_id = _o->your_id;
  auto _players = _o->players.size() ? _fbb.CreateVector<::flatbuffers::Offset<fbs::Player>> (_o->players.size(), [](size_t i, _VectorArgs *__va) { return CreatePlayer(*__va->__fbb, __va->__o->players[i].get(), __va->__rehasher); }, &_va ) : 0;
  auto _mobs = _o->mobs.size() ? _fbb.CreateVector<::flatbuffers::Offset<fbs::Mob>> (_o->mobs.size(), [](size_t i, _VectorArgs *__va) { return CreateMob(*__va->__fbb, __va->__o->mobs[i].get(), __va->__rehasher); }, &_va ) : 0;
  return fbs::CreateServerScene(
      _fbb,
      _map_id,
      _your_id,
      _players,
      _mobs);
}

inline ServerCharacterMoveT::ServerCharacterMoveT(const ServerCharacterMoveT &o)
      : movement((o.movement) ? new fbs::MovementT(*o.movement) : nullptr),
        client_id(o.client_id) {
}

inline ServerCharacterMoveT &ServerCharacterMoveT::operator=(ServerCharacterMoveT o) FLATBUFFERS_NOEXCEPT {
  std::swap(movement, o.movement);
  std::swap(client_id, o.client_id);
  return *this;
}

inline ServerCharacterMoveT *ServerCharacterMove::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ServerCharacterMoveT>(new ServerCharacterMoveT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ServerCharacterMove::UnPackTo(ServerCharacterMoveT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = movement(); if (_e) { if(_o->movement) { _e->UnPackTo(_o->movement.get(), _resolver); } else { _o->movement = std::unique_ptr<fbs::MovementT>(_e->UnPack(_resolver)); } } else if (_o->movement) { _o->movement.reset(); } }
  { auto _e = client_id(); _o->client_id = _e; }
}

inline ::flatbuffers::Offset<ServerCharacterMove> CreateServerCharacterMove(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterMoveT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ServerCharacterMove::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ServerCharacterMove> ServerCharacterMove::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterMoveT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ServerCharacterMoveT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _movement = _o->movement ? CreateMovement(_fbb, _o->movement.get(), _rehasher) : 0;
  auto _client_id = _o->client_id;
  return fbs::CreateServerCharacterMove(
      _fbb,
      _movement,
      _client_id);
}

inline ServerCharacterInT::ServerCharacterInT(const ServerCharacterInT &o)
      : player((o.player) ? new fbs::PlayerT(*o.player) : nullptr) {
}

inline ServerCharacterInT &ServerCharacterInT::operator=(ServerCharacterInT o) FLATBUFFERS_NOEXCEPT {
  std::swap(player, o.player);
  return *this;
}

inline ServerCharacterInT *ServerCharacterIn::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ServerCharacterInT>(new ServerCharacterInT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ServerCharacterIn::UnPackTo(ServerCharacterInT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = player(); if (_e) { if(_o->player) { _e->UnPackTo(_o->player.get(), _resolver); } else { _o->player = std::unique_ptr<fbs::PlayerT>(_e->UnPack(_resolver)); } } else if (_o->player) { _o->player.reset(); } }
}

inline ::flatbuffers::Offset<ServerCharacterIn> CreateServerCharacterIn(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterInT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ServerCharacterIn::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ServerCharacterIn> ServerCharacterIn::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterInT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ServerCharacterInT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _player = _o->player ? CreatePlayer(_fbb, _o->player.get(), _rehasher) : 0;
  return fbs::CreateServerCharacterIn(
      _fbb,
      _player);
}

inline ServerMobMoveT::ServerMobMoveT(const ServerMobMoveT &o) {
  movement.reserve(o.movement.size());
  for (const auto &movement_ : o.movement) { movement.emplace_back((movement_) ? new fbs::MobMovementT(*movement_) : nullptr); }
}

inline ServerMobMoveT &ServerMobMoveT::operator=(ServerMobMoveT o) FLATBUFFERS_NOEXCEPT {
  std::swap(movement, o.movement);
  return *this;
}

inline ServerMobMoveT *ServerMobMove::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ServerMobMoveT>(new ServerMobMoveT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ServerMobMove::UnPackTo(ServerMobMoveT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = movement(); if (_e) { _o->movement.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->movement[_i]) { _e->Get(_i)->UnPackTo(_o->movement[_i].get(), _resolver); } else { _o->movement[_i] = std::unique_ptr<fbs::MobMovementT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->movement.resize(0); } }
}

inline ::flatbuffers::Offset<ServerMobMove> CreateServerMobMove(::flatbuffers::FlatBufferBuilder &_fbb, const ServerMobMoveT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ServerMobMove::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ServerMobMove> ServerMobMove::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerMobMoveT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ServerMobMoveT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _movement = _o->movement.size() ? _fbb.CreateVector<::flatbuffers::Offset<fbs::MobMovement>> (_o->movement.size(), [](size_t i, _VectorArgs *__va) { return CreateMobMovement(*__va->__fbb, __va->__o->movement[i].get(), __va->__rehasher); }, &_va ) : 0;
  return fbs::CreateServerMobMove(
      _fbb,
      _movement);
}

}  // namespace fbs

#endif  // FLATBUFFERS_GENERATED_SERVER_FBS_H_
