// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SERVER_FBS_H_
#define FLATBUFFERS_GENERATED_SERVER_FBS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "common.h"

namespace fbs {

struct ServerHeartbeat;
struct ServerHeartbeatBuilder;
struct ServerHeartbeatT;

struct ServerScene;
struct ServerSceneBuilder;
struct ServerSceneT;

struct ServerCharacterLogic;
struct ServerCharacterLogicBuilder;
struct ServerCharacterLogicT;

struct ServerCharacterIn;
struct ServerCharacterInBuilder;
struct ServerCharacterInT;

struct ServerCharacterOut;
struct ServerCharacterOutBuilder;
struct ServerCharacterOutT;

struct ServerMobLogic;
struct ServerMobLogicBuilder;
struct ServerMobLogicT;

struct ServerCharacterAttack;
struct ServerCharacterAttackBuilder;
struct ServerCharacterAttackT;

struct ServerCharacterSkill;
struct ServerCharacterSkillBuilder;
struct ServerCharacterSkillT;

struct ServerCharacterBall;
struct ServerCharacterBallBuilder;
struct ServerCharacterBallT;

struct ServerMobAttack;
struct ServerMobAttackBuilder;
struct ServerMobAttackT;

struct ServerCharacterChat;
struct ServerCharacterChatBuilder;
struct ServerCharacterChatT;

struct ServerHeartbeatT : public ::flatbuffers::NativeTable {
  typedef ServerHeartbeat TableType;
};

struct ServerHeartbeat FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerHeartbeatT NativeTableType;
  typedef ServerHeartbeatBuilder Builder;
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
  ServerHeartbeatT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ServerHeartbeatT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ServerHeartbeat> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerHeartbeatT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ServerHeartbeatBuilder {
  typedef ServerHeartbeat Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit ServerHeartbeatBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerHeartbeat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerHeartbeat>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerHeartbeat> CreateServerHeartbeat(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  ServerHeartbeatBuilder builder_(_fbb);
  return builder_.Finish();
}

::flatbuffers::Offset<ServerHeartbeat> CreateServerHeartbeat(::flatbuffers::FlatBufferBuilder &_fbb, const ServerHeartbeatT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ServerSceneT : public ::flatbuffers::NativeTable {
  typedef ServerScene TableType;
  uint32_t map_id = 0;
  uint64_t your_id = 0;
  std::vector<std::unique_ptr<fbs::PlayerT>> players{};
  std::vector<std::unique_ptr<fbs::MobT>> mobs{};
  ServerSceneT() = default;
  ServerSceneT(const ServerSceneT &o);
  ServerSceneT(ServerSceneT&&) FLATBUFFERS_NOEXCEPT = default;
  ServerSceneT &operator=(ServerSceneT o) FLATBUFFERS_NOEXCEPT;
};

struct ServerScene FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerSceneT NativeTableType;
  typedef ServerSceneBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MAP_ID = 4,
    VT_YOUR_ID = 6,
    VT_PLAYERS = 8,
    VT_MOBS = 10
  };
  uint32_t map_id() const {
    return GetField<uint32_t>(VT_MAP_ID, 0);
  }
  bool mutate_map_id(uint32_t _map_id = 0) {
    return SetField<uint32_t>(VT_MAP_ID, _map_id, 0);
  }
  uint64_t your_id() const {
    return GetField<uint64_t>(VT_YOUR_ID, 0);
  }
  bool mutate_your_id(uint64_t _your_id = 0) {
    return SetField<uint64_t>(VT_YOUR_ID, _your_id, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::Player>> *players() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::Player>> *>(VT_PLAYERS);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<fbs::Player>> *mutable_players() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<fbs::Player>> *>(VT_PLAYERS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::Mob>> *mobs() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::Mob>> *>(VT_MOBS);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<fbs::Mob>> *mutable_mobs() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<fbs::Mob>> *>(VT_MOBS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_MAP_ID, 4) &&
           VerifyField<uint64_t>(verifier, VT_YOUR_ID, 8) &&
           VerifyOffset(verifier, VT_PLAYERS) &&
           verifier.VerifyVector(players()) &&
           verifier.VerifyVectorOfTables(players()) &&
           VerifyOffset(verifier, VT_MOBS) &&
           verifier.VerifyVector(mobs()) &&
           verifier.VerifyVectorOfTables(mobs()) &&
           verifier.EndTable();
  }
  ServerSceneT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ServerSceneT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ServerScene> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerSceneT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ServerSceneBuilder {
  typedef ServerScene Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_map_id(uint32_t map_id) {
    fbb_.AddElement<uint32_t>(ServerScene::VT_MAP_ID, map_id, 0);
  }
  void add_your_id(uint64_t your_id) {
    fbb_.AddElement<uint64_t>(ServerScene::VT_YOUR_ID, your_id, 0);
  }
  void add_players(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::Player>>> players) {
    fbb_.AddOffset(ServerScene::VT_PLAYERS, players);
  }
  void add_mobs(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::Mob>>> mobs) {
    fbb_.AddOffset(ServerScene::VT_MOBS, mobs);
  }
  explicit ServerSceneBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerScene> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerScene>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerScene> CreateServerScene(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t map_id = 0,
    uint64_t your_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::Player>>> players = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::Mob>>> mobs = 0) {
  ServerSceneBuilder builder_(_fbb);
  builder_.add_your_id(your_id);
  builder_.add_mobs(mobs);
  builder_.add_players(players);
  builder_.add_map_id(map_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ServerScene> CreateServerSceneDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t map_id = 0,
    uint64_t your_id = 0,
    const std::vector<::flatbuffers::Offset<fbs::Player>> *players = nullptr,
    const std::vector<::flatbuffers::Offset<fbs::Mob>> *mobs = nullptr) {
  auto players__ = players ? _fbb.CreateVector<::flatbuffers::Offset<fbs::Player>>(*players) : 0;
  auto mobs__ = mobs ? _fbb.CreateVector<::flatbuffers::Offset<fbs::Mob>>(*mobs) : 0;
  return fbs::CreateServerScene(
      _fbb,
      map_id,
      your_id,
      players__,
      mobs__);
}

::flatbuffers::Offset<ServerScene> CreateServerScene(::flatbuffers::FlatBufferBuilder &_fbb, const ServerSceneT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ServerCharacterLogicT : public ::flatbuffers::NativeTable {
  typedef ServerCharacterLogic TableType;
  std::unique_ptr<fbs::CharacterLogicT> payload{};
  ServerCharacterLogicT() = default;
  ServerCharacterLogicT(const ServerCharacterLogicT &o);
  ServerCharacterLogicT(ServerCharacterLogicT&&) FLATBUFFERS_NOEXCEPT = default;
  ServerCharacterLogicT &operator=(ServerCharacterLogicT o) FLATBUFFERS_NOEXCEPT;
};

struct ServerCharacterLogic FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerCharacterLogicT NativeTableType;
  typedef ServerCharacterLogicBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD = 4
  };
  const fbs::CharacterLogic *payload() const {
    return GetPointer<const fbs::CharacterLogic *>(VT_PAYLOAD);
  }
  fbs::CharacterLogic *mutable_payload() {
    return GetPointer<fbs::CharacterLogic *>(VT_PAYLOAD);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           verifier.VerifyTable(payload()) &&
           verifier.EndTable();
  }
  ServerCharacterLogicT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ServerCharacterLogicT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ServerCharacterLogic> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterLogicT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ServerCharacterLogicBuilder {
  typedef ServerCharacterLogic Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_payload(::flatbuffers::Offset<fbs::CharacterLogic> payload) {
    fbb_.AddOffset(ServerCharacterLogic::VT_PAYLOAD, payload);
  }
  explicit ServerCharacterLogicBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerCharacterLogic> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerCharacterLogic>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerCharacterLogic> CreateServerCharacterLogic(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<fbs::CharacterLogic> payload = 0) {
  ServerCharacterLogicBuilder builder_(_fbb);
  builder_.add_payload(payload);
  return builder_.Finish();
}

::flatbuffers::Offset<ServerCharacterLogic> CreateServerCharacterLogic(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterLogicT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ServerCharacterInT : public ::flatbuffers::NativeTable {
  typedef ServerCharacterIn TableType;
  std::unique_ptr<fbs::PlayerT> player{};
  ServerCharacterInT() = default;
  ServerCharacterInT(const ServerCharacterInT &o);
  ServerCharacterInT(ServerCharacterInT&&) FLATBUFFERS_NOEXCEPT = default;
  ServerCharacterInT &operator=(ServerCharacterInT o) FLATBUFFERS_NOEXCEPT;
};

struct ServerCharacterIn FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerCharacterInT NativeTableType;
  typedef ServerCharacterInBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PLAYER = 4
  };
  const fbs::Player *player() const {
    return GetPointer<const fbs::Player *>(VT_PLAYER);
  }
  fbs::Player *mutable_player() {
    return GetPointer<fbs::Player *>(VT_PLAYER);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PLAYER) &&
           verifier.VerifyTable(player()) &&
           verifier.EndTable();
  }
  ServerCharacterInT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ServerCharacterInT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ServerCharacterIn> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterInT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ServerCharacterInBuilder {
  typedef ServerCharacterIn Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_player(::flatbuffers::Offset<fbs::Player> player) {
    fbb_.AddOffset(ServerCharacterIn::VT_PLAYER, player);
  }
  explicit ServerCharacterInBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerCharacterIn> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerCharacterIn>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerCharacterIn> CreateServerCharacterIn(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<fbs::Player> player = 0) {
  ServerCharacterInBuilder builder_(_fbb);
  builder_.add_player(player);
  return builder_.Finish();
}

::flatbuffers::Offset<ServerCharacterIn> CreateServerCharacterIn(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterInT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ServerCharacterOutT : public ::flatbuffers::NativeTable {
  typedef ServerCharacterOut TableType;
  uint64_t client_id = 0;
};

struct ServerCharacterOut FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerCharacterOutT NativeTableType;
  typedef ServerCharacterOutBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLIENT_ID = 4
  };
  uint64_t client_id() const {
    return GetField<uint64_t>(VT_CLIENT_ID, 0);
  }
  bool mutate_client_id(uint64_t _client_id = 0) {
    return SetField<uint64_t>(VT_CLIENT_ID, _client_id, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CLIENT_ID, 8) &&
           verifier.EndTable();
  }
  ServerCharacterOutT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ServerCharacterOutT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ServerCharacterOut> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterOutT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ServerCharacterOutBuilder {
  typedef ServerCharacterOut Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_client_id(uint64_t client_id) {
    fbb_.AddElement<uint64_t>(ServerCharacterOut::VT_CLIENT_ID, client_id, 0);
  }
  explicit ServerCharacterOutBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerCharacterOut> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerCharacterOut>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerCharacterOut> CreateServerCharacterOut(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t client_id = 0) {
  ServerCharacterOutBuilder builder_(_fbb);
  builder_.add_client_id(client_id);
  return builder_.Finish();
}

::flatbuffers::Offset<ServerCharacterOut> CreateServerCharacterOut(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterOutT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ServerMobLogicT : public ::flatbuffers::NativeTable {
  typedef ServerMobLogic TableType;
  uint32_t map_id = 0;
  std::vector<std::unique_ptr<fbs::MobLogicT>> payload{};
  ServerMobLogicT() = default;
  ServerMobLogicT(const ServerMobLogicT &o);
  ServerMobLogicT(ServerMobLogicT&&) FLATBUFFERS_NOEXCEPT = default;
  ServerMobLogicT &operator=(ServerMobLogicT o) FLATBUFFERS_NOEXCEPT;
};

struct ServerMobLogic FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerMobLogicT NativeTableType;
  typedef ServerMobLogicBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MAP_ID = 4,
    VT_PAYLOAD = 6
  };
  uint32_t map_id() const {
    return GetField<uint32_t>(VT_MAP_ID, 0);
  }
  bool mutate_map_id(uint32_t _map_id = 0) {
    return SetField<uint32_t>(VT_MAP_ID, _map_id, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::MobLogic>> *payload() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::MobLogic>> *>(VT_PAYLOAD);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<fbs::MobLogic>> *mutable_payload() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<fbs::MobLogic>> *>(VT_PAYLOAD);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_MAP_ID, 4) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           verifier.VerifyVector(payload()) &&
           verifier.VerifyVectorOfTables(payload()) &&
           verifier.EndTable();
  }
  ServerMobLogicT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ServerMobLogicT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ServerMobLogic> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerMobLogicT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ServerMobLogicBuilder {
  typedef ServerMobLogic Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_map_id(uint32_t map_id) {
    fbb_.AddElement<uint32_t>(ServerMobLogic::VT_MAP_ID, map_id, 0);
  }
  void add_payload(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::MobLogic>>> payload) {
    fbb_.AddOffset(ServerMobLogic::VT_PAYLOAD, payload);
  }
  explicit ServerMobLogicBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerMobLogic> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerMobLogic>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerMobLogic> CreateServerMobLogic(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t map_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::MobLogic>>> payload = 0) {
  ServerMobLogicBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_map_id(map_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ServerMobLogic> CreateServerMobLogicDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t map_id = 0,
    const std::vector<::flatbuffers::Offset<fbs::MobLogic>> *payload = nullptr) {
  auto payload__ = payload ? _fbb.CreateVector<::flatbuffers::Offset<fbs::MobLogic>>(*payload) : 0;
  return fbs::CreateServerMobLogic(
      _fbb,
      map_id,
      payload__);
}

::flatbuffers::Offset<ServerMobLogic> CreateServerMobLogic(::flatbuffers::FlatBufferBuilder &_fbb, const ServerMobLogicT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ServerCharacterAttackT : public ::flatbuffers::NativeTable {
  typedef ServerCharacterAttack TableType;
  uint64_t client_id = 0;
  std::vector<std::unique_ptr<fbs::CharacterAttackT>> payload{};
  ServerCharacterAttackT() = default;
  ServerCharacterAttackT(const ServerCharacterAttackT &o);
  ServerCharacterAttackT(ServerCharacterAttackT&&) FLATBUFFERS_NOEXCEPT = default;
  ServerCharacterAttackT &operator=(ServerCharacterAttackT o) FLATBUFFERS_NOEXCEPT;
};

struct ServerCharacterAttack FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerCharacterAttackT NativeTableType;
  typedef ServerCharacterAttackBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLIENT_ID = 4,
    VT_PAYLOAD = 6
  };
  uint64_t client_id() const {
    return GetField<uint64_t>(VT_CLIENT_ID, 0);
  }
  bool mutate_client_id(uint64_t _client_id = 0) {
    return SetField<uint64_t>(VT_CLIENT_ID, _client_id, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterAttack>> *payload() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterAttack>> *>(VT_PAYLOAD);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterAttack>> *mutable_payload() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterAttack>> *>(VT_PAYLOAD);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CLIENT_ID, 8) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           verifier.VerifyVector(payload()) &&
           verifier.VerifyVectorOfTables(payload()) &&
           verifier.EndTable();
  }
  ServerCharacterAttackT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ServerCharacterAttackT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ServerCharacterAttack> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterAttackT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ServerCharacterAttackBuilder {
  typedef ServerCharacterAttack Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_client_id(uint64_t client_id) {
    fbb_.AddElement<uint64_t>(ServerCharacterAttack::VT_CLIENT_ID, client_id, 0);
  }
  void add_payload(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterAttack>>> payload) {
    fbb_.AddOffset(ServerCharacterAttack::VT_PAYLOAD, payload);
  }
  explicit ServerCharacterAttackBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerCharacterAttack> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerCharacterAttack>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerCharacterAttack> CreateServerCharacterAttack(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t client_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterAttack>>> payload = 0) {
  ServerCharacterAttackBuilder builder_(_fbb);
  builder_.add_client_id(client_id);
  builder_.add_payload(payload);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ServerCharacterAttack> CreateServerCharacterAttackDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t client_id = 0,
    const std::vector<::flatbuffers::Offset<fbs::CharacterAttack>> *payload = nullptr) {
  auto payload__ = payload ? _fbb.CreateVector<::flatbuffers::Offset<fbs::CharacterAttack>>(*payload) : 0;
  return fbs::CreateServerCharacterAttack(
      _fbb,
      client_id,
      payload__);
}

::flatbuffers::Offset<ServerCharacterAttack> CreateServerCharacterAttack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterAttackT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ServerCharacterSkillT : public ::flatbuffers::NativeTable {
  typedef ServerCharacterSkill TableType;
  uint32_t ski_id = 0;
  uint64_t client_id = 0;
  std::vector<std::unique_ptr<fbs::CharacterSkillT>> payload{};
  ServerCharacterSkillT() = default;
  ServerCharacterSkillT(const ServerCharacterSkillT &o);
  ServerCharacterSkillT(ServerCharacterSkillT&&) FLATBUFFERS_NOEXCEPT = default;
  ServerCharacterSkillT &operator=(ServerCharacterSkillT o) FLATBUFFERS_NOEXCEPT;
};

struct ServerCharacterSkill FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerCharacterSkillT NativeTableType;
  typedef ServerCharacterSkillBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SKI_ID = 4,
    VT_CLIENT_ID = 6,
    VT_PAYLOAD = 8
  };
  uint32_t ski_id() const {
    return GetField<uint32_t>(VT_SKI_ID, 0);
  }
  bool mutate_ski_id(uint32_t _ski_id = 0) {
    return SetField<uint32_t>(VT_SKI_ID, _ski_id, 0);
  }
  uint64_t client_id() const {
    return GetField<uint64_t>(VT_CLIENT_ID, 0);
  }
  bool mutate_client_id(uint64_t _client_id = 0) {
    return SetField<uint64_t>(VT_CLIENT_ID, _client_id, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterSkill>> *payload() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterSkill>> *>(VT_PAYLOAD);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterSkill>> *mutable_payload() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterSkill>> *>(VT_PAYLOAD);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_SKI_ID, 4) &&
           VerifyField<uint64_t>(verifier, VT_CLIENT_ID, 8) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           verifier.VerifyVector(payload()) &&
           verifier.VerifyVectorOfTables(payload()) &&
           verifier.EndTable();
  }
  ServerCharacterSkillT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ServerCharacterSkillT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ServerCharacterSkill> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterSkillT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ServerCharacterSkillBuilder {
  typedef ServerCharacterSkill Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_ski_id(uint32_t ski_id) {
    fbb_.AddElement<uint32_t>(ServerCharacterSkill::VT_SKI_ID, ski_id, 0);
  }
  void add_client_id(uint64_t client_id) {
    fbb_.AddElement<uint64_t>(ServerCharacterSkill::VT_CLIENT_ID, client_id, 0);
  }
  void add_payload(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterSkill>>> payload) {
    fbb_.AddOffset(ServerCharacterSkill::VT_PAYLOAD, payload);
  }
  explicit ServerCharacterSkillBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerCharacterSkill> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerCharacterSkill>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerCharacterSkill> CreateServerCharacterSkill(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t ski_id = 0,
    uint64_t client_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterSkill>>> payload = 0) {
  ServerCharacterSkillBuilder builder_(_fbb);
  builder_.add_client_id(client_id);
  builder_.add_payload(payload);
  builder_.add_ski_id(ski_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ServerCharacterSkill> CreateServerCharacterSkillDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t ski_id = 0,
    uint64_t client_id = 0,
    const std::vector<::flatbuffers::Offset<fbs::CharacterSkill>> *payload = nullptr) {
  auto payload__ = payload ? _fbb.CreateVector<::flatbuffers::Offset<fbs::CharacterSkill>>(*payload) : 0;
  return fbs::CreateServerCharacterSkill(
      _fbb,
      ski_id,
      client_id,
      payload__);
}

::flatbuffers::Offset<ServerCharacterSkill> CreateServerCharacterSkill(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterSkillT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ServerCharacterBallT : public ::flatbuffers::NativeTable {
  typedef ServerCharacterBall TableType;
  uint64_t client_id = 0;
  std::vector<std::unique_ptr<fbs::CharacterBallT>> payload{};
  ServerCharacterBallT() = default;
  ServerCharacterBallT(const ServerCharacterBallT &o);
  ServerCharacterBallT(ServerCharacterBallT&&) FLATBUFFERS_NOEXCEPT = default;
  ServerCharacterBallT &operator=(ServerCharacterBallT o) FLATBUFFERS_NOEXCEPT;
};

struct ServerCharacterBall FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerCharacterBallT NativeTableType;
  typedef ServerCharacterBallBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLIENT_ID = 4,
    VT_PAYLOAD = 6
  };
  uint64_t client_id() const {
    return GetField<uint64_t>(VT_CLIENT_ID, 0);
  }
  bool mutate_client_id(uint64_t _client_id = 0) {
    return SetField<uint64_t>(VT_CLIENT_ID, _client_id, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterBall>> *payload() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterBall>> *>(VT_PAYLOAD);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterBall>> *mutable_payload() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterBall>> *>(VT_PAYLOAD);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CLIENT_ID, 8) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           verifier.VerifyVector(payload()) &&
           verifier.VerifyVectorOfTables(payload()) &&
           verifier.EndTable();
  }
  ServerCharacterBallT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ServerCharacterBallT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ServerCharacterBall> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterBallT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ServerCharacterBallBuilder {
  typedef ServerCharacterBall Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_client_id(uint64_t client_id) {
    fbb_.AddElement<uint64_t>(ServerCharacterBall::VT_CLIENT_ID, client_id, 0);
  }
  void add_payload(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterBall>>> payload) {
    fbb_.AddOffset(ServerCharacterBall::VT_PAYLOAD, payload);
  }
  explicit ServerCharacterBallBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerCharacterBall> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerCharacterBall>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerCharacterBall> CreateServerCharacterBall(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t client_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fbs::CharacterBall>>> payload = 0) {
  ServerCharacterBallBuilder builder_(_fbb);
  builder_.add_client_id(client_id);
  builder_.add_payload(payload);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ServerCharacterBall> CreateServerCharacterBallDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t client_id = 0,
    const std::vector<::flatbuffers::Offset<fbs::CharacterBall>> *payload = nullptr) {
  auto payload__ = payload ? _fbb.CreateVector<::flatbuffers::Offset<fbs::CharacterBall>>(*payload) : 0;
  return fbs::CreateServerCharacterBall(
      _fbb,
      client_id,
      payload__);
}

::flatbuffers::Offset<ServerCharacterBall> CreateServerCharacterBall(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterBallT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ServerMobAttackT : public ::flatbuffers::NativeTable {
  typedef ServerMobAttack TableType;
  uint64_t client_id = 0;
  std::unique_ptr<fbs::MobAttackT> payload{};
  ServerMobAttackT() = default;
  ServerMobAttackT(const ServerMobAttackT &o);
  ServerMobAttackT(ServerMobAttackT&&) FLATBUFFERS_NOEXCEPT = default;
  ServerMobAttackT &operator=(ServerMobAttackT o) FLATBUFFERS_NOEXCEPT;
};

struct ServerMobAttack FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerMobAttackT NativeTableType;
  typedef ServerMobAttackBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLIENT_ID = 4,
    VT_PAYLOAD = 6
  };
  uint64_t client_id() const {
    return GetField<uint64_t>(VT_CLIENT_ID, 0);
  }
  bool mutate_client_id(uint64_t _client_id = 0) {
    return SetField<uint64_t>(VT_CLIENT_ID, _client_id, 0);
  }
  const fbs::MobAttack *payload() const {
    return GetPointer<const fbs::MobAttack *>(VT_PAYLOAD);
  }
  fbs::MobAttack *mutable_payload() {
    return GetPointer<fbs::MobAttack *>(VT_PAYLOAD);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CLIENT_ID, 8) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           verifier.VerifyTable(payload()) &&
           verifier.EndTable();
  }
  ServerMobAttackT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ServerMobAttackT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ServerMobAttack> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerMobAttackT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ServerMobAttackBuilder {
  typedef ServerMobAttack Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_client_id(uint64_t client_id) {
    fbb_.AddElement<uint64_t>(ServerMobAttack::VT_CLIENT_ID, client_id, 0);
  }
  void add_payload(::flatbuffers::Offset<fbs::MobAttack> payload) {
    fbb_.AddOffset(ServerMobAttack::VT_PAYLOAD, payload);
  }
  explicit ServerMobAttackBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerMobAttack> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerMobAttack>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerMobAttack> CreateServerMobAttack(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t client_id = 0,
    ::flatbuffers::Offset<fbs::MobAttack> payload = 0) {
  ServerMobAttackBuilder builder_(_fbb);
  builder_.add_client_id(client_id);
  builder_.add_payload(payload);
  return builder_.Finish();
}

::flatbuffers::Offset<ServerMobAttack> CreateServerMobAttack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerMobAttackT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ServerCharacterChatT : public ::flatbuffers::NativeTable {
  typedef ServerCharacterChat TableType;
  uint64_t client_id = 0;
  std::unique_ptr<fbs::CharacterChatT> payload{};
  ServerCharacterChatT() = default;
  ServerCharacterChatT(const ServerCharacterChatT &o);
  ServerCharacterChatT(ServerCharacterChatT&&) FLATBUFFERS_NOEXCEPT = default;
  ServerCharacterChatT &operator=(ServerCharacterChatT o) FLATBUFFERS_NOEXCEPT;
};

struct ServerCharacterChat FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerCharacterChatT NativeTableType;
  typedef ServerCharacterChatBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLIENT_ID = 4,
    VT_PAYLOAD = 6
  };
  uint64_t client_id() const {
    return GetField<uint64_t>(VT_CLIENT_ID, 0);
  }
  bool mutate_client_id(uint64_t _client_id = 0) {
    return SetField<uint64_t>(VT_CLIENT_ID, _client_id, 0);
  }
  const fbs::CharacterChat *payload() const {
    return GetPointer<const fbs::CharacterChat *>(VT_PAYLOAD);
  }
  fbs::CharacterChat *mutable_payload() {
    return GetPointer<fbs::CharacterChat *>(VT_PAYLOAD);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CLIENT_ID, 8) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           verifier.VerifyTable(payload()) &&
           verifier.EndTable();
  }
  ServerCharacterChatT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ServerCharacterChatT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ServerCharacterChat> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterChatT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ServerCharacterChatBuilder {
  typedef ServerCharacterChat Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_client_id(uint64_t client_id) {
    fbb_.AddElement<uint64_t>(ServerCharacterChat::VT_CLIENT_ID, client_id, 0);
  }
  void add_payload(::flatbuffers::Offset<fbs::CharacterChat> payload) {
    fbb_.AddOffset(ServerCharacterChat::VT_PAYLOAD, payload);
  }
  explicit ServerCharacterChatBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerCharacterChat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerCharacterChat>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerCharacterChat> CreateServerCharacterChat(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t client_id = 0,
    ::flatbuffers::Offset<fbs::CharacterChat> payload = 0) {
  ServerCharacterChatBuilder builder_(_fbb);
  builder_.add_client_id(client_id);
  builder_.add_payload(payload);
  return builder_.Finish();
}

::flatbuffers::Offset<ServerCharacterChat> CreateServerCharacterChat(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterChatT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline ServerHeartbeatT *ServerHeartbeat::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ServerHeartbeatT>(new ServerHeartbeatT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ServerHeartbeat::UnPackTo(ServerHeartbeatT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
}

inline ::flatbuffers::Offset<ServerHeartbeat> CreateServerHeartbeat(::flatbuffers::FlatBufferBuilder &_fbb, const ServerHeartbeatT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ServerHeartbeat::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ServerHeartbeat> ServerHeartbeat::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerHeartbeatT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ServerHeartbeatT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  return fbs::CreateServerHeartbeat(
      _fbb);
}

inline ServerSceneT::ServerSceneT(const ServerSceneT &o)
      : map_id(o.map_id),
        your_id(o.your_id) {
  players.reserve(o.players.size());
  for (const auto &players_ : o.players) { players.emplace_back((players_) ? new fbs::PlayerT(*players_) : nullptr); }
  mobs.reserve(o.mobs.size());
  for (const auto &mobs_ : o.mobs) { mobs.emplace_back((mobs_) ? new fbs::MobT(*mobs_) : nullptr); }
}

inline ServerSceneT &ServerSceneT::operator=(ServerSceneT o) FLATBUFFERS_NOEXCEPT {
  std::swap(map_id, o.map_id);
  std::swap(your_id, o.your_id);
  std::swap(players, o.players);
  std::swap(mobs, o.mobs);
  return *this;
}

inline ServerSceneT *ServerScene::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ServerSceneT>(new ServerSceneT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ServerScene::UnPackTo(ServerSceneT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = map_id(); _o->map_id = _e; }
  { auto _e = your_id(); _o->your_id = _e; }
  { auto _e = players(); if (_e) { _o->players.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->players[_i]) { _e->Get(_i)->UnPackTo(_o->players[_i].get(), _resolver); } else { _o->players[_i] = std::unique_ptr<fbs::PlayerT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->players.resize(0); } }
  { auto _e = mobs(); if (_e) { _o->mobs.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->mobs[_i]) { _e->Get(_i)->UnPackTo(_o->mobs[_i].get(), _resolver); } else { _o->mobs[_i] = std::unique_ptr<fbs::MobT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->mobs.resize(0); } }
}

inline ::flatbuffers::Offset<ServerScene> CreateServerScene(::flatbuffers::FlatBufferBuilder &_fbb, const ServerSceneT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ServerScene::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ServerScene> ServerScene::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerSceneT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ServerSceneT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _map_id = _o->map_id;
  auto _your_id = _o->your_id;
  auto _players = _o->players.size() ? _fbb.CreateVector<::flatbuffers::Offset<fbs::Player>> (_o->players.size(), [](size_t i, _VectorArgs *__va) { return CreatePlayer(*__va->__fbb, __va->__o->players[i].get(), __va->__rehasher); }, &_va ) : 0;
  auto _mobs = _o->mobs.size() ? _fbb.CreateVector<::flatbuffers::Offset<fbs::Mob>> (_o->mobs.size(), [](size_t i, _VectorArgs *__va) { return CreateMob(*__va->__fbb, __va->__o->mobs[i].get(), __va->__rehasher); }, &_va ) : 0;
  return fbs::CreateServerScene(
      _fbb,
      _map_id,
      _your_id,
      _players,
      _mobs);
}

inline ServerCharacterLogicT::ServerCharacterLogicT(const ServerCharacterLogicT &o)
      : payload((o.payload) ? new fbs::CharacterLogicT(*o.payload) : nullptr) {
}

inline ServerCharacterLogicT &ServerCharacterLogicT::operator=(ServerCharacterLogicT o) FLATBUFFERS_NOEXCEPT {
  std::swap(payload, o.payload);
  return *this;
}

inline ServerCharacterLogicT *ServerCharacterLogic::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ServerCharacterLogicT>(new ServerCharacterLogicT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ServerCharacterLogic::UnPackTo(ServerCharacterLogicT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = payload(); if (_e) { if(_o->payload) { _e->UnPackTo(_o->payload.get(), _resolver); } else { _o->payload = std::unique_ptr<fbs::CharacterLogicT>(_e->UnPack(_resolver)); } } else if (_o->payload) { _o->payload.reset(); } }
}

inline ::flatbuffers::Offset<ServerCharacterLogic> CreateServerCharacterLogic(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterLogicT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ServerCharacterLogic::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ServerCharacterLogic> ServerCharacterLogic::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterLogicT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ServerCharacterLogicT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _payload = _o->payload ? CreateCharacterLogic(_fbb, _o->payload.get(), _rehasher) : 0;
  return fbs::CreateServerCharacterLogic(
      _fbb,
      _payload);
}

inline ServerCharacterInT::ServerCharacterInT(const ServerCharacterInT &o)
      : player((o.player) ? new fbs::PlayerT(*o.player) : nullptr) {
}

inline ServerCharacterInT &ServerCharacterInT::operator=(ServerCharacterInT o) FLATBUFFERS_NOEXCEPT {
  std::swap(player, o.player);
  return *this;
}

inline ServerCharacterInT *ServerCharacterIn::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ServerCharacterInT>(new ServerCharacterInT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ServerCharacterIn::UnPackTo(ServerCharacterInT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = player(); if (_e) { if(_o->player) { _e->UnPackTo(_o->player.get(), _resolver); } else { _o->player = std::unique_ptr<fbs::PlayerT>(_e->UnPack(_resolver)); } } else if (_o->player) { _o->player.reset(); } }
}

inline ::flatbuffers::Offset<ServerCharacterIn> CreateServerCharacterIn(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterInT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ServerCharacterIn::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ServerCharacterIn> ServerCharacterIn::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterInT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ServerCharacterInT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _player = _o->player ? CreatePlayer(_fbb, _o->player.get(), _rehasher) : 0;
  return fbs::CreateServerCharacterIn(
      _fbb,
      _player);
}

inline ServerCharacterOutT *ServerCharacterOut::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ServerCharacterOutT>(new ServerCharacterOutT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ServerCharacterOut::UnPackTo(ServerCharacterOutT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = client_id(); _o->client_id = _e; }
}

inline ::flatbuffers::Offset<ServerCharacterOut> CreateServerCharacterOut(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterOutT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ServerCharacterOut::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ServerCharacterOut> ServerCharacterOut::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterOutT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ServerCharacterOutT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _client_id = _o->client_id;
  return fbs::CreateServerCharacterOut(
      _fbb,
      _client_id);
}

inline ServerMobLogicT::ServerMobLogicT(const ServerMobLogicT &o)
      : map_id(o.map_id) {
  payload.reserve(o.payload.size());
  for (const auto &payload_ : o.payload) { payload.emplace_back((payload_) ? new fbs::MobLogicT(*payload_) : nullptr); }
}

inline ServerMobLogicT &ServerMobLogicT::operator=(ServerMobLogicT o) FLATBUFFERS_NOEXCEPT {
  std::swap(map_id, o.map_id);
  std::swap(payload, o.payload);
  return *this;
}

inline ServerMobLogicT *ServerMobLogic::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ServerMobLogicT>(new ServerMobLogicT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ServerMobLogic::UnPackTo(ServerMobLogicT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = map_id(); _o->map_id = _e; }
  { auto _e = payload(); if (_e) { _o->payload.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->payload[_i]) { _e->Get(_i)->UnPackTo(_o->payload[_i].get(), _resolver); } else { _o->payload[_i] = std::unique_ptr<fbs::MobLogicT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->payload.resize(0); } }
}

inline ::flatbuffers::Offset<ServerMobLogic> CreateServerMobLogic(::flatbuffers::FlatBufferBuilder &_fbb, const ServerMobLogicT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ServerMobLogic::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ServerMobLogic> ServerMobLogic::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerMobLogicT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ServerMobLogicT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _map_id = _o->map_id;
  auto _payload = _o->payload.size() ? _fbb.CreateVector<::flatbuffers::Offset<fbs::MobLogic>> (_o->payload.size(), [](size_t i, _VectorArgs *__va) { return CreateMobLogic(*__va->__fbb, __va->__o->payload[i].get(), __va->__rehasher); }, &_va ) : 0;
  return fbs::CreateServerMobLogic(
      _fbb,
      _map_id,
      _payload);
}

inline ServerCharacterAttackT::ServerCharacterAttackT(const ServerCharacterAttackT &o)
      : client_id(o.client_id) {
  payload.reserve(o.payload.size());
  for (const auto &payload_ : o.payload) { payload.emplace_back((payload_) ? new fbs::CharacterAttackT(*payload_) : nullptr); }
}

inline ServerCharacterAttackT &ServerCharacterAttackT::operator=(ServerCharacterAttackT o) FLATBUFFERS_NOEXCEPT {
  std::swap(client_id, o.client_id);
  std::swap(payload, o.payload);
  return *this;
}

inline ServerCharacterAttackT *ServerCharacterAttack::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ServerCharacterAttackT>(new ServerCharacterAttackT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ServerCharacterAttack::UnPackTo(ServerCharacterAttackT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = client_id(); _o->client_id = _e; }
  { auto _e = payload(); if (_e) { _o->payload.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->payload[_i]) { _e->Get(_i)->UnPackTo(_o->payload[_i].get(), _resolver); } else { _o->payload[_i] = std::unique_ptr<fbs::CharacterAttackT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->payload.resize(0); } }
}

inline ::flatbuffers::Offset<ServerCharacterAttack> CreateServerCharacterAttack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterAttackT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ServerCharacterAttack::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ServerCharacterAttack> ServerCharacterAttack::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterAttackT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ServerCharacterAttackT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _client_id = _o->client_id;
  auto _payload = _o->payload.size() ? _fbb.CreateVector<::flatbuffers::Offset<fbs::CharacterAttack>> (_o->payload.size(), [](size_t i, _VectorArgs *__va) { return CreateCharacterAttack(*__va->__fbb, __va->__o->payload[i].get(), __va->__rehasher); }, &_va ) : 0;
  return fbs::CreateServerCharacterAttack(
      _fbb,
      _client_id,
      _payload);
}

inline ServerCharacterSkillT::ServerCharacterSkillT(const ServerCharacterSkillT &o)
      : ski_id(o.ski_id),
        client_id(o.client_id) {
  payload.reserve(o.payload.size());
  for (const auto &payload_ : o.payload) { payload.emplace_back((payload_) ? new fbs::CharacterSkillT(*payload_) : nullptr); }
}

inline ServerCharacterSkillT &ServerCharacterSkillT::operator=(ServerCharacterSkillT o) FLATBUFFERS_NOEXCEPT {
  std::swap(ski_id, o.ski_id);
  std::swap(client_id, o.client_id);
  std::swap(payload, o.payload);
  return *this;
}

inline ServerCharacterSkillT *ServerCharacterSkill::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ServerCharacterSkillT>(new ServerCharacterSkillT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ServerCharacterSkill::UnPackTo(ServerCharacterSkillT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = ski_id(); _o->ski_id = _e; }
  { auto _e = client_id(); _o->client_id = _e; }
  { auto _e = payload(); if (_e) { _o->payload.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->payload[_i]) { _e->Get(_i)->UnPackTo(_o->payload[_i].get(), _resolver); } else { _o->payload[_i] = std::unique_ptr<fbs::CharacterSkillT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->payload.resize(0); } }
}

inline ::flatbuffers::Offset<ServerCharacterSkill> CreateServerCharacterSkill(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterSkillT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ServerCharacterSkill::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ServerCharacterSkill> ServerCharacterSkill::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterSkillT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ServerCharacterSkillT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _ski_id = _o->ski_id;
  auto _client_id = _o->client_id;
  auto _payload = _o->payload.size() ? _fbb.CreateVector<::flatbuffers::Offset<fbs::CharacterSkill>> (_o->payload.size(), [](size_t i, _VectorArgs *__va) { return CreateCharacterSkill(*__va->__fbb, __va->__o->payload[i].get(), __va->__rehasher); }, &_va ) : 0;
  return fbs::CreateServerCharacterSkill(
      _fbb,
      _ski_id,
      _client_id,
      _payload);
}

inline ServerCharacterBallT::ServerCharacterBallT(const ServerCharacterBallT &o)
      : client_id(o.client_id) {
  payload.reserve(o.payload.size());
  for (const auto &payload_ : o.payload) { payload.emplace_back((payload_) ? new fbs::CharacterBallT(*payload_) : nullptr); }
}

inline ServerCharacterBallT &ServerCharacterBallT::operator=(ServerCharacterBallT o) FLATBUFFERS_NOEXCEPT {
  std::swap(client_id, o.client_id);
  std::swap(payload, o.payload);
  return *this;
}

inline ServerCharacterBallT *ServerCharacterBall::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ServerCharacterBallT>(new ServerCharacterBallT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ServerCharacterBall::UnPackTo(ServerCharacterBallT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = client_id(); _o->client_id = _e; }
  { auto _e = payload(); if (_e) { _o->payload.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->payload[_i]) { _e->Get(_i)->UnPackTo(_o->payload[_i].get(), _resolver); } else { _o->payload[_i] = std::unique_ptr<fbs::CharacterBallT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->payload.resize(0); } }
}

inline ::flatbuffers::Offset<ServerCharacterBall> CreateServerCharacterBall(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterBallT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ServerCharacterBall::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ServerCharacterBall> ServerCharacterBall::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterBallT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ServerCharacterBallT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _client_id = _o->client_id;
  auto _payload = _o->payload.size() ? _fbb.CreateVector<::flatbuffers::Offset<fbs::CharacterBall>> (_o->payload.size(), [](size_t i, _VectorArgs *__va) { return CreateCharacterBall(*__va->__fbb, __va->__o->payload[i].get(), __va->__rehasher); }, &_va ) : 0;
  return fbs::CreateServerCharacterBall(
      _fbb,
      _client_id,
      _payload);
}

inline ServerMobAttackT::ServerMobAttackT(const ServerMobAttackT &o)
      : client_id(o.client_id),
        payload((o.payload) ? new fbs::MobAttackT(*o.payload) : nullptr) {
}

inline ServerMobAttackT &ServerMobAttackT::operator=(ServerMobAttackT o) FLATBUFFERS_NOEXCEPT {
  std::swap(client_id, o.client_id);
  std::swap(payload, o.payload);
  return *this;
}

inline ServerMobAttackT *ServerMobAttack::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ServerMobAttackT>(new ServerMobAttackT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ServerMobAttack::UnPackTo(ServerMobAttackT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = client_id(); _o->client_id = _e; }
  { auto _e = payload(); if (_e) { if(_o->payload) { _e->UnPackTo(_o->payload.get(), _resolver); } else { _o->payload = std::unique_ptr<fbs::MobAttackT>(_e->UnPack(_resolver)); } } else if (_o->payload) { _o->payload.reset(); } }
}

inline ::flatbuffers::Offset<ServerMobAttack> CreateServerMobAttack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerMobAttackT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ServerMobAttack::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ServerMobAttack> ServerMobAttack::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerMobAttackT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ServerMobAttackT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _client_id = _o->client_id;
  auto _payload = _o->payload ? CreateMobAttack(_fbb, _o->payload.get(), _rehasher) : 0;
  return fbs::CreateServerMobAttack(
      _fbb,
      _client_id,
      _payload);
}

inline ServerCharacterChatT::ServerCharacterChatT(const ServerCharacterChatT &o)
      : client_id(o.client_id),
        payload((o.payload) ? new fbs::CharacterChatT(*o.payload) : nullptr) {
}

inline ServerCharacterChatT &ServerCharacterChatT::operator=(ServerCharacterChatT o) FLATBUFFERS_NOEXCEPT {
  std::swap(client_id, o.client_id);
  std::swap(payload, o.payload);
  return *this;
}

inline ServerCharacterChatT *ServerCharacterChat::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ServerCharacterChatT>(new ServerCharacterChatT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ServerCharacterChat::UnPackTo(ServerCharacterChatT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = client_id(); _o->client_id = _e; }
  { auto _e = payload(); if (_e) { if(_o->payload) { _e->UnPackTo(_o->payload.get(), _resolver); } else { _o->payload = std::unique_ptr<fbs::CharacterChatT>(_e->UnPack(_resolver)); } } else if (_o->payload) { _o->payload.reset(); } }
}

inline ::flatbuffers::Offset<ServerCharacterChat> CreateServerCharacterChat(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterChatT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ServerCharacterChat::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ServerCharacterChat> ServerCharacterChat::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerCharacterChatT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ServerCharacterChatT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _client_id = _o->client_id;
  auto _payload = _o->payload ? CreateCharacterChat(_fbb, _o->payload.get(), _rehasher) : 0;
  return fbs::CreateServerCharacterChat(
      _fbb,
      _client_id,
      _payload);
}

}  // namespace fbs

#endif  // FLATBUFFERS_GENERATED_SERVER_FBS_H_
