include "common.fbs";

namespace fbs;      // 定义命名空间
// 心跳包
table ClientHeartbeat {
}

table ClientScene {
    fade:bool;
    map_id:uint32;
    character:Character;
}

table ClientCharacterAttack {
    payload:[CharacterAttack];
}

table ClientCharacterSkill {
    ski_id:uint32;
    ski_lv:uint8;
    payload:[CharacterSkill];
}

table ClientCharacterBall {
    payload:CharacterBall;
}

table ClientMobAttack {
    map_id:uint32;
    payload:Attack;
}

table ClientCharacterChat {
    map_id:uint32;
    payload:CharacterChat;
}

table ClientCharacterDrop {
    map_id:uint32;
    payload:Drop;
}

table ClientCharacter {
    map_id:uint32;
    payload:Character;
}

table ClientCharacterPick {
    map_id:uint32;
    random_id:uint64;
}

table ClientCharacterInfo {
   payload:uint64;
}

table ClientCharacterTrade {
   step:uint8;
   to_id:uint64;
   payload:[ItemUnion];
   confirm:bool;
}

table ClientCharacterState {
    map_id:uint32;
    payload:[State];
}

table ClientCharacterMv {
    map_id:uint32;
    payload:Movement;
}

table ClientCharacterFlip {
    map_id:uint32;
    payload:Flip;
}

table ClientCharacterAction {
    map_id:uint32;
    payload:Action;
}

table ClientCharacterDie {
    map_id:uint32;
    payload:Die;
}

table ClientCharacterFc {
    map_id:uint32;
    payload:Face;
}

table ClientCharacterParty {
    step:uint8;
    to_id:uint64;
    confirm:bool;
}