namespace fbs;      // 定义命名空间

table LifeState{
    x:float;
    y:float;

    action:string;
    action_index:uint32;
    action_animate:bool;

    page:uint8;
    flip:bool;
}

table CharacterAppearance{
    body:uint32;
    head:uint32;
    face:uint32;
    hair:uint32;
    ear:string;
}

table Character{
    name:[uint16];
    fame:int32;
    job:string;
    level:uint32;

    state:LifeState;
    appearance:CharacterAppearance;
    face:Face;

    equips:[Equip];
    decos:[Deco];

    states:[State];
}

table Movement{
    x1:float;
    y1:float;

    x2:float;
    y2:float;

    time:uint32;
    page:uint8;
}

table Flip{
    flip:bool;
}

table Action{
    action:string;
    action_index:uint32;
    action_animate:bool;
}

enum AttackEnum : uint8 {
    Red,
    Blue,
    Viole,
}

table Attack{
    delay:uint64;
    num:uint64;
    x:float;
    y:float;
    type:AttackEnum;
}

table Die{
    x:float;
    y:float;
}

table Ball{
    x1:float;
    y1:float;

    x2:float;
    y2:float;

    speed:float;

    mob:bool;
    mob_index:uint32;
    delay:uint64;
    page:uint8;
}

table CharacterBall{
    path:string;
    ball:Ball;
}

table CharacterAttack{
    mob_index:uint32;
    attack:Attack;
    afterimage:bool;
    left:bool;
}

table CharacterSkill{
    delay:uint64;
    mob:uint32;
    player:uint64;
    x:float;
    y:float;
}

table Player{
    client_id:uint64;
    character:Character;
}

table Mob{
    mob_index:uint32;
    mob_id:uint32;
    mob_hp:int64;
    state:LifeState;
}

table Face{
    face_action:string;
}

enum ChatEnum : int8 {
    MAP,
}

table CharacterChat{
    type:ChatEnum;
    payload:[uint16];
}

table EquipScroll{
    equip_id:uint32;
    scroll_id:uint32;
    success:bool;
}

table Equip{
    equip_id:uint32;
    scroll:[EquipScroll];
}

table Deco{
    deco_id:uint32;
}

table Item{
    item_id:uint32;
    item_num:uint32;
}

union ItemUnion {
    Equip,
    Item,
}

table Drop{
    random_id:uint64;
    drop:ItemUnion;

    x1:float;
    y1:float;

    x2:float;
    y2:float;

    page:uint8;
}

enum StateEnum : int8 {
    HP,
    MAX_HP,
    BUFF_SKILL,
    BUFF_ITEM,
    BUFF_ABNORMAL,
}

table State{
    state: StateEnum;
    val:int64;
    sub_val:int64;
}

table APSave{
    hp_ap:uint32;
    mp_ap:uint32;
   
    str_ap:uint32;
    dex_ap:uint32;
    int_ap:uint32;
    luk_ap:uint32;
}

table SPSave{
   id:uint32;
   val:uint32;
}

table PackageSave{
   index:uint32;
   data:ItemUnion;
   expire:uint64;
}

table QuestMobSave{
    mob_id:uint32;
    mob_num:uint32;
}

table QuestNPCSave{
    npc_id:uint32;
}

table QuestSave{
   id:string;
   index:uint8;
   complete:bool;
   mob:[QuestMobSave];
   npc:[QuestNPCSave];
}

table CharacterSave{
    character:Character;
    ap:APSave;
    sp:[SPSave];
    remain_ap:uint32;
    remain_sp:[uint32];
    package:[PackageSave];
    meso:uint64;
    map_id:uint32;
    portal_id:uint32;
    hp:uint32;
    mp:uint32;
    exp:uint64;
    quest:[QuestSave];
}

table PlayerSave{
    data:[CharacterSave];
}

table GameSave{
    username:string;
    data:PlayerSave;
}