include "client.fbs";
include "server.fbs";

namespace fbs;      // 定义命名空间

// 联合体：包含所有消息类型
union NetPayload {
    ClientHeartbeat,
    ClientScene,
    ClientCharacterMv,
    ClientCharacterFlip,
    ClientCharacterAction,
    ClientCharacterDie,
    ClientCharacterFc,
    ClientCharacterAttack,
    ClientCharacterSkill,
    ClientCharacterBall,
    ClientCharacterState,
    ClientMobAttack,
    ClientCharacterChat,
    ClientCharacterDrop,
    ClientCharacter,
    ClientCharacterPick,
    ClientCharacterInfo,
    ClientCharacterTrade,
    ClientCharacterParty,
    ClientReactor,
    ServerHeartbeat,
    ServerScene,
    ServerCharacterIn,
    ServerCharacterOut,
    ServerCharacterMv,
    ServerCharacterFlip,
    ServerCharacterAction,
    ServerCharacterDie,
    ServerCharacterFc,
    ServerCharacterAttack,
    ServerCharacterSkill,
    ServerCharacterBall,
    ServerCharacterChat,
    ServerCharacterDrop,
    ServerCharacter,
    ServerMobMv,
    ServerMobFlip,
    ServerMobAction,
    ServerMobState,
    ServerMobEvent,
    ServerMobAttack,
    ServerCharacterPick,
    ServerCharacterInfo,
    ServerCharacterTrade,
    ServerCharacterParty,
    ServerCharacterState,
    ServerDropFade,
    ServerReactor,
}
// 统一的网络包（最外层包装）
table NetPacket {
    payload:NetPayload;          // 实际数据
}

root_type NetPacket;