include "common.fbs";

namespace fbs;      // 定义命名空间

table ServerHeartbeat {
}

table ServerScene {
    map_id:uint32;
    fade:bool;
    
    players:[Player];
    mobs:[Mob];
}

table ServerCharacterLogic {
    payload:CharacterLogic;
}

table ServerCharacterIn {
    player:Player;
}

table ServerCharacterOut {
    client_id:uint64;
}

table ServerMobLogic {
    map_id:uint32;
    payload:[MobLogic];
}

table ServerCharacterAttack {
    client_id:uint64;
    payload:[CharacterAttack];
}

table ServerCharacterSkill {
    ski_id:uint32;
    ski_lv:uint8;
    client_id:uint64;
    payload:[CharacterSkill];
}

table ServerCharacterBall {
    client_id:uint64;
    payload:CharacterBall;
}

table ServerMobAttack {
    client_id:uint64;
    payload:MobAttack;
}

table ServerCharacterChat {
    client_id:uint64;
    name:[uint16];
    payload:CharacterChat;
}

table ServerCharacterDrop {
    client_id:uint64;
    payload:Drop;
}

table ServerCharacter {
    client_id:uint64;
    payload:Character;
}

table ServerCharacterPick {
    client_id:uint64;
    random_id:uint64;
}

table ServerCharacterInfo {
   payload:Character;
}

table ServerCharacterTrade {
   request:bool;
   player:Player;
   payload:[ItemUnion];
   confirm:bool;
}

table ServerMobDrop {
    payload:[Drop];
}