include "common.fbs";

namespace fbs;      // 定义命名空间

table ServerHeartbeat {
}

table ServerScene {
    map_id:uint32;
    fade:bool;
    
    players:[Player];
    mobs:[Mob];
    drops:[Drop];
    reactors:[Reactor];
}

table ServerCharacterIn {
    player:Player;
}

table ServerCharacterOut {
    client_id:uint64;
}

table ServerMobMv {
    mob_index:uint32;
    payload:Movement;
}

table ServerMobFlip {
    mob_index:uint32;
    payload:Flip;
}

table ServerMobAction {
    mob_index:uint32;
    payload:Action;
}

table ServerMobState {
    mob_index:uint32;
    payload:[State];
}

table ServerMobDie {
    mob_index:uint32;
}

table ServerMobDrop {
    mob_index:uint32;
    drop:[Drop];
}

union MobEventUnion {
    ServerMobMv,
    ServerMobFlip,
    ServerMobAction,
    ServerMobState,
    ServerMobDie,
    ServerMobDrop,
}

table ServerMobEvent {
    map_id:uint32;
    payload:[MobEventUnion];
}

table ServerCharacterAttack {
    client_id:uint64;
    payload:[CharacterAttack];
}

table ServerCharacterSkill {
    ski_id:uint32;
    ski_lv:uint8;
    client_id:uint64;
    payload:[CharacterSkill];
}

table ServerCharacterBall {
    client_id:uint64;
    payload:CharacterBall;
}

table ServerMobAttack {
    client_id:uint64;
    payload:Attack;
}

table ServerCharacterChat {
    client_id:uint64;
    name:[uint16];
    payload:CharacterChat;
}

table ServerCharacterDrop {
    client_id:uint64;
    payload:Drop;
}

table ServerCharacter {
    client_id:uint64;
    payload:Character;
}

table ServerCharacterPick {
    client_id:uint64;
    random_id:uint64;
    pet:bool;
    pet_index:int8;
}

table ServerCharacterInfo {
   payload:Character;
}

table ServerCharacterTrade {
   step:uint8;
   player:Player;
   payload:[ItemUnion];
}


table ServerCharacterMv {
    client_id:uint64;
    payload:Movement;
}

table ServerCharacterFlip {
    client_id:uint64;
    payload:Flip;
}

table ServerCharacterAction {
    client_id:uint64;
    payload:Action;
}

table ServerCharacterDie {
    client_id:uint64;
    payload:Die;
}

table ServerCharacterFc {
    client_id:uint64;
    payload:Face;
}

table ServerCharacterParty {
    step:uint8;
    to_id:uint64;
    
    players:[Player];
}

table ServerCharacterState {
    client_id:uint64;
    payload:[State];
}

table ServerDropFade {
    drop_ids:[uint64];
}

table ServerReactor {
    payload:Reactor;
}

table ServerReactorDrop {
    payload:[Drop];
}